using System;
using NovaOryn.Bus.Usb;
namespace NovaOryn.Usb.Hid;
public readonly struct UsbHidKeyboardEvent { public UsbHidKeyboardEvent(Byte usage,Boolean pressed,Char character,Byte modifiers){Usage=usage;Pressed=pressed;Character=character;Modifiers=modifiers;} public Byte Usage{get;} public Boolean Pressed{get;} public Char Character{get;} public Byte Modifiers{get;} }
public readonly struct UsbHidMouseState { public UsbHidMouseState(Int32 x,Int32 y,Int32 wheel,Byte buttons){X=x;Y=y;Wheel=wheel;Buttons=buttons;} public Int32 X{get;} public Int32 Y{get;} public Int32 Wheel{get;} public Byte Buttons{get;} }
public readonly struct UsbHidCapabilities { public UsbHidCapabilities(Boolean initialized,UInt32 keyboards,UInt32 mice,UInt64 keyboardReports,UInt64 mouseReports){Initialized=initialized;Keyboards=keyboards;Mice=mice;KeyboardReports=keyboardReports;MouseReports=mouseReports;} public Boolean Initialized{get;} public UInt32 Keyboards{get;} public UInt32 Mice{get;} public UInt64 KeyboardReports{get;} public UInt64 MouseReports{get;} }
public static unsafe class UsbHid
{
 private struct HidRec{internal Byte Used,Device,Endpoint,Protocol,MaxPacket;internal fixed Byte Previous[8];}
 private const Int32 Max=32; private static HidRec* _r; private static NovaOryn.Kernel.Heap.KernelHeapAllocation _a; private static Boolean _initialized;private static UInt64 _keyboardHandler;private static UInt32 _keyboards,_mice;private static UInt64 _kr,_mr;private static UsbHidMouseState _mouse;
 public static Boolean Initialize(){if(_initialized)return true;if(!NovaOryn.Kernel.Heap.KernelHeap.TryAllocate((UInt64)Max*(UInt64)sizeof(HidRec),64,true,out _a))return false;_r=(HidRec*)(nuint)_a.Address;_initialized=true;return Discover();}
 public static Boolean Discover(){if(!_initialized)return false;UInt32 count=KernelUsbBus.GetInterfaceCount();for(UInt32 i=0;i<count;i++){if(!KernelUsbBus.TryGetInterface(i,out UsbInterfaceInfo inf)||inf.Descriptor.Class!=(Byte)UsbClassCode.Hid||inf.Descriptor.SubClass!=1)continue;if(Find(inf.Device,inf.Descriptor.Protocol)>=0)continue;UsbEndpointDescriptor ep=default;Boolean found=false;for(UInt32 e=0;e<4;e++){if(inf.TryGetEndpoint(e,out UsbEndpointDescriptor x)&&x.In&&x.TransferType==UsbTransferType.Interrupt){ep=x;found=true;break;}}if(!found)continue;Int32 s=Free();if(s<0)return false;HidRec* r=_r+s;r->Used=1;r->Device=(Byte)inf.Device.Value;r->Endpoint=ep.Address;r->Protocol=inf.Descriptor.Protocol;r->MaxPacket=(Byte)(ep.MaximumPacketSize>64?64:ep.MaximumPacketSize);UsbSetupPacket setProtocol=new(0x21,11,0,inf.Descriptor.Number,0);KernelUsbBus.ControlTransfer(inf.Device,setProtocol,null,0,out _);UsbSetupPacket setIdle=new(0x21,10,0,inf.Descriptor.Number,0);KernelUsbBus.ControlTransfer(inf.Device,setIdle,null,0,out _);if(r->Protocol==1)_keyboards++;else if(r->Protocol==2)_mice++;}return true;}
 public static Boolean Service(){if(!_initialized)return false;Byte* report=stackalloc Byte[64];for(Int32 i=0;i<Max;i++){HidRec* r=_r+i;if(r->Used==0)continue;for(Int32 z=0;z<64;z++)report[z]=0;if(!KernelUsbBus.InterruptTransfer(new UsbDeviceHandle(r->Device),r->Endpoint,report,r->MaxPacket,out UInt32 got))continue;if(r->Protocol==1&&got>=8)DecodeKeyboard(r,report);else if(r->Protocol==2&&got>=3)DecodeMouse(report,got);}return true;}
 public static Boolean IsInitialized()=>_initialized; public static Boolean SetKeyboardEventHandler(delegate*<UsbHidKeyboardEvent,Boolean> handler){_keyboardHandler=(UInt64)(void*)handler;return true;} public static UsbHidCapabilities GetCapabilities()=>new(_initialized,_keyboards,_mice,_kr,_mr); public static UsbHidMouseState GetMouseState()=>_mouse;
 public static Char TranslateBootUsage(Byte u,Boolean shift){if(u>=4&&u<=29){Char c=(Char)('a'+u-4);return shift?(Char)(c-'a'+'A'):c;}if(u>=30&&u<=38){const String normal="123456789";const String shifted="!@#$%^&*(";return shift?shifted[u-30]:normal[u-30];}if(u==39)return shift?')':'0';if(u==40)return '\n';if(u==42)return '\b';if(u==43)return '\t';if(u==44)return ' ';if(u==45)return shift?'_':'-';if(u==46)return shift?'+':'=';if(u==47)return shift?'{':'[';if(u==48)return shift?'}':']';if(u==49)return shift?'|':'\\';if(u==51)return shift?':':';';if(u==52)return shift?'\"':'\'';if(u==53)return shift?'~':'`';if(u==54)return shift?'<':',';if(u==55)return shift?'>':'.';if(u==56)return shift?'?':'/';return '\0';}
 private static void DecodeKeyboard(HidRec* r,Byte* p){Boolean shift=(p[0]&0x22)!=0;for(Int32 q=2;q<8;q++){Byte u=r->Previous[q];if(u==0)continue;Boolean present=false;for(Int32 i=2;i<8;i++)if(p[i]==u)present=true;if(!present)Dispatch(new UsbHidKeyboardEvent(u,false,'\0',p[0]));}for(Int32 i=2;i<8;i++){Byte u=p[i];if(u==0)continue;Boolean old=false;for(Int32 q=2;q<8;q++)if(r->Previous[q]==u)old=true;if(!old)Dispatch(new UsbHidKeyboardEvent(u,true,TranslateBootUsage(u,shift),p[0]));}for(Int32 i=0;i<8;i++)r->Previous[i]=p[i];_kr++;} private static Boolean Dispatch(UsbHidKeyboardEvent e){if(_keyboardHandler==0)return true;var h=(delegate*<UsbHidKeyboardEvent,Boolean>)(void*)_keyboardHandler;return h(e);}
 private static void DecodeMouse(Byte* p,UInt32 n){Int32 dx=(SByte)p[1],dy=(SByte)p[2],wheel=n>3?(SByte)p[3]:0;_mouse=new UsbHidMouseState(_mouse.X+dx,_mouse.Y+dy,_mouse.Wheel+wheel,p[0]);_mr++;}
 private static Int32 Find(UsbDeviceHandle d,Byte proto){for(Int32 i=0;i<Max;i++)if((_r+i)->Used!=0&&(_r+i)->Device==(Byte)d.Value&&(_r+i)->Protocol==proto)return i;return -1;}private static Int32 Free(){for(Int32 i=0;i<Max;i++)if((_r+i)->Used==0)return i;return -1;}
}
