<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>NovaOryn.Kernel.Sample</RootNamespace>
    <AssemblyName>NovaOryn.Kernel.Sample</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NovaOryn.Architecture.X64\NovaOryn.Architecture.X64.csproj" />
    <ProjectReference Include="..\NovaOryn.Architecture.Contracts\NovaOryn.Architecture.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Architecture.X64.Descriptors\NovaOryn.Architecture.X64.Descriptors.csproj" />
    <ProjectReference Include="..\NovaOryn.Architecture.X64.Interrupts\NovaOryn.Architecture.X64.Interrupts.csproj" />
    <ProjectReference Include="..\NovaOryn.InterruptControllers.Contracts\NovaOryn.InterruptControllers.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.InterruptControllers.X64\NovaOryn.InterruptControllers.X64.csproj" />
    <ProjectReference Include="..\NovaOryn.Interrupts.Contracts\NovaOryn.Interrupts.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Boot.Contracts\NovaOryn.Boot.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Boot.Memory\NovaOryn.Boot.Memory.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.Virtual.Contracts\NovaOryn.Memory.Virtual.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.Virtual.X64\NovaOryn.Memory.Virtual.X64.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.AddressSpace.Contracts\NovaOryn.Memory.AddressSpace.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.AddressSpace.X64\NovaOryn.Memory.AddressSpace.X64.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.Heap.Contracts\NovaOryn.Memory.Heap.Contracts.csproj" />
    <ProjectReference Include="..\NovaOryn.Memory.Heap\NovaOryn.Memory.Heap.csproj" />
    <ProjectReference Include="..\NovaOryn.Console.Serial\NovaOryn.Console.Serial.csproj" />
    <ProjectReference Include="..\NovaOryn.Console.Framebuffer\NovaOryn.Console.Framebuffer.csproj" />
    <ProjectReference Include="..\NovaOryn.Core\NovaOryn.Core.csproj" />
  </ItemGroup>
</Project>
