using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Script.Serialization;
using EnvDTE;
using Microsoft.VisualStudio.Shell;
namespace NovaOryn.VisualStudio;
internal sealed class NovaOrynConfigurationService
{
 private readonly NovaOrynPackage _package; private readonly DTE _dte;
 public NovaOrynConfigurationService(NovaOrynPackage package,DTE dte){_package=package??throw new ArgumentNullException(nameof(package));_dte=dte??throw new ArgumentNullException(nameof(dte));}
 public void ShowForSelectedProject(){ThreadHelper.ThrowIfNotOnUIThread();Project p=ResolveSelectedNovaOrynProject();if(p==null){_package.Output.WriteLine("[FAIL] Select a NovaOryn kernel project before opening Configuration Pages.");return;}ShowForProject(p,false);}
 public void ShowForProject(Project project,bool firstRunOnly){ThreadHelper.ThrowIfNotOnUIThread();string root=NovaOrynProjectRecognizer.TryGetProjectDirectory(project);if(string.IsNullOrWhiteSpace(root)||!File.Exists(Path.Combine(root,"NovaOrynProject.json")))return;string cp=Path.Combine(root,"NovaOryn.Configuration.json");var m=NovaOrynConfigurationModel.Load(cp);if(firstRunOnly&&m.Completed)return;var w=new NovaOrynConfigurationWindow(m,root);if(w.ShowDialog()!=true)return;Apply(root,w.Configuration);NovaOrynSolutionSynchronizer.EnsureUserlandProjectsLoaded(_dte,_package.Output);_package.Output.WriteLine($"[ OK ] NovaOryn project configuration applied: {root}");_package.Output.WriteLine($"[INFO] Architecture: {w.Configuration.Architecture}; kernel model: {w.Configuration.KernelModel}; development areas (missing): {string.Join(", ",w.Configuration.WorkAreas)}; supplied areas: {string.Join(", ",w.Configuration.GetSuppliedAreas())}");}
 private void Apply(string root,NovaOrynConfigurationModel c)
 {
  c.Version=3;c.Completed=true;c.WorkAreas=c.WorkAreas.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x,StringComparer.OrdinalIgnoreCase).ToList();c.Save(Path.Combine(root,"NovaOryn.Configuration.json"));
  WriteProps(root,c);WriteTargets(root,c);WriteWorkspaceGraph(root,c);UpdateProjectManifest(root,c);WritePlan(root,c);
 }
 private static void WriteProps(string root,NovaOrynConfigurationModel c)
 {
  string a=string.Equals(c.Architecture,"arm64",StringComparison.OrdinalIgnoreCase)?"NOVAORYN_ARCH_ARM64":string.Equals(c.Architecture,"riscv64",StringComparison.OrdinalIgnoreCase)?"NOVAORYN_ARCH_RISCV64":"NOVAORYN_ARCH_X64";
  string k=c.KernelModel=="Microkernel"?"NOVAORYN_KERNEL_MICROKERNEL":c.KernelModel=="Hybrid"?"NOVAORYN_KERNEL_HYBRID":"NOVAORYN_KERNEL_MONOLITHIC";
  var supplied=c.GetSuppliedAreas();var constants=new List<string>{a,k};foreach(string area in supplied){constants.Add("NOVAORYN_WORKAREA_"+NormalizeConstant(area));if(DomainForArea(c.KernelModel,area)=="Kernel")constants.Add("NOVAORYN_KERNELAREA_"+NormalizeConstant(area));}foreach(string area in c.WorkAreas)constants.Add("NOVAORYN_DEVELOPMENTAREA_"+NormalizeConstant(area));
  var b=new StringBuilder();b.AppendLine("<Project>");b.AppendLine("  <!-- Generated by NovaOryn Visual Studio Configuration Pages. Do not hand-edit. -->");b.AppendLine("  <PropertyGroup>");b.AppendLine("    <NovaOrynConfigurationVersion>3</NovaOrynConfigurationVersion>");b.AppendLine($"    <NovaOrynTargetArchitecture>{EscapeXml(c.Architecture)}</NovaOrynTargetArchitecture>");b.AppendLine($"    <NovaOrynKernelModel>{EscapeXml(c.KernelModel)}</NovaOrynKernelModel>");b.AppendLine($"    <NovaOrynBootProtocol>{EscapeXml(c.BootProtocol)}</NovaOrynBootProtocol>");b.AppendLine("    <NovaOrynConfigurationCompleted>true</NovaOrynConfigurationCompleted>");b.AppendLine($"    <NovaOrynWorkAreas>{EscapeXml(string.Join(";",c.GetSuppliedAreas()))}</NovaOrynWorkAreas>");b.AppendLine($"    <NovaOrynDevelopmentAreas>{EscapeXml(string.Join(";",c.WorkAreas))}</NovaOrynDevelopmentAreas>");b.AppendLine($"    <NovaOrynDefaultExecutionDomain>{DefaultDomain(c.KernelModel)}</NovaOrynDefaultExecutionDomain>");foreach(string area in NovaOrynConfigurationModel.AvailableWorkAreas)b.AppendLine($"    <NovaOrynKernelArea{SafeName(area)}>{(c.GetSuppliedAreas().Contains(area,StringComparer.OrdinalIgnoreCase)&&DomainForArea(c.KernelModel,area)=="Kernel"?"true":"false")}</NovaOrynKernelArea{SafeName(area)}>");b.AppendLine($"    <DefineConstants>$(DefineConstants);{string.Join(";",constants)}</DefineConstants>");b.AppendLine("  </PropertyGroup>");b.AppendLine("</Project>");File.WriteAllText(Path.Combine(root,"NovaOryn.Configuration.props"),b.ToString());
 }
 private static void WriteTargets(string root,NovaOrynConfigurationModel c)
 {
  var b=new StringBuilder();b.AppendLine("<Project>");b.AppendLine("  <!-- Generated authoritative configured graph. File presence never implies kernel inclusion. -->");b.AppendLine("  <ItemGroup>");
  foreach(string item in BuildKernelProjects(c))b.AppendLine($"    <NovaOrynConfiguredKernelProject Include=\"{EscapeXml(item)}\" />");
  foreach(var item in BuildWorkspaceProjects(c))b.AppendLine($"    <NovaOrynConfiguredWorkspaceProject Include=\"{EscapeXml(item.Path)}\"><ExecutionDomain>{item.Domain}</ExecutionDomain><WorkArea>{EscapeXml(item.Area)}</WorkArea></NovaOrynConfiguredWorkspaceProject>");
  b.AppendLine("  </ItemGroup>");b.AppendLine("</Project>");File.WriteAllText(Path.Combine(root,"NovaOryn.Configuration.targets"),b.ToString());
 }
 private static IEnumerable<string> BuildKernelProjects(NovaOrynConfigurationModel c)
 {
  if(c.KernelModel=="Microkernel")yield break;
  foreach(string area in c.GetSuppliedAreas())
  {
   if(c.KernelModel=="Hybrid" && !string.Equals(area,"Drivers",StringComparison.OrdinalIgnoreCase) && !string.Equals(area,"Input",StringComparison.OrdinalIgnoreCase))continue;
   string dir=Path.Combine("KernelProjects",SafeName(area));yield return dir+"\\**\\*.csproj";
  }
 }
 private static List<WorkspaceProject> BuildWorkspaceProjects(NovaOrynConfigurationModel c)
 {
  var result=new List<WorkspaceProject>();
  foreach(string area in c.GetSuppliedAreas())
  {
   string domain=DomainForArea(c.KernelModel,area);if(domain=="Kernel")continue;
   string relative=Path.Combine("Userland",SafeName(area),"NovaOryn."+SafeName(area)+".Service.Generated.csproj");result.Add(new WorkspaceProject(relative,domain,area));
  }
  if(c.GetSuppliedAreas().Contains("Tests",StringComparer.OrdinalIgnoreCase))result.Add(new WorkspaceProject(Path.Combine("Tests","NovaOryn.Tests.Generated.csproj"),"Userland","Tests"));
  return result;
 }
 private static void WriteWorkspaceGraph(string root,NovaOrynConfigurationModel c)
 {
  string configDir=Path.Combine(root,"Configuration");Directory.CreateDirectory(configDir);var lines=new List<string>();
  foreach(var item in BuildWorkspaceProjects(c))
  {
   EnsureGeneratedProject(root,item);lines.Add(item.Path.Replace('\\','/'));
  }
  File.WriteAllLines(Path.Combine(configDir,"WorkspaceProjects.txt"),lines);
 }
 private static void EnsureGeneratedProject(string root,WorkspaceProject item)
 {
  string project=Path.Combine(root,item.Path);string directory=Path.GetDirectoryName(project)??root;Directory.CreateDirectory(directory);
  if(!File.Exists(project))
  {
   string assembly=Path.GetFileNameWithoutExtension(project).Replace(".Generated",string.Empty);var b=new StringBuilder();b.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");b.AppendLine("  <PropertyGroup>");b.AppendLine("    <OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable>");b.AppendLine($"    <AssemblyName>{EscapeXml(assembly)}</AssemblyName><RootNamespace>{EscapeXml(assembly)}</RootNamespace>");b.AppendLine("    <NovaOrynProject>true</NovaOrynProject><NovaOrynProjectType>UserlandService</NovaOrynProjectType><NovaOrynConfigurationGenerated>true</NovaOrynConfigurationGenerated>");b.AppendLine($"    <NovaOrynExecutionDomain>{EscapeXml(item.Domain)}</NovaOrynExecutionDomain><NovaOrynWorkArea>{EscapeXml(item.Area)}</NovaOrynWorkArea>");b.AppendLine("  </PropertyGroup>");b.AppendLine("</Project>");File.WriteAllText(project,b.ToString());
  }
  string code=Path.Combine(directory,"GeneratedService.cs");if(!File.Exists(code))File.WriteAllText(code,$"using System;\nnamespace NovaOryn.Generated.{SafeName(item.Area)};\npublic static class GeneratedService\n{{\n    public static Int32 Main(String[] args) => Run();\n    public static Int32 Run() => 0;\n}}\n");
 }
 private static string DomainForArea(string model,string area)
 {
  if(model=="Monolithic")return (area=="Shell"||area=="GUI"||area=="Tests")?"Userland":"Kernel";
  if(model=="Microkernel")return (area=="HAL"||area=="Processes"||area=="Scheduler"||area=="System Calls"||area=="Security"||area=="Diagnostics")?"Kernel":"Userland";
  return (area=="Drivers"||area=="Input"||area=="HAL"||area=="Processes"||area=="Scheduler"||area=="System Calls"||area=="Security"||area=="Diagnostics")?"Kernel":"Userland";
 }
 private static void UpdateProjectManifest(string root,NovaOrynConfigurationModel c)
 {
  string mp=Path.Combine(root,"NovaOrynProject.json");var s=new JavaScriptSerializer();Dictionary<string,object> m;try{m=s.Deserialize<Dictionary<string,object>>(File.ReadAllText(mp))??new Dictionary<string,object>();}catch{m=new Dictionary<string,object>();}
  m["ConfigurationVersion"]=3;m["TargetArchitecture"]=c.Architecture;m["KernelModel"]=c.KernelModel;m["BootProtocol"]=c.BootProtocol;m["ConfigurationFile"]="NovaOryn.Configuration.json";m["ConfigurationTargets"]="NovaOryn.Configuration.targets";m["WorkAreas"]=c.GetSuppliedAreas().ToArray();m["DevelopmentAreas"]=c.WorkAreas.ToArray();m["WorkspaceGraph"]="Configuration/WorkspaceProjects.txt";
  if(string.Equals(c.Architecture,"x64",StringComparison.OrdinalIgnoreCase)){m["ProjectFile"]="Sdk/NovaOryn.Kernel.Entry.X64/NovaOryn.Kernel.Entry.X64.csproj";m["RuntimePack"]="NovaOryn.RuntimePack.X64.Bootstrap";}else if(string.Equals(c.Architecture,"arm64",StringComparison.OrdinalIgnoreCase)){m["ProjectFile"]="Sdk/NovaOryn.Kernel.Entry.Arm64/NovaOryn.Kernel.Entry.Arm64.csproj";m["RuntimePack"]="NovaOryn.RuntimePack.Arm64";}else{m["ProjectFile"]="Sdk/NovaOryn.Kernel.Entry.RiscV64/NovaOryn.Kernel.Entry.RiscV64.csproj";m["RuntimePack"]="NovaOryn.RuntimePack.RiscV64";}
  File.WriteAllText(mp,Pretty(s.Serialize(m))+Environment.NewLine);
 }
 private static void WritePlan(string root,NovaOrynConfigurationModel c){string d=Path.Combine(root,"Configuration");Directory.CreateDirectory(d);var b=new StringBuilder();b.AppendLine("# NovaOryn authoritative configured graph").AppendLine();b.AppendLine($"Architecture: {c.Architecture}");b.AppendLine($"Kernel model: {c.KernelModel}");b.AppendLine($"Default execution domain: {DefaultDomain(c.KernelModel)}").AppendLine();b.AppendLine("Development areas deliberately missing from the supplied OS:");foreach(string x in c.WorkAreas)b.AppendLine($"- {x}");b.AppendLine().AppendLine("Supplied areas and execution domains:");foreach(string x in c.GetSuppliedAreas())b.AppendLine($"- {x}: {DomainForArea(c.KernelModel,x)}");b.AppendLine().AppendLine("NovaOryn.Configuration.json -> .props/.targets -> configured project graph. Checked work areas are the parts the user intends to implement; unchecked areas are supplied. Reconfiguration never deletes user source files.");File.WriteAllText(Path.Combine(d,"WorkAreas.md"),b.ToString());}
 private Project ResolveSelectedNovaOrynProject(){ThreadHelper.ThrowIfNotOnUIThread();try{SelectedItems selected=_dte.SelectedItems;if(selected!=null){for(short index=1;index<=selected.Count;index++){SelectedItem item=selected.Item(index);Project project=item?.Project??item?.ProjectItem?.ContainingProject;if(project!=null&&IsKernel(project))return project;}}}catch{}foreach(Project project in _dte.Solution.Projects){Project found=FindKernel(project);if(found!=null)return found;}return null;}
 private static Project FindKernel(Project p){ThreadHelper.ThrowIfNotOnUIThread();if(p==null)return null;if(IsKernel(p))return p;if(p.ProjectItems==null)return null;foreach(ProjectItem i in p.ProjectItems){if(i.SubProject==null)continue;Project f=FindKernel(i.SubProject);if(f!=null)return f;}return null;}
 private static bool IsKernel(Project p){ThreadHelper.ThrowIfNotOnUIThread();string d=NovaOrynProjectRecognizer.TryGetProjectDirectory(p);return !string.IsNullOrWhiteSpace(d)&&File.Exists(Path.Combine(d,"NovaOrynProject.json"));}
 private static string DefaultDomain(string m)=>m=="Microkernel"?"Userland":m=="Hybrid"?"Mixed":"Kernel";
 private static string SafeName(string value)=>new string((value??string.Empty).Where(Char.IsLetterOrDigit).ToArray());
 private static string NormalizeConstant(string value)=>new string((value??string.Empty).ToUpperInvariant().Select(ch=>Char.IsLetterOrDigit(ch)?ch:'_').ToArray());
 private static string EscapeXml(string v)=>System.Security.SecurityElement.Escape(v??string.Empty);
 private static string Pretty(string json){int i=0;bool q=false,e=false;var b=new StringBuilder();foreach(char c in json){if(q){b.Append(c);if(e)e=false;else if(c=='\\')e=true;else if(c=='\"')q=false;continue;}if(c=='\"'){q=true;b.Append(c);continue;}if(c=='{'||c=='['){b.Append(c).AppendLine();i++;b.Append(new string(' ',i*2));}else if(c=='}'||c==']'){b.AppendLine();i--;b.Append(new string(' ',i*2)).Append(c);}else if(c==',')b.Append(c).AppendLine().Append(new string(' ',i*2));else if(c==':')b.Append(": ");else if(!char.IsWhiteSpace(c))b.Append(c);}return b.ToString();}
 private sealed class WorkspaceProject{public WorkspaceProject(string path,string domain,string area){Path=path;Domain=domain;Area=area;}public string Path{get;}public string Domain{get;}public string Area{get;}}
}
