using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
namespace NovaOryn.VisualStudio;
internal sealed class NovaOrynConfigurationWindow:Window
{
 private readonly ComboBox _architecture=new ComboBox();private readonly ComboBox _kernelModel=new ComboBox();private readonly TextBlock _architectureStatus=new TextBlock();private readonly TextBlock _kernelModelStatus=new TextBlock();private readonly Dictionary<string,CheckBox> _workAreaBoxes=new Dictionary<string,CheckBox>(StringComparer.OrdinalIgnoreCase);private readonly TextBlock _summary=new TextBlock();private bool _loadingControls;public NovaOrynConfigurationModel Configuration{get;}
 public NovaOrynConfigurationWindow(NovaOrynConfigurationModel configuration,string projectRoot)
 {
  Configuration=configuration??NovaOrynConfigurationModel.CreateDefault();Title="NovaOryn Project Configuration";Width=820;Height=650;MinWidth=720;MinHeight=560;WindowStartupLocation=WindowStartupLocation.CenterScreen;
  var root=new DockPanel{Margin=new Thickness(14)};Content=root;var heading=new StackPanel{Margin=new Thickness(0,0,0,12)};heading.Children.Add(new TextBlock{Text="Configure this NovaOryn operating system",FontSize=20,FontWeight=FontWeights.SemiBold});heading.Children.Add(new TextBlock{Text=projectRoot,Margin=new Thickness(0,4,0,0),TextWrapping=TextWrapping.Wrap,Foreground=Brushes.Gray});DockPanel.SetDock(heading,Dock.Top);root.Children.Add(heading);
  var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right,Margin=new Thickness(0,12,0,0)};var cancel=new Button{Content="Cancel",MinWidth=90,Margin=new Thickness(0,0,8,0)};cancel.Click+=(_,__)=>{DialogResult=false;Close();};var apply=new Button{Content="Apply Configuration",MinWidth=150,IsDefault=true};apply.Click+=(_,__)=>{ReadControls();DialogResult=true;Close();};buttons.Children.Add(cancel);buttons.Children.Add(apply);DockPanel.SetDock(buttons,Dock.Bottom);root.Children.Add(buttons);
  var tabs=new TabControl();tabs.Items.Add(ArchitecturePage());tabs.Items.Add(KernelModelPage());tabs.Items.Add(WorkAreasPage());tabs.Items.Add(SummaryPage());tabs.SelectionChanged+=(_,__)=>RefreshSummary();root.Children.Add(tabs);LoadControls();RefreshStatus();RefreshSummary();
 }
 private TabItem ArchitecturePage(){var p=Page();p.Children.Add(TitleText("Which architecture do you want this OS/kernel to target?"));foreach(string x in NovaOrynConfigurationModel.Architectures)_architecture.Items.Add(x);_architecture.MinWidth=240;_architecture.HorizontalAlignment=HorizontalAlignment.Left;_architecture.Margin=new Thickness(0,10,0,10);_architecture.SelectionChanged+=(_,__)=>{if(_loadingControls)return;ReadControls();RefreshStatus();RefreshSummary();};p.Children.Add(_architecture);_architectureStatus.TextWrapping=TextWrapping.Wrap;p.Children.Add(_architectureStatus);p.Children.Add(Note("x64 is installed now. ARM64 and RISC-V 64 are valid target intent, but NovaOryn refuses to build them until their architecture packs exist rather than silently generating x64."));return new TabItem{Header="1. Architecture",Content=p};}
 private TabItem KernelModelPage(){var p=Page();p.Children.Add(TitleText("Which kernel model do you want?"));foreach(string x in NovaOrynConfigurationModel.KernelModels)_kernelModel.Items.Add(x);_kernelModel.MinWidth=240;_kernelModel.HorizontalAlignment=HorizontalAlignment.Left;_kernelModel.Margin=new Thickness(0,10,0,10);_kernelModel.SelectionChanged+=(_,__)=>{if(_loadingControls)return;ReadControls();RefreshStatus();RefreshSummary();};p.Children.Add(_kernelModel);_kernelModelStatus.TextWrapping=TextWrapping.Wrap;p.Children.Add(_kernelModelStatus);p.Children.Add(Note("This selection is authoritative: Apply regenerates the physical/project topology. Monolithic places supplied system components under Kernel where appropriate; Microkernel keeps only kernel mechanisms under Kernel and places supplied services/drivers in Userland; Hybrid deliberately splits the two."));return new TabItem{Header="2. Kernel Model",Content=p};}
 private TabItem WorkAreasPage(){var p=Page();p.Children.Add(TitleText("What do you want to work on?"));p.Children.Add(Note("Check ONLY the area or areas you want to implement yourself. Checked areas are deliberately missing from the supplied OS. Every unchecked area is supplied by NovaOryn and placed according to the selected kernel model. Reconfiguration never deletes your source files."));var g=new UniformGrid{Columns=2,Margin=new Thickness(0,12,0,0)};foreach(string area in NovaOrynConfigurationModel.AvailableWorkAreas){var box=new CheckBox{Content=area,Margin=new Thickness(4,6,18,6)};box.Checked+=(_,__)=>{if(!_loadingControls)RefreshSummary();};box.Unchecked+=(_,__)=>{if(!_loadingControls)RefreshSummary();};_workAreaBoxes[area]=box;g.Children.Add(box);}p.Children.Add(g);return new TabItem{Header="3. Work Areas",Content=new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}};}
 private TabItem SummaryPage(){var p=Page();p.Children.Add(TitleText("Configuration that will be applied"));_summary.TextWrapping=TextWrapping.Wrap;_summary.FontFamily=new FontFamily("Consolas");_summary.Margin=new Thickness(0,12,0,0);p.Children.Add(_summary);p.Children.Add(Note("Apply writes NovaOryn.Configuration.json, .props and .targets, regenerates Configuration/WorkspaceProjects.txt, updates NovaOrynProject.json, and synchronizes Solution Explorer without deleting user code."));return new TabItem{Header="4. Summary",Content=p};}
 private static StackPanel Page()=>new StackPanel{Margin=new Thickness(18)};private static TextBlock TitleText(string t)=>new TextBlock{Text=t,FontSize=16,FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap};private static TextBlock Note(string t)=>new TextBlock{Text=t,Margin=new Thickness(0,14,0,0),TextWrapping=TextWrapping.Wrap,Foreground=Brushes.Gray};
 private void LoadControls(){_loadingControls=true;try{_architecture.SelectedItem=NovaOrynConfigurationModel.Architectures.FirstOrDefault(x=>string.Equals(x,Configuration.Architecture,StringComparison.OrdinalIgnoreCase))??"x64";_kernelModel.SelectedItem=NovaOrynConfigurationModel.KernelModels.FirstOrDefault(x=>string.Equals(x,Configuration.KernelModel,StringComparison.OrdinalIgnoreCase))??"Monolithic";foreach(var pair in _workAreaBoxes)pair.Value.IsChecked=Configuration.WorkAreas.Contains(pair.Key,StringComparer.OrdinalIgnoreCase);}finally{_loadingControls=false;}}
 private void ReadControls(){Configuration.Architecture=_architecture.SelectedItem as string??"x64";Configuration.KernelModel=_kernelModel.SelectedItem as string??"Monolithic";Configuration.BootProtocol="Uefi";Configuration.WorkAreas=_workAreaBoxes.Where(x=>x.Value.IsChecked==true).Select(x=>x.Key).ToList();}
 private void RefreshStatus(){ReadControls();_architectureStatus.Text=Configuration.GetArchitectureStatus();_kernelModelStatus.Text=Configuration.GetKernelModelDescription();}
 private void RefreshSummary(){if(_loadingControls)return;ReadControls();string d=Configuration.KernelModel=="Microkernel"?"Userland services + minimal Kernel":Configuration.KernelModel=="Hybrid"?"Mixed":"Kernel-heavy";var supplied=Configuration.GetSuppliedAreas();_summary.Text=$"Architecture : {Configuration.Architecture}\nBoot protocol: {Configuration.BootProtocol}\nKernel model : {Configuration.KernelModel}\nTopology     : {d}\n\nYou will implement (missing):\n  "+(Configuration.WorkAreas.Count==0?"(nothing - complete supplied OS)":string.Join("\n  ",Configuration.WorkAreas.OrderBy(x=>x)))+"\n\nNovaOryn supplies:\n  "+string.Join("\n  ",supplied.OrderBy(x=>x));}
}
