using System;
using NovaOryn.Kernel.Heap;
namespace NovaOryn.Kernel.Networking;

public static unsafe class KernelSockets
{
    private struct SocketRecord { public Byte Used,Type,State,TcpState;public UInt32 LocalAddress,RemoteAddress;public UInt16 LocalPort,RemotePort;public UInt32 RxLength;public fixed Byte Rx[2048]; }
    private static SocketRecord* _sockets;private static UInt32 _capacity,_count;private static KernelHeapAllocation _allocation;private static KernelNetworkOptions _options;private static Boolean _initialized;
    internal static Boolean Initialize(KernelNetworkOptions options){if(_initialized)return true;if(!KernelHeap.TryAllocate((UInt64)options.InitialSockets*(UInt64)sizeof(SocketRecord),64,true,out _allocation))return false;_sockets=(SocketRecord*)(nuint)_allocation.Address;_capacity=options.InitialSockets;_options=options;_initialized=true;return true;}
    internal static UInt32 GetCount()=>_count;internal static UInt32 GetCapacity()=>_capacity;
    public static Boolean Create(KernelSocketType type,out KernelSocketHandle handle){handle=default;if(!_initialized||(type!=KernelSocketType.Datagram&&type!=KernelSocketType.Stream))return false;Int32 slot=Free();if(slot<0){if(!Grow())return false;slot=Free();if(slot<0)return false;}SocketRecord* r=_sockets+slot;r->Used=1;r->Type=(Byte)type;r->State=(Byte)KernelSocketState.Created;r->TcpState=(Byte)KernelTcpState.Closed;_count++;handle=new((UInt32)slot+1U);return true;}
    public static Boolean Bind(KernelSocketHandle handle,KernelIpv4Endpoint local){if(!Try(handle,out SocketRecord* r)||local.Port==0)return false;for(Int32 i=0;i<(Int32)_capacity;i++){SocketRecord* p=_sockets+i;if(p!=r&&p->Used!=0&&p->LocalPort==local.Port&&p->LocalAddress==local.Address.Value)return false;}r->LocalAddress=local.Address.Value;r->LocalPort=local.Port;r->State=(Byte)KernelSocketState.Bound;return true;}
    public static Boolean Connect(KernelSocketHandle handle,KernelIpv4Endpoint remote){if(!Try(handle,out SocketRecord* r)||remote.Address.Value==0||remote.Port==0)return false;r->RemoteAddress=remote.Address.Value;r->RemotePort=remote.Port;if(r->Type==(Byte)KernelSocketType.Datagram){r->State=(Byte)KernelSocketState.Connected;return true;}r->State=(Byte)KernelSocketState.Connecting;r->TcpState=(Byte)KernelTcpState.SynSent;return true;}
    public static Boolean Listen(KernelSocketHandle handle){if(!Try(handle,out SocketRecord* r)||r->Type!=(Byte)KernelSocketType.Stream||r->LocalPort==0)return false;r->State=(Byte)KernelSocketState.Listening;r->TcpState=(Byte)KernelTcpState.Listen;return true;}
    public static Boolean Close(KernelSocketHandle handle){if(!Try(handle,out SocketRecord* r))return false;Clear((Byte*)r,sizeof(SocketRecord));_count--;return true;}
    public static Boolean TryGet(KernelSocketHandle handle,out KernelSocketInfo info){info=default;if(!Try(handle,out SocketRecord* r))return false;info=new(handle,(KernelSocketType)r->Type,(KernelSocketState)r->State,new(new KernelIpv4Address(r->LocalAddress),r->LocalPort),new(new KernelIpv4Address(r->RemoteAddress),r->RemotePort),(KernelTcpState)r->TcpState);return true;}
    public static Boolean SendTo(KernelSocketHandle handle,KernelIpv4Endpoint remote,Byte* data,UInt32 length){if(!Try(handle,out SocketRecord* r)||r->Type!=(Byte)KernelSocketType.Datagram||data==null||length==0)return false;KernelIpv4Endpoint destination=remote.Address.Value!=0?remote:new KernelIpv4Endpoint(new KernelIpv4Address(r->RemoteAddress),r->RemotePort);if(destination.Address.Value==0||destination.Port==0)return false;return KernelNetworkStack.SendUdp(new KernelIpv4Endpoint(new KernelIpv4Address(r->LocalAddress),r->LocalPort),destination,data,length);}
    public static Boolean Receive(KernelSocketHandle handle,Byte* buffer,UInt32 capacity,out UInt32 received){received=0;if(!Try(handle,out SocketRecord* r)||buffer==null||capacity==0||r->RxLength==0)return false;UInt32 count=r->RxLength<capacity?r->RxLength:capacity;for(Int32 i=0;i<(Int32)count;i++)buffer[i]=r->Rx[i];if(count<r->RxLength)for(Int32 i=(Int32)count;i<(Int32)r->RxLength;i++)r->Rx[i-(Int32)count]=r->Rx[i];r->RxLength-=count;received=count;return true;}
    internal static Boolean DeliverUdp(KernelIpv4Endpoint source,KernelIpv4Endpoint destination,Byte* data,UInt32 length){if(data==null)return false;for(Int32 i=0;i<(Int32)_capacity;i++){SocketRecord* r=_sockets+i;if(r->Used==0||r->Type!=(Byte)KernelSocketType.Datagram||r->LocalPort!=destination.Port)continue;if(r->LocalAddress!=0&&r->LocalAddress!=destination.Address.Value)continue;UInt32 room=2048U-r->RxLength;UInt32 count=length<room?length:room;for(Int32 j=0;j<(Int32)count;j++)r->Rx[(Int32)r->RxLength+j]=data[j];r->RxLength+=count;r->RemoteAddress=source.Address.Value;r->RemotePort=source.Port;return count==length;}return false;}
    internal static Boolean ObserveTcp(KernelIpv4Endpoint source,KernelIpv4Endpoint destination,Byte flags){for(Int32 i=0;i<(Int32)_capacity;i++){SocketRecord* r=_sockets+i;if(r->Used==0||r->Type!=(Byte)KernelSocketType.Stream||r->LocalPort!=destination.Port)continue;if(r->TcpState==(Byte)KernelTcpState.Listen&&(flags&0x02)!=0){r->RemoteAddress=source.Address.Value;r->RemotePort=source.Port;r->TcpState=(Byte)KernelTcpState.SynReceived;r->State=(Byte)KernelSocketState.Connecting;return true;}if(r->TcpState==(Byte)KernelTcpState.SynSent&&(flags&0x12)==0x12){r->TcpState=(Byte)KernelTcpState.Established;r->State=(Byte)KernelSocketState.Connected;return true;}if(r->TcpState==(Byte)KernelTcpState.SynReceived&&(flags&0x10)!=0){r->TcpState=(Byte)KernelTcpState.Established;r->State=(Byte)KernelSocketState.Connected;return true;}if((flags&0x01)!=0){r->TcpState=(Byte)KernelTcpState.CloseWait;return true;}}return false;}
    private static Boolean Try(KernelSocketHandle h,out SocketRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_capacity||(_sockets+i)->Used==0)return false;r=_sockets+i;return true;}private static Int32 Free(){for(Int32 i=0;i<(Int32)_capacity;i++)if((_sockets+i)->Used==0)return i;return -1;}
    private static Boolean Grow(){if(_options.RegistryMode!=KernelNetworkRegistryMode.Dynamic)return false;UInt32 next=KernelNetworkMath.NextCapacity(_capacity,_options.MaximumSockets);if(next<=_capacity)return false;if(!KernelHeap.TryAllocate((UInt64)next*(UInt64)sizeof(SocketRecord),64,true,out KernelHeapAllocation fresh))return false;SocketRecord* p=(SocketRecord*)(nuint)fresh.Address;for(UInt64 i=0;i<(UInt64)_capacity*(UInt64)sizeof(SocketRecord);i++)((Byte*)p)[i]=((Byte*)_sockets)[i];KernelHeapAllocation old=_allocation;_allocation=fresh;_sockets=p;_capacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean Clear(Byte* p,Int32 bytes){for(Int32 i=0;i<bytes;i++)p[i]=0;return true;}
}
