using System;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Heap;

namespace NovaOryn.Kernel.Networking;

public static unsafe class KernelNetworking
{
    private struct InterfaceRecord { public Byte Used;public Byte State;public Byte Contextual;public UInt32 Device;public Byte A,B,C,D,E,F;public UInt32 Address,Mask,Gateway,Mtu;public delegate*<Byte*,UInt32,Boolean> Tx;public delegate*<Boolean,Boolean> RxEnable; }
    private struct RouteRecord { public Byte Used;public UInt32 Network,Mask,Gateway,Interface,Metric; }
    private struct NeighborRecord { public Byte Used;public UInt32 Address,Interface;public Byte A,B,C,D,E,F; }
    private static InterfaceRecord* _interfaces;private static RouteRecord* _routes;private static NeighborRecord* _neighbors;
    private static UInt32 _interfaceCapacity,_routeCapacity,_neighborCapacity,_interfacesUsed,_routesUsed,_neighborsUsed;private static KernelHeapAllocation _interfaceAllocation,_routeAllocation,_neighborAllocation;private static KernelNetworkOptions _options;private static Boolean _initialized;

    public static Boolean Initialize()=>Initialize(KernelNetworkOptions.DynamicDefault);
    public static Boolean Initialize(KernelNetworkOptions options){if(_initialized||!KernelHeap.IsInitialized()||!KernelNetworkMath.IsValidOptions(options))return false;if(!Allocate(options.InitialInterfaces,sizeof(InterfaceRecord),out _interfaceAllocation,out Byte* ip))return false;if(!Allocate(options.InitialRoutes,sizeof(RouteRecord),out _routeAllocation,out Byte* rp)){KernelHeap.TryRelease(_interfaceAllocation);return false;}if(!Allocate(options.InitialNeighbors,sizeof(NeighborRecord),out _neighborAllocation,out Byte* np)){KernelHeap.TryRelease(_routeAllocation);KernelHeap.TryRelease(_interfaceAllocation);return false;}_interfaces=(InterfaceRecord*)ip;_routes=(RouteRecord*)rp;_neighbors=(NeighborRecord*)np;_interfaceCapacity=options.InitialInterfaces;_routeCapacity=options.InitialRoutes;_neighborCapacity=options.InitialNeighbors;_options=options;if(!KernelSockets.Initialize(options)||!KernelNetworkQueue.Initialize(options)){KernelHeap.TryRelease(_neighborAllocation);KernelHeap.TryRelease(_routeAllocation);KernelHeap.TryRelease(_interfaceAllocation);return false;}_initialized=true;return true;}
    public static Boolean IsInitialized()=>_initialized;
    public static KernelNetworkCapabilities GetCapabilities()=>new(_initialized,_options.RegistryMode,_interfacesUsed,_routesUsed,_neighborsUsed,KernelSockets.GetCount(),_interfaceCapacity,_routeCapacity,_neighborCapacity,KernelSockets.GetCapacity());

    public static Boolean RegisterInterface(KernelDeviceHandle device,KernelMacAddress mac,UInt32 mtu,KernelNetworkInterfaceCallbacks callbacks,out KernelNetworkInterfaceHandle handle){handle=default;if(!_initialized||device.Value==0||mac.IsZero||mtu<576||callbacks.TransmitFrame==null)return false;Int32 slot=FreeInterface();if(slot<0){if(!GrowInterfaces())return false;slot=FreeInterface();if(slot<0)return false;}InterfaceRecord* r=_interfaces+slot;r->Used=1;r->Device=device.Value;r->A=mac.A;r->B=mac.B;r->C=mac.C;r->D=mac.D;r->E=mac.E;r->F=mac.F;r->Mtu=mtu;r->Tx=callbacks.TransmitFrame;r->RxEnable=callbacks.SetReceiveEnabled;_interfacesUsed++;handle=new KernelNetworkInterfaceHandle((UInt32)slot+1U);return true;}
    /// <summary>Registers an interface using callbacks that receive the owning generic device handle.</summary>
    public static Boolean RegisterInterface(KernelDeviceHandle device,KernelMacAddress mac,UInt32 mtu,KernelContextualNetworkInterfaceCallbacks callbacks,out KernelNetworkInterfaceHandle handle){handle=default;if(!_initialized||device.Value==0||mac.IsZero||mtu<576||callbacks.TransmitFrame==null)return false;Int32 slot=FreeInterface();if(slot<0){if(!GrowInterfaces())return false;slot=FreeInterface();if(slot<0)return false;}InterfaceRecord* r=_interfaces+slot;r->Used=1;r->Contextual=1;r->Device=device.Value;r->A=mac.A;r->B=mac.B;r->C=mac.C;r->D=mac.D;r->E=mac.E;r->F=mac.F;r->Mtu=mtu;r->Tx=(delegate*<Byte*,UInt32,Boolean>)(void*)callbacks.TransmitFrame;r->RxEnable=(delegate*<Boolean,Boolean>)(void*)callbacks.SetReceiveEnabled;_interfacesUsed++;handle=new KernelNetworkInterfaceHandle((UInt32)slot+1U);return true;}
    public static Boolean ConfigureIpv4(KernelNetworkInterfaceHandle handle,KernelIpv4Address address,KernelIpv4Address mask,KernelIpv4Address gateway){if(!TryInterface(handle,out InterfaceRecord* r)||address.Value==0||mask.Value==0)return false;r->Address=address.Value;r->Mask=mask.Value;r->Gateway=gateway.Value;return true;}
    public static Boolean SetInterfaceState(KernelNetworkInterfaceHandle handle,KernelNetworkInterfaceState state){if(!TryInterface(handle,out InterfaceRecord* r))return false;if(r->RxEnable!=null){Boolean enabled=state==KernelNetworkInterfaceState.Up;if(r->Contextual!=0){delegate*<KernelDeviceHandle,Boolean,Boolean> rx=(delegate*<KernelDeviceHandle,Boolean,Boolean>)(void*)r->RxEnable;if(!rx(new KernelDeviceHandle(r->Device),enabled))return false;}else if(!r->RxEnable(enabled))return false;}r->State=(Byte)state;return true;}
    public static Boolean TryGetInterface(KernelNetworkInterfaceHandle handle,out KernelNetworkInterfaceInfo info){info=default;if(!TryInterface(handle,out InterfaceRecord* r))return false;info=new(handle,new KernelDeviceHandle(r->Device),new KernelMacAddress(r->A,r->B,r->C,r->D,r->E,r->F),new KernelIpv4Address(r->Address),new KernelIpv4Address(r->Mask),new KernelIpv4Address(r->Gateway),r->Mtu,(KernelNetworkInterfaceState)r->State);return true;}
    public static Boolean AddRoute(KernelNetworkRoute route){if(!_initialized||route.Interface.Value==0||!TryInterface(route.Interface,out _))return false;Int32 slot=FreeRoute();if(slot<0){if(!GrowRoutes())return false;slot=FreeRoute();if(slot<0)return false;}RouteRecord* r=_routes+slot;r->Used=1;r->Network=route.Network.Value;r->Mask=route.Mask.Value;r->Gateway=route.Gateway.Value;r->Interface=route.Interface.Value;r->Metric=route.Metric;_routesUsed++;return true;}
    public static Boolean TryResolveRoute(KernelIpv4Address destination,out KernelNetworkRoute route){route=default;if(!_initialized)return false;Boolean found=false;UInt32 bestPrefix=0,bestMetric=UInt32.MaxValue;for(Int32 i=0;i<(Int32)_routeCapacity;i++){RouteRecord* r=_routes+i;if(r->Used==0)continue;KernelNetworkRoute candidate=new(new KernelIpv4Address(r->Network),new KernelIpv4Address(r->Mask),new KernelIpv4Address(r->Gateway),new KernelNetworkInterfaceHandle(r->Interface),r->Metric);if(!KernelNetworkMath.RouteMatches(candidate,destination))continue;UInt32 prefix=KernelNetworkMath.PrefixLength(candidate.Mask);if(!found||prefix>bestPrefix||(prefix==bestPrefix&&candidate.Metric<bestMetric)){found=true;bestPrefix=prefix;bestMetric=candidate.Metric;route=candidate;}}return found;}
    public static Boolean UpdateNeighbor(KernelNetworkInterfaceHandle networkInterface,KernelIpv4Address address,KernelMacAddress mac){if(!_initialized||networkInterface.Value==0||address.Value==0||mac.IsZero)return false;for(Int32 i=0;i<(Int32)_neighborCapacity;i++){NeighborRecord* n=_neighbors+i;if(n->Used!=0&&n->Interface==networkInterface.Value&&n->Address==address.Value){SetMac(n,mac);return true;}}Int32 slot=FreeNeighbor();if(slot<0){if(!GrowNeighbors())return false;slot=FreeNeighbor();if(slot<0)return false;}NeighborRecord* r=_neighbors+slot;r->Used=1;r->Interface=networkInterface.Value;r->Address=address.Value;SetMac(r,mac);_neighborsUsed++;return true;}
    public static Boolean TryResolveNeighbor(KernelNetworkInterfaceHandle networkInterface,KernelIpv4Address address,out KernelMacAddress mac){mac=default;if(!_initialized)return false;for(Int32 i=0;i<(Int32)_neighborCapacity;i++){NeighborRecord* n=_neighbors+i;if(n->Used!=0&&n->Interface==networkInterface.Value&&n->Address==address.Value){mac=new(n->A,n->B,n->C,n->D,n->E,n->F);return true;}}return false;}
    public static Boolean ReceiveFrame(KernelNetworkInterfaceHandle networkInterface,Byte* frame,UInt32 length)=>KernelNetworkStack.ReceiveEthernet(networkInterface,frame,length);
    public static Boolean QueueReceivedFrame(KernelNetworkInterfaceHandle networkInterface,Byte* frame,UInt32 length,out KernelNetworkPacketHandle handle)=>KernelNetworkQueue.Enqueue(networkInterface,frame,length,out handle);
    internal static Boolean Transmit(KernelNetworkInterfaceHandle h,Byte* frame,UInt32 length){if(!TryInterface(h,out InterfaceRecord* r)||r->State!=(Byte)KernelNetworkInterfaceState.Up||frame==null||length==0)return false;if(r->Contextual!=0){delegate*<KernelDeviceHandle,Byte*,UInt32,Boolean> tx=(delegate*<KernelDeviceHandle,Byte*,UInt32,Boolean>)(void*)r->Tx;return tx(new KernelDeviceHandle(r->Device),frame,length);}return r->Tx(frame,length);}

    private static Boolean Allocate(UInt32 capacity,Int32 size,out KernelHeapAllocation allocation,out Byte* pointer){allocation=default;pointer=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)size,64,true,out allocation))return false;pointer=(Byte*)(nuint)allocation.Address;return true;}
    private static Boolean TryInterface(KernelNetworkInterfaceHandle h,out InterfaceRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_interfaceCapacity||(_interfaces+i)->Used==0)return false;r=_interfaces+i;return true;}
    private static Int32 FreeInterface(){for(Int32 i=0;i<(Int32)_interfaceCapacity;i++)if((_interfaces+i)->Used==0)return i;return -1;}private static Int32 FreeRoute(){for(Int32 i=0;i<(Int32)_routeCapacity;i++)if((_routes+i)->Used==0)return i;return -1;}private static Int32 FreeNeighbor(){for(Int32 i=0;i<(Int32)_neighborCapacity;i++)if((_neighbors+i)->Used==0)return i;return -1;}
    private static Boolean GrowInterfaces(){if(_options.RegistryMode!=KernelNetworkRegistryMode.Dynamic)return false;UInt32 next=KernelNetworkMath.NextCapacity(_interfaceCapacity,_options.MaximumInterfaces);if(next<=_interfaceCapacity||!Allocate(next,sizeof(InterfaceRecord),out KernelHeapAllocation fresh,out Byte* pointer))return false;Copy((Byte*)_interfaces,pointer,(UInt64)_interfaceCapacity*(UInt64)sizeof(InterfaceRecord));KernelHeapAllocation old=_interfaceAllocation;_interfaceAllocation=fresh;_interfaces=(InterfaceRecord*)pointer;_interfaceCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean GrowRoutes(){if(_options.RegistryMode!=KernelNetworkRegistryMode.Dynamic)return false;UInt32 next=KernelNetworkMath.NextCapacity(_routeCapacity,_options.MaximumRoutes);if(next<=_routeCapacity||!Allocate(next,sizeof(RouteRecord),out KernelHeapAllocation fresh,out Byte* pointer))return false;Copy((Byte*)_routes,pointer,(UInt64)_routeCapacity*(UInt64)sizeof(RouteRecord));KernelHeapAllocation old=_routeAllocation;_routeAllocation=fresh;_routes=(RouteRecord*)pointer;_routeCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean GrowNeighbors(){if(_options.RegistryMode!=KernelNetworkRegistryMode.Dynamic)return false;UInt32 next=KernelNetworkMath.NextCapacity(_neighborCapacity,_options.MaximumNeighbors);if(next<=_neighborCapacity||!Allocate(next,sizeof(NeighborRecord),out KernelHeapAllocation fresh,out Byte* pointer))return false;Copy((Byte*)_neighbors,pointer,(UInt64)_neighborCapacity*(UInt64)sizeof(NeighborRecord));KernelHeapAllocation old=_neighborAllocation;_neighborAllocation=fresh;_neighbors=(NeighborRecord*)pointer;_neighborCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean Copy(Byte* source,Byte* destination,UInt64 bytes){for(UInt64 i=0;i<bytes;i++)destination[i]=source[i];return true;}private static Boolean SetMac(NeighborRecord* r,KernelMacAddress m){r->A=m.A;r->B=m.B;r->C=m.C;r->D=m.D;r->E=m.E;r->F=m.F;return true;}
}
