using System;
namespace NovaOryn.Kernel.Networking;

public static unsafe class KernelNetworkStack
{
    private const UInt16 EtherTypeIpv4=0x0800;private const UInt16 EtherTypeArp=0x0806;private const UInt16 EtherTypeIpv6=0x86DD;
    public static Boolean ReceiveEthernet(KernelNetworkInterfaceHandle networkInterface,Byte* frame,UInt32 length){if(frame==null||length<14||!KernelNetworking.TryGetInterface(networkInterface,out KernelNetworkInterfaceInfo info))return false;UInt16 type=KernelNetworkMath.ReadUInt16Network(frame+12);if(type==EtherTypeArp)return ReceiveArp(networkInterface,info,frame+14,length-14);if(type==EtherTypeIpv4)return ReceiveIpv4(networkInterface,info,frame+14,length-14);if(type==EtherTypeIpv6)return ReceiveIpv6(networkInterface,frame+14,length-14);return false;}
    public static Boolean SendUdp(KernelIpv4Endpoint source,KernelIpv4Endpoint destination,Byte* payload,UInt32 length){if(payload==null||length==0||length>65507)return false;if(!KernelNetworking.TryResolveRoute(destination.Address,out KernelNetworkRoute route))return false;if(!KernelNetworking.TryGetInterface(route.Interface,out KernelNetworkInterfaceInfo info)||info.State!=KernelNetworkInterfaceState.Up)return false;KernelIpv4Address nextHop=route.Gateway.Value!=0?route.Gateway:destination.Address;if(!KernelNetworking.TryResolveNeighbor(route.Interface,nextHop,out KernelMacAddress target))return false;UInt32 total=14U+20U+8U+length;if(total>info.Mtu+14U||total>65535U)return false;Byte* frame=stackalloc Byte[(Int32)total];WriteMac(frame,target);WriteMac(frame+6,info.MacAddress);KernelNetworkMath.WriteUInt16Network(frame+12,2,EtherTypeIpv4);Byte* ip=frame+14;for(Int32 i=0;i<20;i++)ip[i]=0;ip[0]=0x45;KernelNetworkMath.WriteUInt16Network(ip+2,2,(UInt16)(20U+8U+length));ip[8]=64;ip[9]=(Byte)KernelNetworkProtocol.Udp;KernelNetworkMath.WriteUInt32Network(ip+12,4,source.Address.Value!=0?source.Address.Value:info.Address.Value);KernelNetworkMath.WriteUInt32Network(ip+16,4,destination.Address.Value);KernelNetworkMath.WriteUInt16Network(ip+10,2,KernelNetworkMath.InternetChecksum(ip,20));Byte* udp=ip+20;KernelNetworkMath.WriteUInt16Network(udp,2,source.Port);KernelNetworkMath.WriteUInt16Network(udp+2,2,destination.Port);KernelNetworkMath.WriteUInt16Network(udp+4,2,(UInt16)(8U+length));udp[6]=0;udp[7]=0;for(UInt32 i=0;i<length;i++)udp[8+i]=payload[i];return KernelNetworking.Transmit(route.Interface,frame,total);}
    private static Boolean ReceiveIpv6(KernelNetworkInterfaceHandle networkInterface,Byte* packet,UInt32 length){if(packet==null||length<40||(packet[0]>>4)!=6)return false;UInt16 payloadLength=KernelNetworkMath.ReadUInt16Network(packet+4);if((UInt32)payloadLength+40U>length)return false;KernelIpv6Address source=KernelNetworkMath.ReadIpv6Address(packet+8);KernelIpv6Address destination=KernelNetworkMath.ReadIpv6Address(packet+24);if(source.IsUnspecified||destination.IsUnspecified)return false;Byte nextHeader=packet[6];if(nextHeader==58)return ReceiveNdp(networkInterface,packet,length);return true;}

    public static Boolean ReceiveNdp(KernelNetworkInterfaceHandle networkInterface,Byte* ipv6Packet,UInt32 length){if(ipv6Packet==null||length<48||(ipv6Packet[0]>>4)!=6||ipv6Packet[6]!=58)return false;Byte* icmp=ipv6Packet+40;UInt32 icmpLength=length-40;if(icmpLength<8)return false;Byte type=icmp[0];if(type!=135&&type!=136)return true;if(icmpLength<24)return false;KernelIpv6Address target=KernelNetworkMath.ReadIpv6Address(icmp+8);if(target.IsUnspecified)return false;UInt32 at=24;while(at+2<=icmpLength){Byte optionType=icmp[at];Byte units=icmp[at+1];UInt32 optionLength=(UInt32)units*8U;if(units==0||at+optionLength>icmpLength)return false;if((optionType==1||optionType==2)&&optionLength>=8){KernelMacAddress mac=new(icmp[at+2],icmp[at+3],icmp[at+4],icmp[at+5],icmp[at+6],icmp[at+7]);return KernelNetworking.UpdateIpv6Neighbor(networkInterface,target,mac);}at+=optionLength;}return true;}
    public static Boolean SendIcmpEchoIpv4(KernelNetworkInterfaceHandle networkInterface,KernelIpv4Address destination,UInt16 identifier,UInt16 sequence,Byte* payload,UInt32 length){if(payload==null&&length!=0)return false;if(!KernelNetworking.TryGetInterface(networkInterface,out KernelNetworkInterfaceInfo info)||info.State!=KernelNetworkInterfaceState.Up)return false;if(!KernelNetworking.TryResolveNeighbor(networkInterface,destination,out KernelMacAddress target))return false;UInt32 icmpLength=8U+length,total=14U+20U+icmpLength;if(total>info.Mtu+14U||total>65535U)return false;Byte* frame=stackalloc Byte[(Int32)total];WriteMac(frame,target);WriteMac(frame+6,info.MacAddress);KernelNetworkMath.WriteUInt16Network(frame+12,2,EtherTypeIpv4);Byte* ip=frame+14;for(Int32 i=0;i<20;i++)ip[i]=0;ip[0]=0x45;KernelNetworkMath.WriteUInt16Network(ip+2,2,(UInt16)(20U+icmpLength));ip[8]=64;ip[9]=(Byte)KernelNetworkProtocol.Icmp;KernelNetworkMath.WriteUInt32Network(ip+12,4,info.Address.Value);KernelNetworkMath.WriteUInt32Network(ip+16,4,destination.Value);KernelNetworkMath.WriteUInt16Network(ip+10,2,KernelNetworkMath.InternetChecksum(ip,20));Byte* icmp=ip+20;for(UInt32 i=0;i<icmpLength;i++)icmp[i]=0;icmp[0]=8;KernelNetworkMath.WriteUInt16Network(icmp+4,2,identifier);KernelNetworkMath.WriteUInt16Network(icmp+6,2,sequence);for(UInt32 i=0;i<length;i++)icmp[8+i]=payload[i];KernelNetworkMath.WriteUInt16Network(icmp+2,2,KernelNetworkMath.InternetChecksum(icmp,icmpLength));return KernelNetworking.Transmit(networkInterface,frame,total);}
    private static Boolean ReceiveArp(KernelNetworkInterfaceHandle h,KernelNetworkInterfaceInfo info,Byte* p,UInt32 length){if(length<28||KernelNetworkMath.ReadUInt16Network(p)!=1||KernelNetworkMath.ReadUInt16Network(p+2)!=0x0800||p[4]!=6||p[5]!=4)return false;KernelIpv4Address sender=new(KernelNetworkMath.ReadUInt32Network(p+14));KernelMacAddress mac=new(p[8],p[9],p[10],p[11],p[12],p[13]);KernelNetworking.UpdateNeighbor(h,sender,mac);UInt16 op=KernelNetworkMath.ReadUInt16Network(p+6);KernelIpv4Address target=new(KernelNetworkMath.ReadUInt32Network(p+24));if(op!=1||target.Value!=info.Address.Value)return true;Byte* frame=stackalloc Byte[42];WriteMac(frame,mac);WriteMac(frame+6,info.MacAddress);KernelNetworkMath.WriteUInt16Network(frame+12,2,EtherTypeArp);Byte* a=frame+14;KernelNetworkMath.WriteUInt16Network(a,2,1);KernelNetworkMath.WriteUInt16Network(a+2,2,0x0800);a[4]=6;a[5]=4;KernelNetworkMath.WriteUInt16Network(a+6,2,2);WriteMac(a+8,info.MacAddress);KernelNetworkMath.WriteUInt32Network(a+14,4,info.Address.Value);WriteMac(a+18,mac);KernelNetworkMath.WriteUInt32Network(a+24,4,sender.Value);return KernelNetworking.Transmit(h,frame,42);}
    private static Boolean ReceiveIpv4(KernelNetworkInterfaceHandle h,KernelNetworkInterfaceInfo info,Byte* ip,UInt32 length){if(length<20||(ip[0]>>4)!=4)return false;UInt32 header=(UInt32)(ip[0]&0x0F)*4U;if(header<20||header>length)return false;UInt16 total=KernelNetworkMath.ReadUInt16Network(ip+2);if(total<header||total>length)return false;if(KernelNetworkMath.InternetChecksum(ip,header)!=0)return false;KernelIpv4Address source=new(KernelNetworkMath.ReadUInt32Network(ip+12));KernelIpv4Address destination=new(KernelNetworkMath.ReadUInt32Network(ip+16));if(destination.Value!=info.Address.Value&&destination.Value!=0xFFFFFFFFU)return false;Byte protocol=ip[9];Byte* payload=ip+header;UInt32 payloadLength=(UInt32)total-header;if(protocol==(Byte)KernelNetworkProtocol.Icmp)return ReceiveIcmp(h,info,source,destination,payload,payloadLength);if(protocol==(Byte)KernelNetworkProtocol.Udp)return ReceiveUdp(source,destination,payload,payloadLength);if(protocol==(Byte)KernelNetworkProtocol.Tcp)return ReceiveTcp(source,destination,payload,payloadLength);return false;}
    private static Boolean ReceiveIcmp(KernelNetworkInterfaceHandle h,KernelNetworkInterfaceInfo info,KernelIpv4Address source,KernelIpv4Address destination,Byte* p,UInt32 length){if(length<8||KernelNetworkMath.InternetChecksum(p,length)!=0)return false;if(p[0]!=8||p[1]!=0)return true;if(!KernelNetworking.TryResolveNeighbor(h,source,out KernelMacAddress mac))return false;UInt32 total=14U+20U+length;if(total>info.Mtu+14U)return false;Byte* frame=stackalloc Byte[(Int32)total];WriteMac(frame,mac);WriteMac(frame+6,info.MacAddress);KernelNetworkMath.WriteUInt16Network(frame+12,2,EtherTypeIpv4);Byte* ip=frame+14;for(Int32 i=0;i<20;i++)ip[i]=0;ip[0]=0x45;KernelNetworkMath.WriteUInt16Network(ip+2,2,(UInt16)(20U+length));ip[8]=64;ip[9]=(Byte)KernelNetworkProtocol.Icmp;KernelNetworkMath.WriteUInt32Network(ip+12,4,destination.Value);KernelNetworkMath.WriteUInt32Network(ip+16,4,source.Value);KernelNetworkMath.WriteUInt16Network(ip+10,2,KernelNetworkMath.InternetChecksum(ip,20));Byte* icmp=ip+20;for(UInt32 i=0;i<length;i++)icmp[i]=p[i];icmp[0]=0;icmp[2]=0;icmp[3]=0;KernelNetworkMath.WriteUInt16Network(icmp+2,2,KernelNetworkMath.InternetChecksum(icmp,length));return KernelNetworking.Transmit(h,frame,total);}
    private static Boolean ReceiveUdp(KernelIpv4Address source,KernelIpv4Address destination,Byte* p,UInt32 length){if(length<8)return false;UInt16 sourcePort=KernelNetworkMath.ReadUInt16Network(p);UInt16 destinationPort=KernelNetworkMath.ReadUInt16Network(p+2);UInt16 udpLength=KernelNetworkMath.ReadUInt16Network(p+4);if(udpLength<8||udpLength>length)return false;return KernelSockets.DeliverUdp(new(source,sourcePort),new(destination,destinationPort),p+8,(UInt32)udpLength-8U);}
    private static Boolean ReceiveTcp(KernelIpv4Address source,KernelIpv4Address destination,Byte* p,UInt32 length){if(length<20)return false;UInt16 sourcePort=KernelNetworkMath.ReadUInt16Network(p);UInt16 destinationPort=KernelNetworkMath.ReadUInt16Network(p+2);UInt32 header=(UInt32)(p[12]>>4)*4U;if(header<20||header>length)return false;return KernelSockets.ObserveTcp(new(source,sourcePort),new(destination,destinationPort),p[13]);}
    private static Boolean WriteMac(Byte* p,KernelMacAddress m){p[0]=m.A;p[1]=m.B;p[2]=m.C;p[3]=m.D;p[4]=m.E;p[5]=m.F;return true;}
}
