using System;
using NovaOryn.Kernel.Contracts;
using NovaOryn.Kernel.Heap;
namespace NovaOryn.Kernel.Networking;

public static unsafe class KernelNetworkQueue
{
    private struct PacketRecord { public Byte Used,State;public UInt32 Interface,Length;public KernelHeapAllocation Payload; }
    private static PacketRecord* _packets;private static UInt32 _capacity,_count;private static KernelHeapAllocation _tableAllocation;private static KernelNetworkOptions _options;private static Boolean _initialized;
    internal static Boolean Initialize(KernelNetworkOptions options){if(_initialized)return true;if(!KernelHeap.TryAllocate((UInt64)options.InitialPackets*(UInt64)sizeof(PacketRecord),64,true,out _tableAllocation))return false;_packets=(PacketRecord*)(nuint)_tableAllocation.Address;_capacity=options.InitialPackets;_options=options;_initialized=true;return true;}
    public static UInt32 GetCount()=>_count;public static UInt32 GetCapacity()=>_capacity;
    public static Boolean Enqueue(KernelNetworkInterfaceHandle networkInterface,Byte* frame,UInt32 length,out KernelNetworkPacketHandle handle){handle=default;if(!_initialized||networkInterface.Value==0||frame==null||length<14||length>65535)return false;Int32 slot=Free();if(slot<0){if(!Grow())return false;slot=Free();if(slot<0)return false;}if(!KernelHeap.TryAllocate(length,16,false,out KernelHeapAllocation payload))return false;Byte* dst=(Byte*)(nuint)payload.Address;for(UInt32 i=0;i<length;i++)dst[i]=frame[i];PacketRecord* r=_packets+slot;r->Used=1;r->State=(Byte)KernelNetworkPacketState.Queued;r->Interface=networkInterface.Value;r->Length=length;r->Payload=payload;_count++;handle=new KernelNetworkPacketHandle((UInt32)slot+1U);return true;}
    public static Boolean ProcessNext(out KernelNetworkPacketHandle handle){handle=default;if(!_initialized)return false;for(Int32 i=0;i<(Int32)_capacity;i++){PacketRecord* r=_packets+i;if(r->Used==0||r->State!=(Byte)KernelNetworkPacketState.Queued)continue;handle=new KernelNetworkPacketHandle((UInt32)i+1U);Byte* payload=(Byte*)(nuint)r->Payload.Address;Boolean corrupted=KernelFaultInjection.TryCorruptPacket("network",payload,r->Length,out UInt32 changedOffset,out Byte original);Boolean ok=KernelNetworkStack.ReceiveEthernet(new KernelNetworkInterfaceHandle(r->Interface),payload,r->Length);if(corrupted)payload[changedOffset]=original;r->State=(Byte)(ok?KernelNetworkPacketState.Processed:KernelNetworkPacketState.Failed);return ok;}return false;}
    public static Boolean TryGet(KernelNetworkPacketHandle handle,out KernelNetworkPacketInfo info){info=default;if(!Try(handle,out PacketRecord* r))return false;info=new(handle,new KernelNetworkInterfaceHandle(r->Interface),(KernelNetworkPacketState)r->State,r->Length);return true;}
    public static Boolean Release(KernelNetworkPacketHandle handle){if(!Try(handle,out PacketRecord* r)||r->State==(Byte)KernelNetworkPacketState.Queued)return false;if(!KernelHeap.TryRelease(r->Payload))return false;for(Int32 i=0;i<sizeof(PacketRecord);i++)((Byte*)r)[i]=0;_count--;return true;}
    private static Boolean Try(KernelNetworkPacketHandle h,out PacketRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_capacity||(_packets+i)->Used==0)return false;r=_packets+i;return true;}private static Int32 Free(){for(Int32 i=0;i<(Int32)_capacity;i++)if((_packets+i)->Used==0)return i;return -1;}
    private static Boolean Grow(){if(_options.RegistryMode!=KernelNetworkRegistryMode.Dynamic)return false;UInt32 next=KernelNetworkMath.NextCapacity(_capacity,_options.MaximumPackets);if(next<=_capacity||!KernelHeap.TryAllocate((UInt64)next*(UInt64)sizeof(PacketRecord),64,true,out KernelHeapAllocation fresh))return false;PacketRecord* table=(PacketRecord*)(nuint)fresh.Address;for(UInt64 i=0;i<(UInt64)_capacity*(UInt64)sizeof(PacketRecord);i++)((Byte*)table)[i]=((Byte*)_packets)[i];KernelHeapAllocation old=_tableAllocation;_tableAllocation=fresh;_packets=table;_capacity=next;return KernelHeap.TryRelease(old);}
}
