<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NovaOryn.Memory.Virtual</RootNamespace>
    <AssemblyName>NovaOryn.Memory.Virtual.Contracts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NovaOryn.Core\NovaOryn.Core.csproj" />
    <ProjectReference Include="..\NovaOryn.Primitives\NovaOryn.Primitives.csproj" />
  </ItemGroup>
</Project>
