using System;
using NovaOryn.Kernel.Drivers;
namespace NovaOryn.Bus.Usb;
public enum UsbSpeed : Byte { Unknown=0, Low=1, Full=2, High=3, Super=4, SuperPlus=5 }
public enum UsbTransferDirection : Byte { HostToDevice=0, DeviceToHost=1 }
public enum UsbTransferType : Byte { Control=0, Isochronous=1, Bulk=2, Interrupt=3 }
public enum UsbDescriptorType : Byte { Device=1, Configuration=2, String=3, Interface=4, Endpoint=5, Bos=15, Hid=33, Hub=41, SuperSpeedHub=42 }
public enum UsbClassCode : Byte { PerInterface=0, Audio=1, Communications=2, Hid=3, Physical=5, Image=6, Printer=7, MassStorage=8, Hub=9, CdcData=10, SmartCard=11, Video=14, Billboard=17, Diagnostic=220, Wireless=224, Miscellaneous=239, ApplicationSpecific=254, VendorSpecific=255 }
public readonly struct UsbSetupPacket { public UsbSetupPacket(Byte requestType,Byte request,UInt16 value,UInt16 index,UInt16 length){RequestType=requestType;Request=request;Value=value;Index=index;Length=length;} public Byte RequestType{get;} public Byte Request{get;} public UInt16 Value{get;} public UInt16 Index{get;} public UInt16 Length{get;} }
public readonly struct UsbDeviceDescriptor { public UsbDeviceDescriptor(UInt16 usb,Byte cls,Byte sub,Byte proto,Byte maxPacket0,UInt16 vendor,UInt16 product,UInt16 release,Byte manufacturer,Byte productString,Byte serial,Byte configs){UsbVersion=usb;DeviceClass=cls;DeviceSubClass=sub;DeviceProtocol=proto;MaximumPacketSize0=maxPacket0;VendorId=vendor;ProductId=product;DeviceRelease=release;ManufacturerString=manufacturer;ProductString=productString;SerialNumberString=serial;ConfigurationCount=configs;} public UInt16 UsbVersion{get;} public Byte DeviceClass{get;} public Byte DeviceSubClass{get;} public Byte DeviceProtocol{get;} public Byte MaximumPacketSize0{get;} public UInt16 VendorId{get;} public UInt16 ProductId{get;} public UInt16 DeviceRelease{get;} public Byte ManufacturerString{get;} public Byte ProductString{get;} public Byte SerialNumberString{get;} public Byte ConfigurationCount{get;} }
public readonly struct UsbInterfaceDescriptor { public UsbInterfaceDescriptor(Byte number,Byte alternate,Byte endpoints,Byte cls,Byte sub,Byte proto,Byte str){Number=number;AlternateSetting=alternate;EndpointCount=endpoints;Class=cls;SubClass=sub;Protocol=proto;StringIndex=str;} public Byte Number{get;} public Byte AlternateSetting{get;} public Byte EndpointCount{get;} public Byte Class{get;} public Byte SubClass{get;} public Byte Protocol{get;} public Byte StringIndex{get;} }
public readonly struct UsbEndpointDescriptor { public UsbEndpointDescriptor(Byte address,Byte attributes,UInt16 maxPacket,Byte interval){Address=address;Attributes=attributes;MaximumPacketSize=maxPacket;Interval=interval;} public Byte Address{get;} public Byte Attributes{get;} public UInt16 MaximumPacketSize{get;} public Byte Interval{get;} public Byte Number=>(Byte)(Address&15); public Boolean In=>(Address&128)!=0; public UsbTransferType TransferType=>(UsbTransferType)(Attributes&3); }
public readonly struct UsbDeviceHandle { public UsbDeviceHandle(UInt32 value){Value=value;} public UInt32 Value{get;} }
public readonly struct UsbHostHandle { public UsbHostHandle(UInt32 value){Value=value;} public UInt32 Value{get;} }
public readonly struct UsbDeviceInfo { public UsbDeviceInfo(UsbDeviceHandle usb,KernelDeviceHandle device,UsbHostHandle host,Byte address,Byte port,UsbSpeed speed,UsbDeviceDescriptor descriptor,Byte configuration){Usb=usb;Device=device;Host=host;Address=address;Port=port;Speed=speed;Descriptor=descriptor;Configuration=configuration;} public UsbDeviceHandle Usb{get;} public KernelDeviceHandle Device{get;} public UsbHostHandle Host{get;} public Byte Address{get;} public Byte Port{get;} public UsbSpeed Speed{get;} public UsbDeviceDescriptor Descriptor{get;} public Byte Configuration{get;} }
public readonly struct UsbInterfaceInfo { public UsbInterfaceInfo(UsbDeviceHandle device,UsbInterfaceDescriptor descriptor,UsbEndpointDescriptor ep0,UsbEndpointDescriptor ep1,UsbEndpointDescriptor ep2,UsbEndpointDescriptor ep3){Device=device;Descriptor=descriptor;Endpoint0=ep0;Endpoint1=ep1;Endpoint2=ep2;Endpoint3=ep3;} public UsbDeviceHandle Device{get;} public UsbInterfaceDescriptor Descriptor{get;} public UsbEndpointDescriptor Endpoint0{get;} public UsbEndpointDescriptor Endpoint1{get;} public UsbEndpointDescriptor Endpoint2{get;} public UsbEndpointDescriptor Endpoint3{get;} public Boolean TryGetEndpoint(UInt32 index,out UsbEndpointDescriptor endpoint){endpoint=index==0?Endpoint0:index==1?Endpoint1:index==2?Endpoint2:index==3?Endpoint3:default;return index<Descriptor.EndpointCount&&index<4;} }
public readonly struct UsbBusCapabilities { public UsbBusCapabilities(Boolean initialized,UInt32 hosts,UInt32 devices,UInt32 interfaces,UInt32 enumerations,UInt32 failures){Initialized=initialized;Hosts=hosts;Devices=devices;Interfaces=interfaces;Enumerations=enumerations;EnumerationFailures=failures;} public Boolean Initialized{get;} public UInt32 Hosts{get;} public UInt32 Devices{get;} public UInt32 Interfaces{get;} public UInt32 Enumerations{get;} public UInt32 EnumerationFailures{get;} }
public readonly unsafe struct UsbHostCallbacks
{
 public readonly UInt64 Context;
 public readonly delegate*<UInt64,Byte,Byte,UsbSpeed,Byte,Boolean> PrepareDevice;
 public readonly delegate*<UInt64,Byte,Byte,UsbSetupPacket*,Byte*,UInt32,UInt32*,Boolean> Control;
 public readonly delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean> Bulk;
 public readonly delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean> Interrupt;
 public readonly delegate*<UInt64,Byte,UsbEndpointDescriptor*,Boolean> ConfigureEndpoint;
 public readonly delegate*<UInt64,Byte,Byte,Boolean,Boolean> ConfigureHub;
 public UsbHostCallbacks(UInt64 context,delegate*<UInt64,Byte,Byte,UsbSpeed,Byte,Boolean> prepareDevice,delegate*<UInt64,Byte,Byte,UsbSetupPacket*,Byte*,UInt32,UInt32*,Boolean> control,delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean> bulk,delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean> interrupt,delegate*<UInt64,Byte,UsbEndpointDescriptor*,Boolean> configureEndpoint,delegate*<UInt64,Byte,Byte,Boolean,Boolean> configureHub)
 {Context=context;PrepareDevice=prepareDevice;Control=control;Bulk=bulk;Interrupt=interrupt;ConfigureEndpoint=configureEndpoint;ConfigureHub=configureHub;}
}
