using System;
using NovaOryn.Kernel.Acpi;
using NovaOryn.Kernel.AddressSpace;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Heap;
using NovaOryn.Kernel.InterruptDispatch;
using NovaOryn.Kernel.Internal.X64;
using NovaOryn.Kernel.Pci;
using NovaOryn.Kernel.Smp;
namespace NovaOryn.Kernel.InterruptBroker;
/// <summary>Owns x64 Local APIC, I/O APIC, x2APIC, MSI and MSI-X interrupt delivery behind the driver framework's opaque broker.</summary>
public static unsafe class KernelInterruptBroker
{
    private const UInt32 ApicBaseMsr=0x1BU; private const UInt64 ApicEnabled=1UL<<11,X2ApicEnabled=1UL<<10;
    private struct Route { internal Byte Used,Vector,Mechanism,Direct; internal UInt32 Device,Source,Target; internal UInt64 Handle,Cookie,Callback; internal UInt16 Segment; internal Byte Bus,PciDevice,Function; }
    private struct IoApicMap { internal UInt64 VirtualAddress; internal UInt32 BaseGsi,MaximumGsi; }
    private static Route* _routes; private static KernelHeapAllocation _allocation; private static IoApicMap* _ioApics; private static UInt32 _capacity,_count,_ioApicCount; private static UInt64 _nextHandle; private static Boolean _initialized,_localApic,_ioApic,_x2Apic;
    /// <summary>Installs the opaque driver interrupt broker. PCI routes prefer MSI-X, then MSI, then I/O APIC INTx.</summary>
    public static Boolean Initialize(){if(_initialized)return true;if(!KernelDrivers.IsInitialized()||!KernelInterruptDispatch.IsInitialized()||!KernelHeap.IsInitialized()||!KernelAddressSpace.IsInitialized()||!KernelPci.IsInitialized())return false;if(!Allocate(32U,out _allocation,out _routes))return false;_capacity=32U;UInt64 apic=Native.ReadModelSpecificRegister(ApicBaseMsr);_localApic=(apic&ApicEnabled)!=0UL;_x2Apic=(apic&X2ApicEnabled)!=0UL;if(!_localApic)return false;if(!MapIoApics())return false;_ioApic=_ioApicCount!=0U;if(!KernelDrivers.InstallInterruptBroker(&Request,&Release))return false;_initialized=true;return true;}
    public static Boolean IsInitialized()=>_initialized;
    public static KernelInterruptBrokerCapabilities GetCapabilities()=>new(_initialized,_localApic,_ioApic,_x2Apic,true,true,_count);
    /// <summary>Routes a non-PCI legacy GSI directly to a kernel callback through the I/O APIC.</summary>
    public static Boolean RegisterLegacyGsi(UInt32 gsi,Boolean activeLow,Boolean levelTriggered,delegate*<Byte,UInt64,Boolean> callback,UInt64 cookie,out UInt64 handle)
    {
        handle=0UL;if(!_initialized||!_ioApic||callback==null)return false;if(_count==_capacity&&!Grow())return false;Byte vector=KernelInterruptDispatch.AllocateVector();if(vector==0)return false;Route* r=Free();if(r==null){KernelInterruptDispatch.ReleaseVector(vector);return false;}r->Used=1;r->Vector=vector;r->Mechanism=(Byte)KernelInterruptDeliveryMechanism.IoApic;r->Direct=1;r->Source=gsi;r->Target=0;r->Cookie=cookie;r->Callback=(UInt64)(void*)callback;r->Handle=++_nextHandle;if(r->Handle==0UL)r->Handle=++_nextHandle;if(!KernelInterruptDispatch.Register(vector,&Dispatch,r->Handle)){Clear(r);KernelInterruptDispatch.ReleaseVector(vector);return false;}KernelDriverInterruptRequest request=new(default,gsi,0,0U,levelTriggered,activeLow,0UL);if(!TryRouteGsi(gsi,&request,vector)){KernelInterruptDispatch.Unregister(vector);KernelInterruptDispatch.ReleaseVector(vector);Clear(r);return false;}_count++;handle=r->Handle;return true;
    }
    /// <summary>Releases a directly registered legacy GSI route.</summary>
    public static Boolean ReleaseLegacyGsi(UInt64 handle)
    {
        if(!_initialized||handle==0UL)return false;for(UInt32 i=0;i<_capacity;i++){Route* r=_routes+i;if(r->Used==0||r->Direct==0||r->Handle!=handle)continue;MaskGsi(r->Source);KernelInterruptDispatch.Unregister(r->Vector);KernelInterruptDispatch.ReleaseVector(r->Vector);Clear(r);if(_count!=0U)_count--;return true;}return false;
    }
    public static Boolean TryGetRoute(UInt32 index,out KernelInterruptRouteInfo info){info=default;if(index>=_count)return false;UInt32 found=0;for(UInt32 i=0;i<_capacity;i++){Route* r=_routes+i;if(r->Used==0)continue;if(found++==index){info=new(r->Handle,r->Device,r->Vector,(KernelInterruptDeliveryMechanism)r->Mechanism,r->Source,r->Target);return true;}}return false;}
    private static Boolean Request(KernelDriverInterruptRequest* request,KernelDriverInterruptHandle* handle){if(request==null||handle==null||!_initialized)return false;if(_count==_capacity&&!Grow())return false;Byte vector=KernelInterruptDispatch.AllocateVector();if(vector==0)return false;Route* r=Free();if(r==null){KernelInterruptDispatch.ReleaseVector(vector);return false;}r->Used=1;r->Vector=vector;r->Device=request->Device.Value;r->Target=request->TargetProcessor;r->Source=request->Source;r->Cookie=request->DriverCookie;r->Handle=++_nextHandle;if(r->Handle==0UL)r->Handle=++_nextHandle;if(!KernelInterruptDispatch.Register(vector,&Dispatch,r->Handle)){Clear(r);KernelInterruptDispatch.ReleaseVector(vector);return false;}Boolean routed=false;if(KernelPci.TryGetDevice(request->Device,out PciDeviceInfo pci)){r->Segment=pci.Location.Segment;r->Bus=pci.Location.Bus;r->PciDevice=pci.Location.Device;r->Function=pci.Location.Function;UInt32 apicId=ResolveApicId(request->TargetProcessor);UInt64 address=KernelInterruptBrokerMath.CreateMsiAddress(apicId);UInt16 data=KernelInterruptBrokerMath.CreateMsiData(vector);Boolean hasMsix=KernelPci.TryGetMsixCapability(pci.Location,out PciMsixCapability mx)&&mx.TableSize!=0U;Boolean hasMsi=KernelPci.TryGetMsiCapability(pci.Location,out _);KernelInterruptDeliveryMechanism preferred=KernelInterruptBrokerMath.SelectPciMechanism(hasMsix,hasMsi,_ioApic);if(preferred==KernelInterruptDeliveryMechanism.MsiX&&KernelPci.TryProgramMsix(pci.Location,0,address,data)){r->Mechanism=(Byte)KernelInterruptDeliveryMechanism.MsiX;routed=true;}if(!routed&&preferred!=KernelInterruptDeliveryMechanism.IoApic&&hasMsi&&KernelPci.TryProgramMsi(pci.Location,address,data)){r->Mechanism=(Byte)KernelInterruptDeliveryMechanism.Msi;routed=true;}if(!routed&&_ioApic&&TryRouteIntx(pci.Location,request,vector,out UInt32 gsi)){r->Mechanism=(Byte)KernelInterruptDeliveryMechanism.IoApic;r->Source=gsi;routed=true;}}else if(_ioApic&&TryRouteGsi(request->Source,request,vector)){r->Mechanism=(Byte)KernelInterruptDeliveryMechanism.IoApic;routed=true;}if(!routed){KernelInterruptDispatch.Unregister(vector);KernelInterruptDispatch.ReleaseVector(vector);Clear(r);return false;}_count++;*handle=new KernelDriverInterruptHandle(r->Handle);return true;}
    private static Boolean Release(KernelDriverInterruptHandle handle){if(!_initialized||handle.Value==0UL)return false;for(UInt32 i=0;i<_capacity;i++){Route* r=_routes+i;if(r->Used==0||r->Handle!=handle.Value)continue;PciLocation p=new(r->Segment,r->Bus,r->PciDevice,r->Function);if(r->Mechanism==(Byte)KernelInterruptDeliveryMechanism.Msi)KernelPci.TryDisableMsi(p);else if(r->Mechanism==(Byte)KernelInterruptDeliveryMechanism.MsiX)KernelPci.TryDisableMsix(p);else if(r->Mechanism==(Byte)KernelInterruptDeliveryMechanism.IoApic)MaskGsi(r->Source);KernelInterruptDispatch.Unregister(r->Vector);KernelInterruptDispatch.ReleaseVector(r->Vector);Clear(r);if(_count!=0U)_count--;return true;}return false;}
    private static Boolean Dispatch(Byte vector,UInt64 handle){for(UInt32 i=0;i<_capacity;i++){Route* r=_routes+i;if(r->Used==0||r->Handle!=handle||r->Vector!=vector)continue;if(r->Direct!=0&&r->Callback!=0UL){delegate*<Byte,UInt64,Boolean> cb=(delegate*<Byte,UInt64,Boolean>)(void*)r->Callback;return cb(vector,r->Cookie);}return KernelDrivers.DispatchInterrupt(new KernelDeviceHandle(r->Device),r->Cookie);}return false;}
    private static Boolean TryRouteIntx(PciLocation p,KernelDriverInterruptRequest* request,Byte vector,out UInt32 gsi){gsi=0;if(!KernelPci.TryRead8(p,0x3D,out Byte pin)||pin==0||!KernelPci.TryRead8(p,0x3C,out Byte line)||line==0xFF)return false;gsi=line;return TryRouteGsi(gsi,request,vector)&&KernelPci.SetIntxDisabled(p,false);}
    private static Boolean TryRouteGsi(UInt32 gsi,KernelDriverInterruptRequest* request,Byte vector){if(!TryFindIoApic(gsi,out UInt64 io,out UInt32 baseGsi))return false;UInt32 pin=gsi-baseGsi;UInt32 low=vector;if(request->ActiveLow)low|=1U<<13;if(request->LevelTriggered)low|=1U<<15;UInt32 high=(ResolveApicId(request->TargetProcessor)&0xFFU)<<24;return IoWrite(io,0x11U+pin*2U,high)&&IoWrite(io,0x10U+pin*2U,low);}
    private static Boolean MaskGsi(UInt32 gsi){if(!TryFindIoApic(gsi,out UInt64 io,out UInt32 baseGsi))return false;UInt32 pin=gsi-baseGsi;if(!IoRead(io,0x10U+pin*2U,out UInt32 low))return false;return IoWrite(io,0x10U+pin*2U,low|(1U<<16));}
    private static Boolean TryFindIoApic(UInt32 gsi,out UInt64 mapped,out UInt32 baseGsi){mapped=0;baseGsi=0;for(UInt32 i=0;i<_ioApicCount;i++){IoApicMap* a=_ioApics+i;if(gsi<a->BaseGsi||gsi>a->MaximumGsi)continue;mapped=a->VirtualAddress;baseGsi=a->BaseGsi;return true;}return false;}
    private static Boolean MapIoApics(){UInt32 advertised=KernelAcpi.GetIoApicCount();_ioApicCount=0U;if(advertised==0U)return true;if(!KernelHeap.TryAllocate((UInt64)advertised*(UInt64)sizeof(IoApicMap),16UL,true,out KernelHeapAllocation ioAllocation))return false;_ioApics=(IoApicMap*)(nuint)ioAllocation.Address;for(UInt32 i=0;i<advertised;i++){if(!KernelAcpi.TryGetIoApic(i,out AcpiIoApicInfo a))continue;if(!KernelPci.TryMapMmio(a.Address,0x20UL,out UInt64 mapped))continue;if(!IoRead(mapped,1U,out UInt32 version))continue;UInt32 max=(version>>16)&0xFFU;IoApicMap* entry=_ioApics+_ioApicCount++;entry->VirtualAddress=mapped;entry->BaseGsi=a.GlobalSystemInterruptBase;entry->MaximumGsi=a.GlobalSystemInterruptBase+max;}return true;}
    private static UInt32 ResolveApicId(UInt32 processor){if(KernelSmp.IsInitialized()&&KernelSmp.TryGetProcessor(processor,out KernelProcessorState state))return state.ApicId;return Native.GetCurrentApicId();}
    private static Boolean IoRead(UInt64 io,UInt32 index,out UInt32 value){value=0;if(!Native.WriteMmio32(io,index))return false;value=Native.ReadMmio32(io+0x10UL);return true;}
    private static Boolean IoWrite(UInt64 io,UInt32 index,UInt32 value)=>Native.WriteMmio32(io,index)&&Native.WriteMmio32(io+0x10UL,value);
    private static Route* Free(){for(UInt32 i=0;i<_capacity;i++)if((_routes+i)->Used==0)return _routes+i;return null;}
    private static Boolean Allocate(UInt32 c,out KernelHeapAllocation a,out Route* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)c*(UInt64)sizeof(Route),64UL,true,out a))return false;p=(Route*)(nuint)a.Address;return true;}
    private static Boolean Grow(){UInt32 next=_capacity>=0x40000000U?UInt32.MaxValue:_capacity*2U;if(next<=_capacity||!Allocate(next,out KernelHeapAllocation fresh,out Route* p))return false;for(UInt32 i=0;i<_capacity;i++)p[i]=_routes[i];KernelHeapAllocation old=_allocation;_allocation=fresh;_routes=p;_capacity=next;return KernelHeap.TryRelease(old);}
    private static void Clear(Route* r){Byte* p=(Byte*)r;for(UInt64 i=0;i<(UInt64)sizeof(Route);i++)p[i]=0;}
}
