using System;
using NovaOryn.Kernel.Contracts;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Heap;

namespace NovaOryn.Kernel.Storage;

/// <summary>Heap-backed block-device and volume registry with MBR/GPT partition discovery.</summary>
public static unsafe class KernelStorage
{
    private struct DeviceRecord { internal Byte Used,Kind,ReadOnly,Removable,Contextual; internal UInt32 DriverDevice,LogicalBlockSize,PhysicalBlockSize; internal UInt64 BlockCount,Read,Write,Flush; }
    private struct VolumeRecord { internal Byte Used,Scheme; internal UInt32 Device,Index,MbrType; internal UInt64 FirstBlock,BlockCount,TypeGuidLow,TypeGuidHigh; }
    private static DeviceRecord* _devices; private static VolumeRecord* _volumes;
    private static KernelHeapAllocation _deviceAllocation,_volumeAllocation;
    private static UInt32 _deviceCapacity,_volumeCapacity,_maximumDevices,_maximumVolumes,_deviceCount,_volumeCount;
    private static KernelStorageRegistryMode _mode; private static Boolean _initialized;

    public static Boolean Initialize()=>Initialize(KernelStorageOptions.DynamicDefault);
    public static Boolean Initialize(KernelStorageOptions options)
    { if(_initialized)return true;if(!KernelHeap.IsInitialized()||!KernelDrivers.IsInitialized()||!KernelStorageMath.IsValidOptions(options))return false;_mode=options.RegistryMode;_maximumDevices=options.MaximumDevices;_maximumVolumes=options.MaximumVolumes;if(!AllocateDevices(options.InitialDevices,out _deviceAllocation,out _devices))return false;if(!AllocateVolumes(options.InitialVolumes,out _volumeAllocation,out _volumes)){KernelHeap.TryRelease(_deviceAllocation);_devices=null;return false;}_deviceCapacity=options.InitialDevices;_volumeCapacity=options.InitialVolumes;_deviceCount=0;_volumeCount=0;if(!KernelStorageQueue.Initialize(options)||!KernelVfs.Initialize(options)){KernelHeap.TryRelease(_volumeAllocation);KernelHeap.TryRelease(_deviceAllocation);_devices=null;_volumes=null;return false;}_initialized=true;return true; }
    public static Boolean IsInitialized()=>_initialized;
    public static KernelStorageCapabilities GetCapabilities()=>new(_initialized,_mode,_deviceCount,_volumeCount,KernelVfs.MountCount,KernelVfs.OpenFileCount,KernelStorageQueue.Count,_deviceCapacity,_volumeCapacity,KernelVfs.MountCapacity,KernelVfs.OpenFileCapacity,KernelStorageQueue.Capacity);

    public static Boolean RegisterBlockDevice(KernelDeviceHandle driverDevice,KernelStorageDeviceKind kind,KernelStorageGeometry geometry,KernelBlockDeviceCallbacks callbacks,out KernelStorageDeviceHandle handle)
    { handle=default;if(!_initialized||driverDevice.Value==0||kind==KernelStorageDeviceKind.Unknown||!KernelStorageMath.IsValidGeometry(geometry)||callbacks.ReadBlocks==null)return false;Int32 slot=FreeDevice();if(slot<0){if(!GrowDevices())return false;slot=FreeDevice();if(slot<0)return false;}DeviceRecord* r=_devices+slot;Clear((Byte*)r,sizeof(DeviceRecord));r->Used=1;r->Kind=(Byte)kind;r->ReadOnly=geometry.ReadOnly?(Byte)1:(Byte)0;r->Removable=geometry.Removable?(Byte)1:(Byte)0;r->DriverDevice=driverDevice.Value;r->LogicalBlockSize=geometry.LogicalBlockSize;r->PhysicalBlockSize=geometry.PhysicalBlockSize;r->BlockCount=geometry.BlockCount;r->Read=(UInt64)(void*)callbacks.ReadBlocks;r->Write=(UInt64)(void*)callbacks.WriteBlocks;r->Flush=(UInt64)(void*)callbacks.Flush;_deviceCount++;handle=new KernelStorageDeviceHandle((UInt32)slot+1U);return true; }
    /// <summary>Registers a block device using callbacks that receive the owning generic device handle.</summary>
    public static Boolean RegisterBlockDevice(KernelDeviceHandle driverDevice,KernelStorageDeviceKind kind,KernelStorageGeometry geometry,KernelContextualBlockDeviceCallbacks callbacks,out KernelStorageDeviceHandle handle)
    { handle=default;if(!_initialized||driverDevice.Value==0||kind==KernelStorageDeviceKind.Unknown||!KernelStorageMath.IsValidGeometry(geometry)||callbacks.ReadBlocks==null)return false;Int32 slot=FreeDevice();if(slot<0){if(!GrowDevices())return false;slot=FreeDevice();if(slot<0)return false;}DeviceRecord* r=_devices+slot;Clear((Byte*)r,sizeof(DeviceRecord));r->Used=1;r->Contextual=1;r->Kind=(Byte)kind;r->ReadOnly=geometry.ReadOnly?(Byte)1:(Byte)0;r->Removable=geometry.Removable?(Byte)1:(Byte)0;r->DriverDevice=driverDevice.Value;r->LogicalBlockSize=geometry.LogicalBlockSize;r->PhysicalBlockSize=geometry.PhysicalBlockSize;r->BlockCount=geometry.BlockCount;r->Read=(UInt64)(void*)callbacks.ReadBlocks;r->Write=(UInt64)(void*)callbacks.WriteBlocks;r->Flush=(UInt64)(void*)callbacks.Flush;_deviceCount++;handle=new KernelStorageDeviceHandle((UInt32)slot+1U);return true; }
    public static Boolean TryGetGeometry(KernelStorageDeviceHandle handle,out KernelStorageGeometry geometry)
    { geometry=default;if(!TryDevice(handle,out DeviceRecord* r))return false;geometry=new KernelStorageGeometry(r->LogicalBlockSize,r->PhysicalBlockSize,r->BlockCount,r->ReadOnly!=0,r->Removable!=0);return true; }
    public static Boolean ReadBlocks(KernelStorageDeviceHandle handle,UInt64 firstBlock,UInt32 blockCount,Byte* buffer,UInt32 bufferBytes)
    { if(KernelFaultInjection.ShouldInject(KernelFaultKind.IoTimeout,"storage",out _))return false;if(!TryDevice(handle,out DeviceRecord* r)||buffer==null||blockCount==0||firstBlock>=r->BlockCount||blockCount>r->BlockCount-firstBlock||(UInt64)bufferBytes<(UInt64)blockCount*r->LogicalBlockSize)return false;if(r->Contextual!=0){delegate*<KernelDeviceHandle,UInt64,UInt32,Byte*,UInt32,Boolean> read=(delegate*<KernelDeviceHandle,UInt64,UInt32,Byte*,UInt32,Boolean>)(void*)r->Read;return read(new KernelDeviceHandle(r->DriverDevice),firstBlock,blockCount,buffer,bufferBytes);}delegate*<UInt64,UInt32,Byte*,UInt32,Boolean> readLegacy=(delegate*<UInt64,UInt32,Byte*,UInt32,Boolean>)(void*)r->Read;return readLegacy(firstBlock,blockCount,buffer,bufferBytes); }
    public static Boolean WriteBlocks(KernelStorageDeviceHandle handle,UInt64 firstBlock,UInt32 blockCount,Byte* buffer,UInt32 bufferBytes)
    { if(KernelFaultInjection.ShouldInject(KernelFaultKind.IoTimeout,"storage",out _))return false;if(!TryDevice(handle,out DeviceRecord* r)||r->ReadOnly!=0||r->Write==0||buffer==null||blockCount==0||firstBlock>=r->BlockCount||blockCount>r->BlockCount-firstBlock||(UInt64)bufferBytes<(UInt64)blockCount*r->LogicalBlockSize)return false;if(r->Contextual!=0){delegate*<KernelDeviceHandle,UInt64,UInt32,Byte*,UInt32,Boolean> write=(delegate*<KernelDeviceHandle,UInt64,UInt32,Byte*,UInt32,Boolean>)(void*)r->Write;return write(new KernelDeviceHandle(r->DriverDevice),firstBlock,blockCount,buffer,bufferBytes);}delegate*<UInt64,UInt32,Byte*,UInt32,Boolean> writeLegacy=(delegate*<UInt64,UInt32,Byte*,UInt32,Boolean>)(void*)r->Write;return writeLegacy(firstBlock,blockCount,buffer,bufferBytes); }
    public static Boolean Flush(KernelStorageDeviceHandle handle)
    { if(KernelFaultInjection.ShouldInject(KernelFaultKind.IoTimeout,"storage",out _))return false;if(!TryDevice(handle,out DeviceRecord* r))return false;if(r->Flush==0)return true;if(r->Contextual!=0){delegate*<KernelDeviceHandle,Boolean> flush=(delegate*<KernelDeviceHandle,Boolean>)(void*)r->Flush;return flush(new KernelDeviceHandle(r->DriverDevice));}delegate*<Boolean> flushLegacy=(delegate*<Boolean>)(void*)r->Flush;return flushLegacy(); }

    public static Boolean DiscoverPartitions(KernelStorageDeviceHandle device,Byte* scratch,UInt32 scratchBytes,out UInt32 discovered)
    { discovered=0;if(!TryDevice(device,out DeviceRecord* d)||scratch==null||scratchBytes<d->LogicalBlockSize)return false;if(!ReadBlocks(device,0,1,scratch,scratchBytes))return false;if(KernelStorageMath.IsProtectiveMbr(scratch,d->LogicalBlockSize))return DiscoverGpt(device,d,scratch,scratchBytes,out discovered);for(UInt32 i=0;i<4;i++){if(!KernelStorageMath.TryParseMbrPartition(scratch,d->LogicalBlockSize,i,out KernelPartitionInfo p))continue;if(RegisterVolume(device,p,out _))discovered++;}if(discovered==0){KernelPartitionInfo raw=new(KernelPartitionScheme.Raw,0,0,d->BlockCount,0,0,0);if(RegisterVolume(device,raw,out _))discovered=1;}return true; }
    public static Boolean TryGetVolume(KernelStorageVolumeHandle handle,out KernelStorageDeviceHandle device,out KernelPartitionInfo partition)
    { device=default;partition=default;if(!TryVolume(handle,out VolumeRecord* r))return false;device=new KernelStorageDeviceHandle(r->Device);partition=new KernelPartitionInfo((KernelPartitionScheme)r->Scheme,r->Index,r->FirstBlock,r->BlockCount,r->MbrType,r->TypeGuidLow,r->TypeGuidHigh);return true; }
    public static Boolean ReadVolumeBlocks(KernelStorageVolumeHandle volume,UInt64 relativeBlock,UInt32 count,Byte* buffer,UInt32 bufferBytes)
    { if(!TryVolume(volume,out VolumeRecord* r)||relativeBlock>=r->BlockCount||count==0||count>r->BlockCount-relativeBlock)return false;return ReadBlocks(new KernelStorageDeviceHandle(r->Device),r->FirstBlock+relativeBlock,count,buffer,bufferBytes); }
    public static Boolean WriteVolumeBlocks(KernelStorageVolumeHandle volume,UInt64 relativeBlock,UInt32 count,Byte* buffer,UInt32 bufferBytes)
    { if(!TryVolume(volume,out VolumeRecord* r)||relativeBlock>=r->BlockCount||count==0||count>r->BlockCount-relativeBlock)return false;return WriteBlocks(new KernelStorageDeviceHandle(r->Device),r->FirstBlock+relativeBlock,count,buffer,bufferBytes); }

    private static Boolean DiscoverGpt(KernelStorageDeviceHandle device,DeviceRecord* d,Byte* scratch,UInt32 scratchBytes,out UInt32 discovered)
    { discovered=0;if(!ReadBlocks(device,1,1,scratch,scratchBytes)||!KernelStorageMath.TryParseGptHeader(scratch,d->LogicalBlockSize,out UInt64 entriesLba,out UInt32 entryCount,out UInt32 entrySize))return false;UInt64 entryBytes=(UInt64)entryCount*(UInt64)entrySize;UInt64 entryBlocks=(entryBytes+d->LogicalBlockSize-1UL)/d->LogicalBlockSize;if(entriesLba>=d->BlockCount||entryBlocks>d->BlockCount-entriesLba)return false;UInt32 perBlock=d->LogicalBlockSize/entrySize;if(perBlock==0)return false;UInt32 limit=entryCount;for(UInt32 i=0;i<limit;i++){UInt64 lba=entriesLba+(i/perBlock);UInt32 offset=(i%perBlock)*entrySize;if(!ReadBlocks(device,lba,1,scratch,scratchBytes))return false;if(!KernelStorageMath.TryParseGptEntry(scratch+offset,entrySize,i,out KernelPartitionInfo p))continue;if(RegisterVolume(device,p,out _))discovered++;}return true; }
    private static Boolean RegisterVolume(KernelStorageDeviceHandle device,KernelPartitionInfo p,out KernelStorageVolumeHandle handle)
    { handle=default;if(!TryDevice(device,out DeviceRecord* owner)||p.BlockCount==0||p.FirstBlock>=owner->BlockCount||p.BlockCount>owner->BlockCount-p.FirstBlock)return false;Int32 slot=FreeVolume();if(slot<0){if(!GrowVolumes())return false;slot=FreeVolume();if(slot<0)return false;}VolumeRecord* r=_volumes+slot;Clear((Byte*)r,sizeof(VolumeRecord));r->Used=1;r->Scheme=(Byte)p.Scheme;r->Device=device.Value;r->Index=p.Index;r->FirstBlock=p.FirstBlock;r->BlockCount=p.BlockCount;r->MbrType=p.MbrType;r->TypeGuidLow=p.TypeGuidLow;r->TypeGuidHigh=p.TypeGuidHigh;_volumeCount++;handle=new KernelStorageVolumeHandle((UInt32)slot+1U);return true; }
    private static Int32 FreeDevice(){for(Int32 i=0;i<(Int32)_deviceCapacity;i++)if((_devices+i)->Used==0)return i;return -1;} private static Int32 FreeVolume(){for(Int32 i=0;i<(Int32)_volumeCapacity;i++)if((_volumes+i)->Used==0)return i;return -1;}
    private static Boolean GrowDevices(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_deviceCapacity,_maximumDevices);if(next<=_deviceCapacity||!AllocateDevices(next,out KernelHeapAllocation a,out DeviceRecord* n))return false;Copy((Byte*)_devices,(Byte*)n,(UInt64)_deviceCapacity*(UInt64)sizeof(DeviceRecord));KernelHeapAllocation old=_deviceAllocation;_deviceAllocation=a;_devices=n;_deviceCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean GrowVolumes(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_volumeCapacity,_maximumVolumes);if(next<=_volumeCapacity||!AllocateVolumes(next,out KernelHeapAllocation a,out VolumeRecord* n))return false;Copy((Byte*)_volumes,(Byte*)n,(UInt64)_volumeCapacity*(UInt64)sizeof(VolumeRecord));KernelHeapAllocation old=_volumeAllocation;_volumeAllocation=a;_volumes=n;_volumeCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean AllocateDevices(UInt32 count,out KernelHeapAllocation a,out DeviceRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)count*(UInt64)sizeof(DeviceRecord),64,true,out a))return false;p=(DeviceRecord*)(nuint)a.Address;return true;}
    private static Boolean AllocateVolumes(UInt32 count,out KernelHeapAllocation a,out VolumeRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)count*(UInt64)sizeof(VolumeRecord),64,true,out a))return false;p=(VolumeRecord*)(nuint)a.Address;return true;}
    private static Boolean TryDevice(KernelStorageDeviceHandle h,out DeviceRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_deviceCapacity||(_devices+i)->Used==0)return false;r=_devices+i;return true;}
    private static Boolean TryVolume(KernelStorageVolumeHandle h,out VolumeRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_volumeCapacity||(_volumes+i)->Used==0)return false;r=_volumes+i;return true;}
    private static void Clear(Byte* p,Int32 bytes){for(Int32 i=0;i<bytes;i++)p[i]=0;} private static void Copy(Byte* s,Byte* d,UInt64 bytes){for(UInt64 i=0;i<bytes;i++)d[i]=s[i];}
}
