import { injectable } from '@theia/core/shared/inversify';
import * as fs from 'fs/promises';
import * as path from 'path';
import {
    NovaOrynProjectConfiguration,
    NovaOrynProjectResult,
    NovaOrynProjectService
} from '../common/novaoryn-protocol';

@injectable()
export class NovaOrynProjectServiceImpl implements NovaOrynProjectService {
    async createProject(configuration: NovaOrynProjectConfiguration): Promise<NovaOrynProjectResult> {
        try {
            const validationError = this.validate(configuration);
            if (validationError) {
                return { success: false, error: validationError };
            }

            const projectRoot = path.resolve(configuration.location, configuration.name);
            await fs.mkdir(projectRoot, { recursive: false });

            const directories = configuration.kernelArchitecture === 'microkernel'
                ? this.microkernelDirectories()
                : this.monolithicDirectories();

            for (const directory of directories) {
                await fs.mkdir(path.join(projectRoot, directory), { recursive: true });
            }

            await fs.writeFile(
                path.join(projectRoot, 'NovaOryn.json'),
                JSON.stringify({
                    schemaVersion: 1,
                    sdkVersion: '0.0.10',
                    ...configuration
                }, null, 2) + '\n',
                'utf8'
            );

            await fs.writeFile(path.join(projectRoot, 'Kernel', 'Kernel.cs'), this.kernelSource(configuration), 'utf8');
            await fs.writeFile(path.join(projectRoot, 'Build.bat'), this.buildBatch(), 'utf8');
            await fs.writeFile(path.join(projectRoot, 'Run.bat'), this.runBatch(), 'utf8');
            await fs.writeFile(path.join(projectRoot, 'README.md'), this.projectReadme(configuration), 'utf8');

            return { success: true, projectPath: projectRoot };
        } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            return { success: false, error: message };
        }
    }

    protected validate(configuration: NovaOrynProjectConfiguration): string | undefined {
        if (!/^[A-Za-z][A-Za-z0-9._-]*$/.test(configuration.name)) {
            return 'Project name must begin with a letter and contain only letters, numbers, dot, underscore or hyphen.';
        }
        if (!configuration.location.trim()) {
            return 'A project location is required.';
        }
        return undefined;
    }

    protected monolithicDirectories(): string[] {
        return [
            'Kernel/Architecture', 'Kernel/Boot', 'Kernel/Drivers', 'Kernel/Filesystems',
            'Kernel/Interrupts', 'Kernel/Memory', 'Kernel/Networking', 'Kernel/Processes',
            'Kernel/Scheduler', 'Userland', 'Applications', 'Libraries', 'Tests'
        ];
    }

    protected microkernelDirectories(): string[] {
        return [
            'Kernel/Architecture', 'Kernel/Boot', 'Kernel/IPC', 'Kernel/Interrupts',
            'Kernel/Memory', 'Kernel/Scheduler', 'Services/DeviceManager', 'Services/FileSystem',
            'Services/Network', 'Services/ProcessManager', 'Drivers', 'Userland', 'Applications',
            'Libraries', 'Tests'
        ];
    }

    protected kernelSource(configuration: NovaOrynProjectConfiguration): string {
        return `namespace ${configuration.name}.Kernel;\n\npublic static class Kernel\n{\n    public static int KMain()\n    {\n        return 0;\n    }\n}\n`;
    }

    protected buildBatch(): string {
        return '@echo off\r\nsetlocal\r\necho NovaOryn project build entry point.\r\necho Connect this project to the installed NovaOryn SDK build toolchain.\r\nexit /b 0\r\n';
    }

    protected runBatch(): string {
        return '@echo off\r\nsetlocal\r\necho NovaOryn project run entry point.\r\necho Connect this project to the installed NovaOryn SDK QEMU runner.\r\nexit /b 0\r\n';
    }

    protected projectReadme(configuration: NovaOrynProjectConfiguration): string {
        return `# ${configuration.name}\n\nGenerated by NovaOryn IDE 0.0.10.\n\n- Kernel architecture: ${configuration.kernelArchitecture}\n- Target architecture: ${configuration.targetArchitecture}\n- Entry point: KMain\n`;
    }
}
