using System;
namespace NovaOryn.Kernel.Networking;

public static unsafe class KernelDhcpDns
{
    public static Boolean BuildDhcpDiscover(Byte* buffer,UInt32 capacity,UInt32 transactionId,KernelMacAddress mac,out UInt32 length){length=0;if(buffer==null||capacity<244||mac.IsZero)return false;for(UInt32 i=0;i<244;i++)buffer[i]=0;buffer[0]=1;buffer[1]=1;buffer[2]=6;KernelNetworkMath.WriteUInt32Network(buffer+4,4,transactionId);buffer[10]=0x80;buffer[28]=mac.A;buffer[29]=mac.B;buffer[30]=mac.C;buffer[31]=mac.D;buffer[32]=mac.E;buffer[33]=mac.F;buffer[236]=99;buffer[237]=130;buffer[238]=83;buffer[239]=99;buffer[240]=53;buffer[241]=1;buffer[242]=1;buffer[243]=255;length=244;return true;}
    public static Boolean TryParseDhcpOffer(Byte* packet,UInt32 length,UInt32 transactionId,out KernelIpv4Address offeredAddress,out KernelIpv4Address serverAddress){offeredAddress=default;serverAddress=default;if(packet==null||length<240||packet[0]!=2||KernelNetworkMath.ReadUInt32Network(packet+4)!=transactionId)return false;if(packet[236]!=99||packet[237]!=130||packet[238]!=83||packet[239]!=99)return false;offeredAddress=new KernelIpv4Address(KernelNetworkMath.ReadUInt32Network(packet+16));UInt32 i=240;Boolean offer=false;while(i<length){Byte code=packet[i++];if(code==255)break;if(code==0)continue;if(i>=length)return false;Byte size=packet[i++];if(i+(UInt32)size>length)return false;if(code==53&&size==1&&packet[i]==2)offer=true;if(code==54&&size==4)serverAddress=new KernelIpv4Address(KernelNetworkMath.ReadUInt32Network(packet+i));i+=(UInt32)size;}return offer&&offeredAddress.Value!=0;}
    public static Boolean BuildDnsAQuery(Byte* buffer,UInt32 capacity,UInt16 transactionId,String host,out UInt32 length)=>BuildDnsQuery(buffer,capacity,transactionId,host,KernelDnsRecordType.A,out length);
    public static Boolean BuildDnsQuery(Byte* buffer,UInt32 capacity,UInt16 transactionId,String host,KernelDnsRecordType recordType,out UInt32 length){length=0;if(buffer==null||host==null||host.Length==0||capacity<17)return false;for(UInt32 i=0;i<capacity;i++)buffer[i]=0;KernelNetworkMath.WriteUInt16Network(buffer,2,transactionId);KernelNetworkMath.WriteUInt16Network(buffer+2,2,0x0100);KernelNetworkMath.WriteUInt16Network(buffer+4,2,1);UInt32 at=12,labelStart=0;for(Int32 i=0;i<=host.Length;i++){Boolean end=i==host.Length||host[i]=='.';if(!end)continue;Int32 labelLength=i-(Int32)labelStart;if(labelLength<=0||labelLength>63||at+1U+(UInt32)labelLength+5U>capacity)return false;buffer[at++]=(Byte)labelLength;for(Int32 j=0;j<labelLength;j++){Char c=host[(Int32)labelStart+j];if(c>127)return false;buffer[at++]=(Byte)c;}labelStart=(UInt32)i+1U;}buffer[at++]=0;KernelNetworkMath.WriteUInt16Network(buffer+at,2,(UInt16)recordType);at+=2;KernelNetworkMath.WriteUInt16Network(buffer+at,2,1);at+=2;length=at;return true;}
    public static Boolean TryParseDnsAResponse(Byte* packet,UInt32 length,UInt16 transactionId,out KernelIpv4Address address){address=default;if(packet==null||length<12||KernelNetworkMath.ReadUInt16Network(packet)!=transactionId||(KernelNetworkMath.ReadUInt16Network(packet+2)&0x8000)==0)return false;UInt16 questions=KernelNetworkMath.ReadUInt16Network(packet+4),answers=KernelNetworkMath.ReadUInt16Network(packet+6);UInt32 at=12;for(UInt16 q=0;q<questions;q++){if(!SkipDnsName(packet,length,ref at)||at+4>length)return false;at+=4;}for(UInt16 a=0;a<answers;a++){if(!SkipDnsName(packet,length,ref at)||at+10>length)return false;UInt16 type=KernelNetworkMath.ReadUInt16Network(packet+at);UInt16 klass=KernelNetworkMath.ReadUInt16Network(packet+at+2);UInt16 dataLength=KernelNetworkMath.ReadUInt16Network(packet+at+8);at+=10;if(at+(UInt32)dataLength>length)return false;if(type==1&&klass==1&&dataLength==4){address=new KernelIpv4Address(KernelNetworkMath.ReadUInt32Network(packet+at));return true;}at+=(UInt32)dataLength;}return false;}

    public static Boolean TryParseDnsAaaaResponse(Byte* packet,UInt32 length,UInt16 transactionId,out KernelIpv6Address address){address=default;if(packet==null||length<12||KernelNetworkMath.ReadUInt16Network(packet)!=transactionId||(KernelNetworkMath.ReadUInt16Network(packet+2)&0x8000)==0)return false;UInt16 questions=KernelNetworkMath.ReadUInt16Network(packet+4),answers=KernelNetworkMath.ReadUInt16Network(packet+6);UInt32 at=12;for(UInt16 q=0;q<questions;q++){if(!SkipDnsName(packet,length,ref at)||at+4>length)return false;at+=4;}for(UInt16 a=0;a<answers;a++){if(!SkipDnsName(packet,length,ref at)||at+10>length)return false;UInt16 type=KernelNetworkMath.ReadUInt16Network(packet+at);UInt16 klass=KernelNetworkMath.ReadUInt16Network(packet+at+2);UInt16 dataLength=KernelNetworkMath.ReadUInt16Network(packet+at+8);at+=10;if(at+(UInt32)dataLength>length)return false;if(type==28&&klass==1&&dataLength==16){address=KernelNetworkMath.ReadIpv6Address(packet+at);return true;}at+=(UInt32)dataLength;}return false;}
    private static Boolean SkipDnsName(Byte* packet,UInt32 length,ref UInt32 at){while(at<length){Byte size=packet[at++];if(size==0)return true;if((size&0xC0)==0xC0){if(at>=length)return false;at++;return true;}if(size>63||at+(UInt32)size>length)return false;at+=(UInt32)size;}return false;}
}
