using System;
using NovaOryn.Bus.Usb;
using NovaOryn.Kernel.AddressSpace;
using NovaOryn.Kernel.Heap;
using NovaOryn.Kernel.Memory;
using NovaOryn.Kernel.Pci;
namespace NovaOryn.Usb.Xhci;
/// <summary>PCI xHCI host-controller implementation with command, event and endpoint transfer rings.</summary>
public static unsafe class KernelXhci
{
 const UInt32 SpinLimit=40000000U;const Int32 MaxControllers=8,MaxSlots=256,MaxEndpoints=2048;
 struct Ring{internal KernelPhysicalAllocation Memory;internal UInt16 Enqueue;internal Byte Cycle;}
 struct Slot{internal Byte Used,SlotId,LogicalAddress,RootPort,Depth,SpeedId,HubPorts,ContextEntries,MultiTt,ParentSlot,TtPort;internal UInt32 Route;internal UInt16 Ep0Packet;internal KernelPhysicalAllocation Output,Input;internal Ring Ep0;}
 struct Endpoint{internal Byte Used,SlotId,Dci,Address,Type,Interval;internal UInt16 MaxPacket;internal Ring Ring;}
 struct Controller{internal Byte Used,Ports,Slots,ContextSize,State,EventCycle;internal UInt16 EventIndex;internal UInt16 Segment;internal Byte Bus,Device,Function,PendingSlot;internal UInt32 Host;internal UInt64 Mmio,Operational,Runtime,Doorbells;internal KernelPhysicalAllocation Dcbaa,Command,Event,Erst,ScratchArray;internal UInt64 SlotTable,EndpointTable;internal UInt16 CommandEnqueue;internal Byte CommandCycle;}
 static Controller* _controllers;static KernelHeapAllocation _controllersAllocation;static Boolean _initialized;static UInt32 _controllerCount,_running,_connected;
 public static Boolean Initialize(){if(_initialized)return true;if(!KernelUsbBus.Initialize()||!KernelPhysicalMemory.IsInitialized()||!KernelAddressSpace.IsInitialized()||!KernelHeap.IsInitialized())return false;if(!KernelHeap.TryAllocate((UInt64)MaxControllers*(UInt64)sizeof(Controller),64,true,out _controllersAllocation))return false;_controllers=(Controller*)(nuint)_controllersAllocation.Address;for(UInt32 i=0;i<KernelPci.GetDeviceCount();i++){if(!KernelPci.TryGetDevice(i,out PciDeviceInfo p)||p.ClassCode!=0x0C0330U)continue;if(_controllerCount>=MaxControllers)break;Controller* c=_controllers+_controllerCount;Clear((Byte*)c,(UInt64)sizeof(Controller));c->Used=1;c->Segment=p.Location.Segment;c->Bus=p.Location.Bus;c->Device=p.Location.Device;c->Function=p.Location.Function;c->State=(Byte)XhciControllerState.Discovered;_controllerCount++;if(!Start(c)){c->State=(Byte)XhciControllerState.Failed;continue;}_running++;} _initialized=true;return ScanRootPorts();}
 public static XhciCapabilities GetCapabilities()=>new(_initialized,_controllerCount,_running,_connected,true);public static UInt32 GetControllerCount()=>_controllerCount;
 public static Boolean TryGetController(UInt32 index,out XhciControllerInfo info){info=default;if(index>=_controllerCount)return false;Controller* c=_controllers+index;if(c->Used==0)return false;info=new XhciControllerInfo(new PciLocation(c->Segment,c->Bus,c->Device,c->Function),c->Mmio,c->Ports,c->Slots,(XhciControllerState)c->State);return true;}
 public static Boolean ScanRootPorts(){if(!_initialized&&_controllerCount==0)return false;_connected=0;for(UInt32 ci=0;ci<_controllerCount;ci++){Controller* c=_controllers+ci;if(c->State!=(Byte)XhciControllerState.Running)continue;for(Byte p=1;p<=c->Ports;p++){UInt32 ps=R32(Port(c,p));if((ps&1U)==0)continue;_connected++;UsbSpeed speed=SpeedFromId((Byte)((ps>>10)&15U));KernelUsbBus.EnumeratePort(new UsbHostHandle(c->Host),p,speed,out _);}}return true;}
 static Boolean Start(Controller* c){PciLocation loc=new(c->Segment,c->Bus,c->Device,c->Function);if(!KernelPci.TryMapBar(loc,0,out PciBarInfo bar,out UInt64 mmio)||bar.Type==PciBarType.Io||bar.Length<0x2000UL)return false;if(!KernelPci.TryRead16(loc,4,out UInt16 command)||!KernelPci.TryWrite16(loc,4,(UInt16)(command|0x0006U)))return false;c->Mmio=mmio;Byte cap=R8(mmio);UInt32 hcs1=R32(mmio+4),hcs2=R32(mmio+8),hcc1=R32(mmio+0x10);c->Slots=(Byte)(hcs1&0xFFU);c->Ports=(Byte)((hcs1>>24)&0xFFU);c->ContextSize=(Byte)(((hcc1&(1U<<2))!=0)?64:32);c->Operational=mmio+cap;c->Doorbells=mmio+(R32(mmio+0x14)&~3U);c->Runtime=mmio+(R32(mmio+0x18)&~31U);if(c->Slots==0||c->Ports==0||(R32(c->Operational+8)&1U)==0)return false;W32(c->Operational,R32(c->Operational)&~1U);if(!Wait32(c->Operational+4,1U,1U))return false;W32(c->Operational,R32(c->Operational)|2U);if(!Wait32(c->Operational,2U,0U)||!Wait32(c->Operational+4,1U<<11,0U))return false;if(!AllocateControllerMemory(c,hcs2))return false;SetupCommandRing(c);SetupEventRing(c);W64(c->Operational+0x30,c->Dcbaa.StartAddress);W64(c->Operational+0x18,c->Command.StartAddress|1UL);W32(c->Operational+0x38,c->Slots);UInt64 ir=c->Runtime+0x20;W32(ir+8,1U);W64(ir+0x10,c->Erst.StartAddress);W64(ir+0x18,c->Event.StartAddress);W32(ir,2U);W32(c->Operational,R32(c->Operational)|1U);if(!Wait32(c->Operational+4,1U,0U))return false;UsbHostCallbacks callbacks=new((UInt64)(nuint)c,&PrepareDevice,&ControlTransfer,&BulkTransfer,&InterruptTransfer,&ConfigureEndpoint,&ConfigureHub);if(!KernelUsbBus.RegisterHost(callbacks,out UsbHostHandle host))return false;c->Host=host.Value;c->State=(Byte)XhciControllerState.Running;return true;}
 static Boolean AllocateControllerMemory(Controller* c,UInt32 hcs2){if(!Page(out c->Dcbaa)||!Page(out c->Command)||!Page(out c->Event)||!Page(out c->Erst))return false;Zero(c->Dcbaa);Zero(c->Command);Zero(c->Event);Zero(c->Erst);if(!KernelHeap.TryAllocate((UInt64)MaxSlots*(UInt64)sizeof(Slot),64,true,out KernelHeapAllocation sa)||!KernelHeap.TryAllocate((UInt64)MaxEndpoints*(UInt64)sizeof(Endpoint),64,true,out KernelHeapAllocation ea))return false;c->SlotTable=sa.Address;c->EndpointTable=ea.Address;UInt32 scratch=((hcs2>>27)&31U)<<5|((hcs2>>21)&31U);if(scratch!=0){UInt64 pages=((UInt64)scratch*8UL+4095UL)/4096UL;if(!KernelPhysicalMemory.TryAllocate(pages,1,out c->ScratchArray))return false;Zero(c->ScratchArray);UInt64* a=(UInt64*)Direct(c->ScratchArray);for(UInt32 i=0;i<scratch;i++){if(!Page(out KernelPhysicalAllocation sp))return false;Zero(sp);a[i]=sp.StartAddress;}((UInt64*)Direct(c->Dcbaa))[0]=c->ScratchArray.StartAddress;}return true;}
 static void SetupCommandRing(Controller* c){UInt32* trb=(UInt32*)Direct(c->Command);UInt64 p=c->Command.StartAddress;UInt32 i=255U*4U;trb[i]=(UInt32)p;trb[i+1]=(UInt32)(p>>32);trb[i+2]=0;trb[i+3]=(6U<<10)|(1U<<1)|1U;c->CommandEnqueue=0;c->CommandCycle=1;}
 static void SetupEventRing(Controller* c){UInt64* erst=(UInt64*)Direct(c->Erst);erst[0]=c->Event.StartAddress;erst[1]=256UL;c->EventIndex=0;c->EventCycle=1;}
 static Boolean PrepareDevice(UInt64 context,Byte parentAddress,Byte port,UsbSpeed speed,Byte logicalAddress){Controller* c=(Controller*)(nuint)context;if(c==null||port==0)return false;Byte root=port,depth=0,parentSlot=0,ttPort=0;UInt32 route=0;Byte speedId=SpeedId(speed);if(parentAddress==0){if(port>c->Ports||!ResetRootPort(c,port,out speedId))return false;}else{Slot* parent=FindSlot(c,parentAddress);if(parent==null||parent->Depth>=5)return false;parentSlot=parent->SlotId;root=parent->RootPort;depth=(Byte)(parent->Depth+1);UInt32 nibble=port>15?(UInt32)15:port;route=parent->Route|(nibble<<(parent->Depth*4));if((speed==UsbSpeed.Low||speed==UsbSpeed.Full)&&parent->SpeedId==3){ttPort=port;}}
 if(!Command(c,0,0,0,9U<<10,out Byte slotId))return false;Slot* s=Slots(c)+slotId;if(s->Used!=0)return false;Clear((Byte*)s,(UInt64)sizeof(Slot));s->Used=1;s->SlotId=slotId;s->LogicalAddress=logicalAddress;s->RootPort=root;s->Depth=depth;s->SpeedId=speedId;s->Route=route;s->ParentSlot=parentSlot;s->TtPort=ttPort;s->Ep0Packet=DefaultEp0(speedId);s->ContextEntries=1;if(!Page(out s->Output)||!Page(out s->Input)||!Page(out s->Ep0.Memory))return Disable(c,s);Zero(s->Output);Zero(s->Input);Zero(s->Ep0.Memory);SetupTransferRing(&s->Ep0);((UInt64*)Direct(c->Dcbaa))[slotId]=s->Output.StartAddress;BuildInput(c,s,1,null);if(!Command(c,s->Input.StartAddress,0,0,(11U<<10)|((UInt32)slotId<<24),out _))return Disable(c,s);c->PendingSlot=slotId;return true;}
 static Boolean ControlTransfer(UInt64 context,Byte address,Byte endpoint,UsbSetupPacket* setup,Byte* buffer,UInt32 bytes,UInt32* transferred){Controller* c=(Controller*)(nuint)context;if(transferred!=null)*transferred=0;if(c==null||setup==null||endpoint!=0)return false;Slot* s=address==0?SlotById(c,c->PendingSlot):FindSlot(c,address);if(s==null)return false;if(setup->RequestType==0&&setup->Request==5){if(transferred!=null)*transferred=0;return true;}Boolean input=(setup->RequestType&0x80)!=0;KernelPhysicalAllocation bounce=default;Byte* dma=null;if(bytes!=0){if(!Buffer(bytes,out bounce,out dma))return false;if(!input&&buffer!=null)Copy(buffer,dma,bytes);}UInt64 setupValue=(UInt64)setup->RequestType|((UInt64)setup->Request<<8)|((UInt64)setup->Value<<16)|((UInt64)setup->Index<<32)|((UInt64)setup->Length<<48);UInt32 trt=bytes==0?0U:(input?3U:2U);if(!Enqueue(&s->Ep0,setupValue,0,8U,(2U<<10)|(1U<<6)|(trt<<16)|(bytes!=0?1U<<4:0U))){Release(bounce);return false;}if(bytes!=0&&!Enqueue(&s->Ep0,bounce.StartAddress,0,bytes,(3U<<10)|(input?1U<<16:0U)|(1U<<4))){Release(bounce);return false;}Boolean statusIn=bytes==0||!input;if(!Enqueue(&s->Ep0,0,0,0,(4U<<10)|(statusIn?1U<<16:0U)|(1U<<5))){Release(bounce);return false;}RingDoorbell(c,s->SlotId,1);Boolean ok=WaitTransfer(c,s->SlotId,1,bytes,out UInt32 actual);if(ok&&bytes!=0&&input&&buffer!=null)Copy(dma,buffer,actual);if(ok&&input&&setup->Request==6&&(setup->Value>>8)==1&&actual>=8&&dma[7]!=s->Ep0Packet)ok=UpdateEp0(c,s,dma[7]);Release(bounce);if(transferred!=null)*transferred=actual;return ok;}
 static Boolean ConfigureEndpoint(UInt64 context,Byte address,UsbEndpointDescriptor* descriptor){Controller* c=(Controller*)(nuint)context;if(c==null||descriptor==null||descriptor->Number==0)return false;Slot* s=FindSlot(c,address);if(s==null)return false;Byte dci=Dci(descriptor->Address);if(FindEndpoint(c,s->SlotId,dci)!=null)return true;Endpoint* e=FreeEndpoint(c);if(e==null)return false;Clear((Byte*)e,(UInt64)sizeof(Endpoint));e->Used=1;e->SlotId=s->SlotId;e->Dci=dci;e->Address=descriptor->Address;e->Type=(Byte)descriptor->TransferType;e->Interval=descriptor->Interval;e->MaxPacket=descriptor->MaximumPacketSize;if(!Page(out e->Ring.Memory)){e->Used=0;return false;}Zero(e->Ring.Memory);SetupTransferRing(&e->Ring);if(dci>s->ContextEntries)s->ContextEntries=dci;BuildInput(c,s,dci,e);if(!Command(c,s->Input.StartAddress,0,0,(12U<<10)|((UInt32)s->SlotId<<24),out _)){Release(e->Ring.Memory);e->Used=0;return false;}return true;}
 static Boolean ConfigureHub(UInt64 context,Byte address,Byte ports,Boolean multiTt){Controller* c=(Controller*)(nuint)context;if(c==null)return false;Slot* s=FindSlot(c,address);if(s==null)return false;s->HubPorts=ports;s->MultiTt=multiTt?(Byte)1:(Byte)0;BuildInput(c,s,0,null);return Command(c,s->Input.StartAddress,0,0,(13U<<10)|((UInt32)s->SlotId<<24),out _);}
 static Boolean BulkTransfer(UInt64 context,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred)=>DataTransfer((Controller*)(nuint)context,address,endpoint,buffer,bytes,transferred);
 static Boolean InterruptTransfer(UInt64 context,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred)=>DataTransfer((Controller*)(nuint)context,address,endpoint,buffer,bytes,transferred);
 static Boolean DataTransfer(Controller* c,Byte address,Byte endpoint,Byte* buffer,UInt32 bytes,UInt32* transferred){if(transferred!=null)*transferred=0;if(c==null||buffer==null||bytes==0||bytes>4096)return false;Slot* s=FindSlot(c,address);if(s==null)return false;Byte dci=Dci(endpoint);Endpoint* e=FindEndpoint(c,s->SlotId,dci);if(e==null)return false;Boolean input=(endpoint&0x80)!=0;if(!Buffer(bytes,out KernelPhysicalAllocation bounce,out Byte* dma))return false;if(!input)Copy(buffer,dma,bytes);if(!Enqueue(&e->Ring,bounce.StartAddress,0,bytes,(1U<<10)|(1U<<2)|(1U<<5))){Release(bounce);return false;}RingDoorbell(c,s->SlotId,dci);Boolean ok=WaitTransfer(c,s->SlotId,dci,bytes,out UInt32 actual);if(ok&&input)Copy(dma,buffer,actual);Release(bounce);if(transferred!=null)*transferred=actual;return ok;}
 static Boolean UpdateEp0(Controller* c,Slot* s,UInt16 packet){if(packet==0||packet==s->Ep0Packet)return packet!=0;s->Ep0Packet=packet;BuildInput(c,s,1,null);return Command(c,s->Input.StartAddress,0,0,(13U<<10)|((UInt32)s->SlotId<<24),out _);}
 static void BuildInput(Controller* c,Slot* s,Byte addDci,Endpoint* e){Byte* input=Direct(s->Input);Clear(input,4096);UInt32* icc=(UInt32*)input;UInt32 flags=1U;if(addDci!=0)flags|=1U<<addDci;icc[1]=flags;UInt32* slot=(UInt32*)(input+c->ContextSize);slot[0]=(s->Route&0xFFFFFU)|((UInt32)s->SpeedId<<20)|((UInt32)s->MultiTt<<25)|(s->HubPorts!=0?1U<<26:0U)|((UInt32)s->ContextEntries<<27);slot[1]=((UInt32)s->RootPort<<16)|((UInt32)s->HubPorts<<24);if(s->TtPort!=0)slot[2]=(UInt32)s->ParentSlot|((UInt32)s->TtPort<<8);if(addDci==1){UInt32* ep=(UInt32*)(input+(UInt32)c->ContextSize*2U);BuildEndpointContext(ep,4,s->Ep0Packet,s->Ep0.Memory.StartAddress,0,8);}else if(e!=null){UInt32* ep=(UInt32*)(input+(UInt32)c->ContextSize*(UInt32)(e->Dci+1));Byte type=EndpointType(e->Address,(UsbTransferType)e->Type);BuildEndpointContext(ep,type,e->MaxPacket,e->Ring.Memory.StartAddress,Interval(s->SpeedId,(UsbTransferType)e->Type,e->Interval),e->MaxPacket);}}
 static void BuildEndpointContext(UInt32* ep,Byte type,UInt16 packet,UInt64 dequeue,Byte interval,UInt16 average){for(Int32 i=0;i<8;i++)ep[i]=0;ep[0]=(UInt32)interval<<16;ep[1]=(3U<<1)|((UInt32)type<<3)|((UInt32)packet<<16);ep[2]=(UInt32)dequeue|1U;ep[3]=(UInt32)(dequeue>>32);ep[4]=average;}
 static Boolean ResetRootPort(Controller* c,Byte port,out Byte speed){speed=0;UInt64 a=Port(c,port);UInt32 v=R32(a);if((v&1U)==0)return false;speed=(Byte)((v>>10)&15U);if((v&2U)!=0)return true;UInt32 write=(v&~0x00FE0000U)|(1U<<4);W32(a,write);for(UInt32 i=0;i<SpinLimit;i++){UInt32 p=R32(a);if((p&1U)==0)return false;if((p&(1U<<4))==0&&(p&2U)!=0){speed=(Byte)((p>>10)&15U);return true;}}return false;}
 static Boolean Command(Controller* c,UInt64 parameter,UInt32 status,UInt32 controlLow,UInt32 control,out Byte slot){slot=0;UInt32* ring=(UInt32*)Direct(c->Command);UInt32 i=(UInt32)c->CommandEnqueue*4U;ring[i]=(UInt32)parameter;ring[i+1]=(UInt32)(parameter>>32);ring[i+2]=status;ring[i+3]=control|c->CommandCycle;c->CommandEnqueue++;if(c->CommandEnqueue==255){c->CommandEnqueue=0;c->CommandCycle=(Byte)(c->CommandCycle==0?1:0);}W32(c->Doorbells,0);return WaitCommand(c,out slot);}
 static Boolean WaitCommand(Controller* c,out Byte slot){slot=0;for(UInt32 spin=0;spin<SpinLimit;spin++){if(!NextEvent(c,out UInt32 d0,out UInt32 d1,out UInt32 d2,out UInt32 d3))continue;Byte type=(Byte)((d3>>10)&63U);if(type!=33)continue;Byte code=(Byte)(d2>>24);slot=(Byte)(d3>>24);return code==1;}return false;}
 static Boolean WaitTransfer(Controller* c,Byte slot,Byte dci,UInt32 requested,out UInt32 actual){actual=0;for(UInt32 spin=0;spin<SpinLimit;spin++){if(!NextEvent(c,out UInt32 d0,out UInt32 d1,out UInt32 d2,out UInt32 d3))continue;Byte type=(Byte)((d3>>10)&63U);if(type!=32)continue;if((Byte)(d3>>24)!=slot||(Byte)((d3>>16)&31U)!=dci)continue;Byte code=(Byte)(d2>>24);UInt32 remain=d2&0x00FFFFFFU;actual=remain>requested?0:requested-remain;return code==1||code==13;}return false;}
 static Boolean NextEvent(Controller* c,out UInt32 d0,out UInt32 d1,out UInt32 d2,out UInt32 d3){UInt32* ring=(UInt32*)Direct(c->Event);UInt32 i=(UInt32)c->EventIndex*4U;d0=ring[i];d1=ring[i+1];d2=ring[i+2];d3=ring[i+3];if((d3&1U)!=c->EventCycle)return false;c->EventIndex++;if(c->EventIndex==256){c->EventIndex=0;c->EventCycle=(Byte)(c->EventCycle==0?1:0);}W64(c->Runtime+0x20+0x18,c->Event.StartAddress+(UInt64)c->EventIndex*16UL);return true;}
 static Boolean Enqueue(Ring* r,UInt64 parameter,UInt32 statusHi,UInt32 length,UInt32 control){UInt32* ring=(UInt32*)Direct(r->Memory);UInt32 i=(UInt32)r->Enqueue*4U;ring[i]=(UInt32)parameter;ring[i+1]=(UInt32)(parameter>>32);ring[i+2]=length|statusHi;ring[i+3]=control|r->Cycle;r->Enqueue++;if(r->Enqueue==255){r->Enqueue=0;r->Cycle=(Byte)(r->Cycle==0?1:0);}return true;}
 static void SetupTransferRing(Ring* r){UInt32* ring=(UInt32*)Direct(r->Memory);UInt64 p=r->Memory.StartAddress;UInt32 i=255U*4U;ring[i]=(UInt32)p;ring[i+1]=(UInt32)(p>>32);ring[i+2]=0;ring[i+3]=(6U<<10)|(1U<<1)|1U;r->Enqueue=0;r->Cycle=1;}
 static void RingDoorbell(Controller* c,Byte slot,Byte dci)=>W32(c->Doorbells+(UInt64)slot*4UL,dci);
 static Slot* FindSlot(Controller* c,Byte logical){if(logical==0)return null;Slot* t=Slots(c);for(Int32 i=1;i<MaxSlots;i++)if((t+i)->Used!=0&&(t+i)->LogicalAddress==logical)return t+i;return null;}static Slot* SlotById(Controller* c,Byte id){if(id==0)return null;Slot* s=Slots(c)+id;return s->Used!=0?s:null;}static Slot* Slots(Controller* c)=>(Slot*)(nuint)c->SlotTable;
 static Endpoint* FindEndpoint(Controller* c,Byte slot,Byte dci){Endpoint* e=(Endpoint*)(nuint)c->EndpointTable;for(Int32 i=0;i<MaxEndpoints;i++)if((e+i)->Used!=0&&(e+i)->SlotId==slot&&(e+i)->Dci==dci)return e+i;return null;}static Endpoint* FreeEndpoint(Controller* c){Endpoint* e=(Endpoint*)(nuint)c->EndpointTable;for(Int32 i=0;i<MaxEndpoints;i++)if((e+i)->Used==0)return e+i;return null;}
 static Boolean Disable(Controller* c,Slot* s){if(s->SlotId!=0)Command(c,0,0,0,(10U<<10)|((UInt32)s->SlotId<<24),out _);Release(s->Output);Release(s->Input);Release(s->Ep0.Memory);Clear((Byte*)s,(UInt64)sizeof(Slot));return false;}
 static Byte Dci(Byte address){Byte n=(Byte)(address&15U);return (Byte)(n*2U+((address&0x80)!=0?1U:0U));}static Byte EndpointType(Byte address,UsbTransferType type){Boolean input=(address&0x80)!=0;if(type==UsbTransferType.Isochronous)return input?(Byte)5:(Byte)1;if(type==UsbTransferType.Bulk)return input?(Byte)6:(Byte)2;if(type==UsbTransferType.Interrupt)return input?(Byte)7:(Byte)3;return 4;}
 static Byte Interval(Byte speedId,UsbTransferType type,Byte value){if(value==0)return 0;if(speedId>=3)return (Byte)(value>16?15:value-1);UInt32 target=(UInt32)value*8U,exp=0,p=1;while(p<target&&exp<15){p<<=1;exp++;}return (Byte)(exp==0?0:exp-1);}
 static Byte SpeedId(UsbSpeed s)=>s==UsbSpeed.Full?(Byte)1:s==UsbSpeed.Low?(Byte)2:s==UsbSpeed.High?(Byte)3:s==UsbSpeed.Super?(Byte)4:s==UsbSpeed.SuperPlus?(Byte)5:(Byte)0;static UsbSpeed SpeedFromId(Byte s)=>s==1?UsbSpeed.Full:s==2?UsbSpeed.Low:s==3?UsbSpeed.High:s==4?UsbSpeed.Super:s==5?UsbSpeed.SuperPlus:UsbSpeed.Unknown;static UInt16 DefaultEp0(Byte s)=>s>=4?(UInt16)512:s==3?(UInt16)64:(UInt16)8;
 static UInt64 Port(Controller* c,Byte p)=>c->Operational+0x400UL+(UInt64)(p-1)*0x10UL;static Boolean Page(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a);static Boolean Buffer(UInt32 bytes,out KernelPhysicalAllocation a,out Byte* p){a=default;p=null;UInt64 pages=((UInt64)bytes+4095UL)/4096UL;if(!KernelPhysicalMemory.TryAllocate(pages,1,out a))return false;p=Direct(a);Zero(a);return true;}static Byte* Direct(KernelPhysicalAllocation a)=>(Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress);static void Zero(KernelPhysicalAllocation a){if(a.Token==0)return;Clear(Direct(a),a.PageCount*4096UL);}static Boolean Release(KernelPhysicalAllocation a)=>a.Token==0||KernelPhysicalMemory.TryRelease(a);
 static Boolean Wait32(UInt64 a,UInt32 mask,UInt32 expected){for(UInt32 i=0;i<SpinLimit;i++)if((R32(a)&mask)==expected)return true;return false;}static Byte R8(UInt64 a)=>*(Byte*)(nuint)a;static UInt32 R32(UInt64 a)=>*(UInt32*)(nuint)a;static void W32(UInt64 a,UInt32 v)=>*(UInt32*)(nuint)a=v;static void W64(UInt64 a,UInt64 v)=>*(UInt64*)(nuint)a=v;static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;}static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];}
}
