using System;
using NovaOryn.Bus.Usb;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Storage;
namespace NovaOryn.Usb.MassStorage;
public readonly struct UsbMassStorageCapabilities{public UsbMassStorageCapabilities(Boolean initialized,UInt32 devices,UInt64 commands){Initialized=initialized;Devices=devices;Commands=commands;}public Boolean Initialized{get;}public UInt32 Devices{get;}public UInt64 Commands{get;}}
public static unsafe class UsbMassStorage
{
 private struct Rec{internal Byte Used,Device,InEp,OutEp,Lun;internal UInt32 BlockSize;internal UInt64 Blocks;internal UInt32 Tag;internal UInt32 Generic;internal UInt32 Storage;}
 private const Int32 Max=32;private static Rec* _r;private static NovaOryn.Kernel.Heap.KernelHeapAllocation _a;private static Boolean _initialized;private static UInt32 _devices;private static UInt64 _commands;
 public static Boolean Initialize(){if(_initialized)return true;if(!NovaOryn.Kernel.Heap.KernelHeap.TryAllocate((UInt64)Max*(UInt64)sizeof(Rec),64,true,out _a))return false;_r=(Rec*)(nuint)_a.Address;_initialized=true;return Discover();}
 public static Boolean Discover(){if(!_initialized)return false;for(UInt32 i=0;i<KernelUsbBus.GetInterfaceCount();i++){if(!KernelUsbBus.TryGetInterface(i,out UsbInterfaceInfo inf)||inf.Descriptor.Class!=(Byte)UsbClassCode.MassStorage||inf.Descriptor.Protocol!=0x50)continue;if(Find(inf.Device)>=0)continue;Byte ine=0,oute=0;for(UInt32 e=0;e<4;e++)if(inf.TryGetEndpoint(e,out UsbEndpointDescriptor ep)&&ep.TransferType==UsbTransferType.Bulk){if(ep.In)ine=ep.Address;else oute=ep.Address;}if(ine==0||oute==0)continue;Int32 s=Free();if(s<0)return false;Rec* r=_r+s;r->Used=1;r->Device=(Byte)inf.Device.Value;r->InEp=ine;r->OutEp=oute;r->Tag=1;if(KernelUsbBus.TryGetDevice(inf.Device,out UsbDeviceInfo di))r->Generic=di.Device.Value;UsbSetupPacket maxLun=new(0xA1,0xFE,0,inf.Descriptor.Number,1);Byte lun=0;if(KernelUsbBus.ControlTransfer(inf.Device,maxLun,&lun,1,out UInt32 got)&&got==1)r->Lun=lun;if(!ReadCapacity(r)){r->Used=0;continue;}KernelStorageGeometry g=new(r->BlockSize,r->BlockSize,r->Blocks,false,true);KernelContextualBlockDeviceCallbacks cb=new(&ReadBlocks,&WriteBlocks,&Flush);if(!KernelStorage.RegisterBlockDevice(new KernelDeviceHandle(r->Generic),KernelStorageDeviceKind.UsbMassStorage,g,cb,out KernelStorageDeviceHandle sh)){r->Used=0;continue;}r->Storage=sh.Value;_devices++;}return true;}
 public static UsbMassStorageCapabilities GetCapabilities()=>new(_initialized,_devices,_commands);
 private static Boolean ReadCapacity(Rec* r){Byte* data=stackalloc Byte[8];Byte* cdb=stackalloc Byte[10];Zero(cdb,10);cdb[0]=0x25;if(!Bot(r,cdb,10,data,8,true))return false;UInt32 last=BE32(data),size=BE32(data+4);if(size<512||size>65536)return false;r->BlockSize=size;r->Blocks=(UInt64)last+1;return true;}
 private static Boolean ReadBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes){Rec* r=ByGeneric(device);if(r==null||count==0||lba>UInt32.MaxValue||count>UInt32.MaxValue-(UInt32)lba||bytes<(UInt64)count*r->BlockSize)return false;Byte* c=stackalloc Byte[10];for(UInt32 i=0;i<count;i++){Zero(c,10);c[0]=0x28;WBE32(c+2,(UInt32)lba+i);WBE16(c+7,1);if(!Bot(r,c,10,buffer+(UInt64)i*r->BlockSize,r->BlockSize,true))return false;}return true;}
 private static Boolean WriteBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes){Rec* r=ByGeneric(device);if(r==null||count==0||lba>UInt32.MaxValue||count>UInt32.MaxValue-(UInt32)lba||bytes<(UInt64)count*r->BlockSize)return false;Byte* c=stackalloc Byte[10];for(UInt32 i=0;i<count;i++){Zero(c,10);c[0]=0x2A;WBE32(c+2,(UInt32)lba+i);WBE16(c+7,1);if(!Bot(r,c,10,buffer+(UInt64)i*r->BlockSize,r->BlockSize,false))return false;}return true;}
 private static Boolean Flush(KernelDeviceHandle device){Rec* r=ByGeneric(device);if(r==null)return false;Byte* c=stackalloc Byte[10];Zero(c,10);c[0]=0x35;return Bot(r,c,10,null,0,false);}
 private static Boolean Bot(Rec* r,Byte* cdb,Byte cdbLen,Byte* data,UInt32 dataLen,Boolean input){Byte* cbw=stackalloc Byte[31];Zero(cbw,31);cbw[0]=0x55;cbw[1]=0x53;cbw[2]=0x42;cbw[3]=0x43;UInt32 tag=r->Tag++;WLE32(cbw+4,tag);WLE32(cbw+8,dataLen);cbw[12]=input?(Byte)0x80:(Byte)0;cbw[13]=r->Lun;cbw[14]=cdbLen;for(Byte i=0;i<cdbLen;i++)cbw[15+i]=cdb[i];if(!KernelUsbBus.BulkTransfer(new UsbDeviceHandle(r->Device),r->OutEp,cbw,31,out UInt32 x)||x!=31)return false;if(dataLen!=0){Byte ep=input?r->InEp:r->OutEp;if(!KernelUsbBus.BulkTransfer(new UsbDeviceHandle(r->Device),ep,data,dataLen,out x)||x!=dataLen)return false;}Byte* csw=stackalloc Byte[13];if(!KernelUsbBus.BulkTransfer(new UsbDeviceHandle(r->Device),r->InEp,csw,13,out x)||x!=13||csw[0]!=0x55||csw[1]!=0x53||csw[2]!=0x42||csw[3]!=0x53||LE32(csw+4)!=tag||csw[12]!=0)return false;_commands++;return true;}
 private static Rec* ByGeneric(KernelDeviceHandle h){for(Int32 i=0;i<Max;i++)if((_r+i)->Used!=0&&(_r+i)->Generic==h.Value)return _r+i;return null;}private static Int32 Find(UsbDeviceHandle d){for(Int32 i=0;i<Max;i++)if((_r+i)->Used!=0&&(_r+i)->Device==(Byte)d.Value)return i;return -1;}private static Int32 Free(){for(Int32 i=0;i<Max;i++)if((_r+i)->Used==0)return i;return -1;}private static void Zero(Byte* p,UInt32 n){for(UInt32 i=0;i<n;i++)p[i]=0;}private static UInt32 BE32(Byte* p)=>(UInt32)p[3]|((UInt32)p[2]<<8)|((UInt32)p[1]<<16)|((UInt32)p[0]<<24);private static UInt32 LE32(Byte* p)=>(UInt32)p[0]|((UInt32)p[1]<<8)|((UInt32)p[2]<<16)|((UInt32)p[3]<<24);private static void WBE16(Byte* p,UInt16 v){p[0]=(Byte)(v>>8);p[1]=(Byte)v;}private static void WBE32(Byte* p,UInt32 v){p[0]=(Byte)(v>>24);p[1]=(Byte)(v>>16);p[2]=(Byte)(v>>8);p[3]=(Byte)v;}private static void WLE32(Byte* p,UInt32 v){p[0]=(Byte)v;p[1]=(Byte)(v>>8);p[2]=(Byte)(v>>16);p[3]=(Byte)(v>>24);}
}
