<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
    <RuntimeMetadataVersion>v4.0.30319</RuntimeMetadataVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <AssemblyName>NovaOryn.Kernel.Entry.X64</AssemblyName>
    <NovaOrynSystemModule>NovaOryn.Freestanding.CoreLib</NovaOrynSystemModule>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NovaOryn.Freestanding.CoreLib\NovaOryn.Freestanding.CoreLib.csproj" />
    <ProjectReference Include="..\NovaOryn.Kernel.Console\NovaOryn.Kernel.Console.csproj" />
    <ProjectReference Include="..\..\$safeprojectname$.csproj" />
      <ProjectReference Include="..\NovaOryn.Kernel.Heap\NovaOryn.Kernel.Heap.csproj" />
  </ItemGroup>
</Project>
