using System;
using NovaOryn.Kernel.Heap;

namespace NovaOryn.Kernel.Storage;

/// <summary>Provides heap-backed block-I/O request queueing above synchronous device callbacks.</summary>
public static unsafe class KernelStorageQueue
{
    private struct RequestRecord { internal Byte Used,State,Operation; internal UInt32 Device,BlockCount,BufferBytes; internal UInt64 FirstBlock,BufferAddress,Cookie; }
    private static RequestRecord* _requests;private static KernelHeapAllocation _allocation;private static UInt32 _capacity,_maximum,_count;private static KernelStorageRegistryMode _mode;private static Boolean _initialized;
    public static UInt32 Count=>_count;public static UInt32 Capacity=>_capacity;
    internal static Boolean Initialize(KernelStorageOptions options){if(_initialized)return true;_mode=options.RegistryMode;_maximum=options.MaximumRequests;if(!KernelHeap.TryAllocate((UInt64)options.InitialRequests*(UInt64)sizeof(RequestRecord),64,true,out _allocation))return false;_requests=(RequestRecord*)(nuint)_allocation.Address;_capacity=options.InitialRequests;_initialized=true;return true;}
    public static Boolean Enqueue(KernelBlockRequest request,out KernelStorageRequestHandle handle){handle=default;if(!_initialized||request.Device.Value==0||request.Operation==0)return false;if(request.Operation!=KernelBlockOperation.Flush&&(request.BlockCount==0||request.BufferAddress==0||request.BufferBytes==0))return false;Int32 slot=Free();if(slot<0){if(!Grow())return false;slot=Free();if(slot<0)return false;}RequestRecord* r=_requests+slot;r->Used=1;r->State=(Byte)KernelStorageRequestState.Pending;r->Operation=(Byte)request.Operation;r->Device=request.Device.Value;r->FirstBlock=request.FirstBlock;r->BlockCount=request.BlockCount;r->BufferAddress=request.BufferAddress;r->BufferBytes=request.BufferBytes;r->Cookie=request.Cookie;_count++;handle=new KernelStorageRequestHandle((UInt32)slot+1U);return true;}
    public static Boolean ProcessNext(KernelStorageDeviceHandle device,out KernelStorageRequestHandle handle){handle=default;if(!_initialized||device.Value==0)return false;for(Int32 i=0;i<(Int32)_capacity;i++){RequestRecord* r=_requests+i;if(r->Used==0||r->State!=(Byte)KernelStorageRequestState.Pending||r->Device!=device.Value)continue;handle=new KernelStorageRequestHandle((UInt32)i+1U);return Process(handle);}return false;}
    public static Boolean Process(KernelStorageRequestHandle handle){if(!Try(handle,out RequestRecord* r)||r->State!=(Byte)KernelStorageRequestState.Pending)return false;KernelStorageDeviceHandle device=new(r->Device);Boolean ok=r->Operation==(Byte)KernelBlockOperation.Read?KernelStorage.ReadBlocks(device,r->FirstBlock,r->BlockCount,(Byte*)(nuint)r->BufferAddress,r->BufferBytes):r->Operation==(Byte)KernelBlockOperation.Write?KernelStorage.WriteBlocks(device,r->FirstBlock,r->BlockCount,(Byte*)(nuint)r->BufferAddress,r->BufferBytes):KernelStorage.Flush(device);r->State=(Byte)(ok?KernelStorageRequestState.Completed:KernelStorageRequestState.Failed);return ok;}
    public static Boolean TryGet(KernelStorageRequestHandle handle,out KernelStorageRequestInfo info){info=default;if(!Try(handle,out RequestRecord* r))return false;KernelBlockRequest request=new(new KernelStorageDeviceHandle(r->Device),(KernelBlockOperation)r->Operation,r->FirstBlock,r->BlockCount,r->BufferAddress,r->BufferBytes,r->Cookie);info=new KernelStorageRequestInfo(handle,(KernelStorageRequestState)r->State,request);return true;}
    public static Boolean Release(KernelStorageRequestHandle handle){if(!Try(handle,out RequestRecord* r)||r->State==(Byte)KernelStorageRequestState.Pending)return false;Clear((Byte*)r,sizeof(RequestRecord));_count--;return true;}
    private static Boolean Try(KernelStorageRequestHandle h,out RequestRecord* r){r=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_capacity||(_requests+i)->Used==0)return false;r=_requests+i;return true;}
    private static Int32 Free(){for(Int32 i=0;i<(Int32)_capacity;i++)if((_requests+i)->Used==0)return i;return -1;}
    private static Boolean Grow(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_capacity,_maximum);if(next<=_capacity)return false;if(!KernelHeap.TryAllocate((UInt64)next*(UInt64)sizeof(RequestRecord),64,true,out KernelHeapAllocation allocation))return false;RequestRecord* table=(RequestRecord*)(nuint)allocation.Address;Copy((Byte*)_requests,(Byte*)table,(UInt64)_capacity*(UInt64)sizeof(RequestRecord));KernelHeapAllocation old=_allocation;_allocation=allocation;_requests=table;_capacity=next;return KernelHeap.TryRelease(old);}
    private static void Clear(Byte* p,Int32 n){for(Int32 i=0;i<n;i++)p[i]=0;}private static void Copy(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
