using System;
using NovaOryn.Kernel.Heap;

namespace NovaOryn.Kernel.Storage;

/// <summary>Virtual filesystem namespaces, filesystem providers, mount points, and open-file dispatch.</summary>
public static unsafe class KernelVfs
{
    private struct ProviderRecord { internal Byte Used,Type; internal UInt64 Probe,Mount,Unmount,Open,Read,Write,Flush,Close; }
    private struct NamespaceRecord { internal Byte Used; }
    private struct MountRecord { internal Byte Used; internal UInt32 Namespace,Volume,Provider,PathLength; internal UInt64 PathHash,MountCookie; }
    private struct FileRecord { internal Byte Used,Type,Access; internal UInt32 Provider,Mount; internal UInt64 Cookie,Position,Length; }
    private static ProviderRecord* _providers;private static NamespaceRecord* _namespaces;private static MountRecord* _mounts;private static FileRecord* _files;
    private static KernelHeapAllocation _providerAllocation,_namespaceAllocation,_mountAllocation,_fileAllocation;
    private static UInt32 _providerCapacity,_namespaceCapacity,_mountCapacity,_fileCapacity,_providerCount,_namespaceCount,_mountCount,_openFileCount,_maximumProviders,_maximumNamespaces,_maximumMounts,_maximumOpenFiles;private static KernelStorageRegistryMode _mode;private static Boolean _initialized;
    public static UInt32 MountCount=>_mountCount; public static UInt32 OpenFileCount=>_openFileCount; public static UInt32 MountCapacity=>_mountCapacity; public static UInt32 OpenFileCapacity=>_fileCapacity;
    public static KernelMountNamespaceHandle DefaultNamespace=>new(1U);

    internal static Boolean Initialize(KernelStorageOptions options)
    { if(_initialized)return true;_mode=options.RegistryMode;_providerCapacity=options.InitialProviders;_namespaceCapacity=options.InitialNamespaces;_maximumProviders=options.MaximumProviders;_maximumNamespaces=options.MaximumNamespaces;_maximumMounts=options.MaximumMounts;_maximumOpenFiles=options.MaximumOpenFiles;if(!AllocProviders(_providerCapacity,out _providerAllocation,out _providers)||!AllocNamespaces(_namespaceCapacity,out _namespaceAllocation,out _namespaces)||!AllocMounts(options.InitialMounts,out _mountAllocation,out _mounts)||!AllocFiles(options.InitialOpenFiles,out _fileAllocation,out _files))return false;_mountCapacity=options.InitialMounts;_fileCapacity=options.InitialOpenFiles;_namespaces->Used=1;_namespaceCount=1;_initialized=true;return true; }
    public static Boolean IsInitialized()=>_initialized;
    public static Boolean CreateNamespace(out KernelMountNamespaceHandle handle)
    { handle=default;if(!_initialized)return false;Int32 slot=FreeNamespace();if(slot<0){if(!GrowNamespaces())return false;slot=FreeNamespace();}(_namespaces+slot)->Used=1;_namespaceCount++;handle=new KernelMountNamespaceHandle((UInt32)slot+1U);return true; }
    public static Boolean RegisterFileSystem(KernelFileSystemType type,KernelFileSystemCallbacks callbacks)
    { if(!_initialized||type==KernelFileSystemType.Unknown||callbacks.Probe==null||callbacks.Mount==null||callbacks.Unmount==null||callbacks.Open==null||callbacks.Read==null||callbacks.Close==null)return false;for(Int32 i=0;i<(Int32)_providerCapacity;i++)if((_providers+i)->Used!=0&&(_providers+i)->Type==(Byte)type)return false;Int32 slot=FreeProvider();if(slot<0){if(!GrowProviders())return false;slot=FreeProvider();}ProviderRecord* p=_providers+slot;p->Used=1;p->Type=(Byte)type;p->Probe=(UInt64)(void*)callbacks.Probe;p->Mount=(UInt64)(void*)callbacks.Mount;p->Unmount=(UInt64)(void*)callbacks.Unmount;p->Open=(UInt64)(void*)callbacks.Open;p->Read=(UInt64)(void*)callbacks.Read;p->Write=(UInt64)(void*)callbacks.Write;p->Flush=(UInt64)(void*)callbacks.Flush;p->Close=(UInt64)(void*)callbacks.Close;_providerCount++;return true; }
    public static Boolean Mount(KernelMountNamespaceHandle ns,KernelStorageVolumeHandle volume,KernelFileSystemType type,String path,out KernelMountHandle handle)
    { handle=default;if(!TryNamespace(ns)||volume.Value==0||path==null||path.Length<1||path[0]!='/')return false;Int32 provider=FindProvider(type);if(provider<0)return false;ProviderRecord* p=_providers+provider;delegate*<KernelStorageVolumeHandle,Boolean> probe=(delegate*<KernelStorageVolumeHandle,Boolean>)(void*)p->Probe;if(!probe(volume))return false;UInt64 cookie=0;delegate*<KernelStorageVolumeHandle,UInt64*,Boolean> mount=(delegate*<KernelStorageVolumeHandle,UInt64*,Boolean>)(void*)p->Mount;if(!mount(volume,&cookie))return false;Int32 slot=FreeMount();if(slot<0){if(!GrowMounts())return false;slot=FreeMount();}MountRecord* m=_mounts+slot;m->Used=1;m->Namespace=ns.Value;m->Volume=volume.Value;m->Provider=(UInt32)provider+1U;m->PathLength=(UInt32)NormalizeMountLength(path);m->PathHash=HashPrefix(path,m->PathLength);m->MountCookie=cookie;_mountCount++;handle=new KernelMountHandle((UInt32)slot+1U);return true; }
    public static Boolean Unmount(KernelMountHandle handle)
    { Int32 i=(Int32)handle.Value-1;if(!_initialized||i<0||(UInt32)i>=_mountCapacity||(_mounts+i)->Used==0)return false;for(Int32 f=0;f<(Int32)_fileCapacity;f++)if((_files+f)->Used!=0&&(_files+f)->Mount==handle.Value)return false;MountRecord* m=_mounts+i;ProviderRecord* p=_providers+(Int32)m->Provider-1;delegate*<UInt64,Boolean> unmount=(delegate*<UInt64,Boolean>)(void*)p->Unmount;if(!unmount(m->MountCookie))return false;Clear((Byte*)m,sizeof(MountRecord));_mountCount--;return true; }
    public static Boolean Open(KernelMountNamespaceHandle ns,String path,KernelFileAccess access,out KernelFileHandle handle)
    { handle=default;if(!TryNamespace(ns)||path==null||path.Length<1||path[0]!='/')return false;Int32 mount=FindMount(ns,path);if(mount<0)return false;MountRecord* m=_mounts+mount;ProviderRecord* p=_providers+(Int32)m->Provider-1;UInt64 cookie=0,length=0;KernelFileType type=KernelFileType.Unknown;delegate*<UInt64,String,UInt32,KernelFileAccess,UInt64*,KernelFileType*,UInt64*,Boolean> open=(delegate*<UInt64,String,UInt32,KernelFileAccess,UInt64*,KernelFileType*,UInt64*,Boolean>)(void*)p->Open;if(!open(m->MountCookie,path,m->PathLength,access,&cookie,&type,&length))return false;Int32 slot=FreeFile();if(slot<0){if(!GrowFiles()){delegate*<UInt64,Boolean> close=(delegate*<UInt64,Boolean>)(void*)p->Close;close(cookie);return false;}slot=FreeFile();}FileRecord* f=_files+slot;f->Used=1;f->Type=(Byte)type;f->Access=(Byte)access;f->Provider=m->Provider;f->Mount=(UInt32)mount+1U;f->Cookie=cookie;f->Length=length;f->Position=0;_openFileCount++;handle=new KernelFileHandle((UInt32)slot+1U);return true; }
    public static Boolean Read(KernelFileHandle handle,Byte* buffer,UInt32 bytesToRead,out UInt32 bytesRead)
    { bytesRead=0;if(!TryFile(handle,out FileRecord* f)||buffer==null||bytesToRead==0||(f->Access!=(Byte)KernelFileAccess.Read&&f->Access!=(Byte)KernelFileAccess.ReadWrite))return false;ProviderRecord* p=_providers+(Int32)f->Provider-1;delegate*<UInt64,UInt64,Byte*,UInt32,UInt32*,Boolean> read=(delegate*<UInt64,UInt64,Byte*,UInt32,UInt32*,Boolean>)(void*)p->Read;UInt32 readCount=0;if(!read(f->Cookie,f->Position,buffer,bytesToRead,&readCount))return false;bytesRead=readCount;f->Position+=readCount;return true; }
    public static Boolean Write(KernelFileHandle handle,Byte* buffer,UInt32 bytesToWrite,out UInt32 bytesWritten)
    { bytesWritten=0;if(!TryFile(handle,out FileRecord* f)||buffer==null||bytesToWrite==0||(f->Access!=(Byte)KernelFileAccess.Write&&f->Access!=(Byte)KernelFileAccess.ReadWrite))return false;ProviderRecord* p=_providers+(Int32)f->Provider-1;if(p->Write==0)return false;delegate*<UInt64,UInt64,Byte*,UInt32,UInt32*,Boolean> write=(delegate*<UInt64,UInt64,Byte*,UInt32,UInt32*,Boolean>)(void*)p->Write;UInt32 writeCount=0;if(!write(f->Cookie,f->Position,buffer,bytesToWrite,&writeCount))return false;bytesWritten=writeCount;f->Position+=writeCount;if(f->Position>f->Length)f->Length=f->Position;return true; }
    public static Boolean Seek(KernelFileHandle handle,Int64 offset,KernelSeekOrigin origin,out UInt64 position)
    { position=0;if(!TryFile(handle,out FileRecord* f))return false;UInt64 basis=origin==KernelSeekOrigin.Begin?0UL:origin==KernelSeekOrigin.Current?f->Position:f->Length;if(offset<0){UInt64 amount=(UInt64)(-offset);if(amount>basis)return false;position=basis-amount;}else{UInt64 amount=(UInt64)offset;if(UInt64.MaxValue-basis<amount)return false;position=basis+amount;}f->Position=position;return true; }
    public static Boolean Flush(KernelFileHandle handle)
    { if(!TryFile(handle,out FileRecord* f))return false;ProviderRecord* p=_providers+(Int32)f->Provider-1;if(p->Flush==0)return true;delegate*<UInt64,Boolean> flush=(delegate*<UInt64,Boolean>)(void*)p->Flush;return flush(f->Cookie); }
    public static Boolean Close(KernelFileHandle handle)
    { if(!TryFile(handle,out FileRecord* f))return false;ProviderRecord* p=_providers+(Int32)f->Provider-1;delegate*<UInt64,Boolean> close=(delegate*<UInt64,Boolean>)(void*)p->Close;if(!close(f->Cookie))return false;Clear((Byte*)f,sizeof(FileRecord));_openFileCount--;return true; }
    public static Boolean TryGetFileInfo(KernelFileHandle handle,out KernelVfsFileInfo info){info=default;if(!TryFile(handle,out FileRecord* f))return false;info=new KernelVfsFileInfo(handle,(KernelFileType)f->Type,f->Length,f->Position,(KernelFileAccess)f->Access);return true;}
    private static Int32 FindProvider(KernelFileSystemType type){for(Int32 i=0;i<(Int32)_providerCapacity;i++)if((_providers+i)->Used!=0&&(_providers+i)->Type==(Byte)type)return i;return -1;}
    private static Int32 FindMount(KernelMountNamespaceHandle ns,String path){Int32 best=-1;UInt32 bestLength=0;for(Int32 i=0;i<(Int32)_mountCapacity;i++){MountRecord* m=_mounts+i;if(m->Used==0||m->Namespace!=ns.Value||m->PathLength>(UInt32)path.Length||m->PathLength<bestLength)continue;if(HashPrefix(path,m->PathLength)!=m->PathHash)continue;if(m->PathLength>1&&path.Length>m->PathLength&&path[(Int32)m->PathLength]!='/')continue;best=i;bestLength=m->PathLength;}return best;}
    private static Int32 NormalizeMountLength(String path){Int32 n=path.Length;while(n>1&&path[n-1]=='/')n--;return n;}
    private static UInt64 HashPrefix(String path,UInt32 length){UInt64 h=1469598103934665603UL;for(UInt32 i=0;i<length;i++){Char c=path[(Int32)i];if(c>='A'&&c<='Z')c=(Char)(c+32);h^=(UInt64)c;h*=1099511628211UL;}return h;}
    private static Boolean TryNamespace(KernelMountNamespaceHandle h){Int32 i=(Int32)h.Value-1;return _initialized&&i>=0&&(UInt32)i<_namespaceCapacity&&(_namespaces+i)->Used!=0;}
    private static Boolean TryFile(KernelFileHandle h,out FileRecord* f){f=null;Int32 i=(Int32)h.Value-1;if(!_initialized||i<0||(UInt32)i>=_fileCapacity||(_files+i)->Used==0)return false;f=_files+i;return true;}
    private static Int32 FreeProvider(){for(Int32 i=0;i<(Int32)_providerCapacity;i++)if((_providers+i)->Used==0)return i;return -1;}private static Int32 FreeNamespace(){for(Int32 i=0;i<(Int32)_namespaceCapacity;i++)if((_namespaces+i)->Used==0)return i;return -1;}private static Int32 FreeMount(){for(Int32 i=0;i<(Int32)_mountCapacity;i++)if((_mounts+i)->Used==0)return i;return -1;}private static Int32 FreeFile(){for(Int32 i=0;i<(Int32)_fileCapacity;i++)if((_files+i)->Used==0)return i;return -1;}
    private static Boolean GrowProviders(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_providerCapacity,_maximumProviders);if(!AllocProviders(next,out KernelHeapAllocation a,out ProviderRecord* n))return false;Copy((Byte*)_providers,(Byte*)n,(UInt64)_providerCapacity*(UInt64)sizeof(ProviderRecord));KernelHeapAllocation old=_providerAllocation;_providerAllocation=a;_providers=n;_providerCapacity=next;return KernelHeap.TryRelease(old);}private static Boolean GrowNamespaces(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_namespaceCapacity,_maximumNamespaces);if(!AllocNamespaces(next,out KernelHeapAllocation a,out NamespaceRecord* n))return false;Copy((Byte*)_namespaces,(Byte*)n,(UInt64)_namespaceCapacity*(UInt64)sizeof(NamespaceRecord));KernelHeapAllocation old=_namespaceAllocation;_namespaceAllocation=a;_namespaces=n;_namespaceCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean GrowMounts(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_mountCapacity,_maximumMounts);if(next<=_mountCapacity||!AllocMounts(next,out KernelHeapAllocation a,out MountRecord* n))return false;Copy((Byte*)_mounts,(Byte*)n,(UInt64)_mountCapacity*(UInt64)sizeof(MountRecord));KernelHeapAllocation old=_mountAllocation;_mountAllocation=a;_mounts=n;_mountCapacity=next;return KernelHeap.TryRelease(old);}private static Boolean GrowFiles(){if(_mode!=KernelStorageRegistryMode.Dynamic)return false;UInt32 next=KernelStorageMath.NextCapacity(_fileCapacity,_maximumOpenFiles);if(next<=_fileCapacity||!AllocFiles(next,out KernelHeapAllocation a,out FileRecord* n))return false;Copy((Byte*)_files,(Byte*)n,(UInt64)_fileCapacity*(UInt64)sizeof(FileRecord));KernelHeapAllocation old=_fileAllocation;_fileAllocation=a;_files=n;_fileCapacity=next;return KernelHeap.TryRelease(old);}
    private static Boolean AllocProviders(UInt32 n,out KernelHeapAllocation a,out ProviderRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)n*(UInt64)sizeof(ProviderRecord),64,true,out a))return false;p=(ProviderRecord*)(nuint)a.Address;return true;}private static Boolean AllocNamespaces(UInt32 n,out KernelHeapAllocation a,out NamespaceRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)n*(UInt64)sizeof(NamespaceRecord),64,true,out a))return false;p=(NamespaceRecord*)(nuint)a.Address;return true;}private static Boolean AllocMounts(UInt32 n,out KernelHeapAllocation a,out MountRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)n*(UInt64)sizeof(MountRecord),64,true,out a))return false;p=(MountRecord*)(nuint)a.Address;return true;}private static Boolean AllocFiles(UInt32 n,out KernelHeapAllocation a,out FileRecord* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)n*(UInt64)sizeof(FileRecord),64,true,out a))return false;p=(FileRecord*)(nuint)a.Address;return true;}
    private static void Clear(Byte* p,Int32 n){for(Int32 i=0;i<n;i++)p[i]=0;}private static void Copy(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
