using System;
using NovaOryn.Kernel.AddressSpace;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Memory;
using NovaOryn.Kernel.Heap;
using NovaOryn.Kernel.Pci;
using NovaOryn.Kernel.Storage;
namespace NovaOryn.Kernel.Nvme;
/// <summary>PCI NVMe 1.x controller driver with admin/I/O queues, namespace discovery and synchronous block I/O.</summary>
public static unsafe class KernelNvme
{
 const UInt16 RequestedAdminEntries=32,RequestedIoEntries=64; const UInt32 SpinLimit=40000000U;
 struct Controller { internal Byte Used,State,DbStride,InterruptMode,AdminPhase,IoPhase; internal UInt16 Segment,AdminTail,AdminHead,AdminCid,IoTail,IoHead,IoCid,AdminEntries,IoEntries; internal Byte Bus,Device,Function; internal UInt32 DeviceHandle,Version,NamespaceCount; internal UInt64 Mmio; internal KernelPhysicalAllocation Asq,Acq,IoSq,IoCq,Identify; }
 struct Namespace { internal Byte Used; internal UInt32 Controller,Nsid,BlockSize,DeviceHandle,StorageHandle; internal UInt64 Blocks; }
 static Controller* _controllers; static Namespace* _namespaces; static KernelHeapAllocation _controllerAllocation,_namespaceAllocation; static UInt32 _controllerCapacity,_namespaceCapacity,_controllerCount,_namespaceCount; static Boolean _initialized;
 /// <summary>Discovers class 01/08/02 PCI functions and initializes every usable NVMe controller.</summary>
 public static Boolean Initialize(){if(_initialized)return true;if(!KernelPci.IsInitialized()||!KernelStorage.IsInitialized()||!KernelPhysicalMemory.IsInitialized()||!KernelAddressSpace.IsInitialized())return false;if(!AllocateTables())return false;UInt32 n=KernelPci.GetDeviceCount();for(UInt32 i=0;i<n;i++){if(!KernelPci.TryGetDevice(i,out PciDeviceInfo p)||!NvmeMath.IsNvmeClass(p.ClassCode))continue;if(_controllerCount==_controllerCapacity&&!GrowControllers())return false;TryStartController(p);} _initialized=true;return true;}
 public static Boolean IsInitialized()=>_initialized; public static NvmeCapabilities GetCapabilities()=>new(_initialized,_controllerCount,_namespaceCount);
 public static Boolean TryGetController(UInt32 index,out NvmeControllerInfo info){info=default;if(index>=_controllerCount)return false;Controller* c=_controllers+index;if(c->Used==0)return false;info=new NvmeControllerInfo(new PciLocation(c->Segment,c->Bus,c->Device,c->Function),new KernelDeviceHandle(c->DeviceHandle),(NvmeControllerState)c->State,(NvmeInterruptMode)c->InterruptMode,c->AdminEntries,c->IoEntries,c->NamespaceCount,c->Version);return true;}
 public static Boolean TryGetNamespace(UInt32 index,out NvmeNamespaceInfo info){info=default;if(index>=_namespaceCount)return false;Namespace* n=_namespaces+index;if(n->Used==0)return false;info=new NvmeNamespaceInfo(n->Controller,n->Nsid,n->BlockSize,n->Blocks,new KernelDeviceHandle(n->DeviceHandle),new KernelStorageDeviceHandle(n->StorageHandle));return true;}
 static Boolean TryStartController(PciDeviceInfo pci){if(!KernelPci.TryMapBar(pci.Location,0,out PciBarInfo bar,out UInt64 mmio)||bar.Type==PciBarType.Io||bar.Length<0x2000UL)return false;if(!KernelPci.TryRead16(pci.Location,4,out UInt16 cmd)||!KernelPci.TryWrite16(pci.Location,4,(UInt16)(cmd|0x0006U)))return false;Controller* c=_controllers+_controllerCount;Clear((Byte*)c,(UInt64)sizeof(Controller));c->Used=1;c->State=(Byte)NvmeControllerState.Disabled;c->Segment=pci.Location.Segment;c->Bus=pci.Location.Bus;c->Device=pci.Location.Device;c->Function=pci.Location.Function;c->DeviceHandle=pci.DeviceHandle.Value;c->Mmio=mmio;UInt64 cap=R64(mmio,0);UInt32 maximumEntries=(UInt32)(cap&0xFFFFUL)+1U;if(maximumEntries<2U||(cap&(1UL<<37))==0)return Fail(c);c->AdminEntries=(UInt16)(maximumEntries<RequestedAdminEntries?maximumEntries:RequestedAdminEntries);c->IoEntries=(UInt16)(maximumEntries<RequestedIoEntries?maximumEntries:RequestedIoEntries);c->DbStride=(Byte)((cap>>32)&15UL);c->Version=R32(mmio,8);if(((cap>>48)&15UL)!=0UL)return Fail(c);W32(mmio,0x14,0);if(!WaitReady(c,false))return Fail(c);if(!AllocPage(out c->Asq)||!AllocPage(out c->Acq)||!AllocPage(out c->Identify))return Fail(c);Zero(c->Asq);Zero(c->Acq);Zero(c->Identify);W32(mmio,0x24,((UInt32)(c->AdminEntries-1U)<<16)|(UInt32)(c->AdminEntries-1U));W64(mmio,0x28,c->Asq.StartAddress);W64(mmio,0x30,c->Acq.StartAddress);W32(mmio,0x14,(6U<<16)|(4U<<20)|1U);if(!WaitReady(c,true))return Fail(c);c->State=(Byte)NvmeControllerState.Ready;c->InterruptMode=(Byte)NvmeInterruptMode.Synchronous;c->AdminPhase=1;c->IoPhase=1;if(!AdminIdentify(c,0,1,c->Identify.StartAddress))return Fail(c);Byte* id=Direct(c->Identify);UInt32 nn=*(UInt32*)(id+516);if(!CreateIoQueues(c))return Fail(c);UInt32 controllerIndex=_controllerCount++;if(!DiscoverActiveNamespaces(controllerIndex,c,nn))return Fail(c);return true;}
 static Boolean CreateIoQueues(Controller* c){if(!AllocPage(out c->IoSq)||!AllocPage(out c->IoCq))return false;Zero(c->IoSq);Zero(c->IoCq);if(!AdminCreateCq(c,1,c->IoEntries,c->IoCq.StartAddress))return false;if(!AdminCreateSq(c,1,c->IoEntries,c->IoSq.StartAddress,1))return false;return true;}
 static Boolean DiscoverActiveNamespaces(UInt32 ci,Controller* c,UInt32 nn){UInt32 start=0;for(;;){Zero(c->Identify);if(!AdminIdentify(c,start,2,c->Identify.StartAddress)){if(start!=0)return false;for(UInt32 nsid=1;nsid<=nn;nsid++)DiscoverNamespace(ci,c,nsid);return true;}UInt32* ids=(UInt32*)Direct(c->Identify);UInt32 last=start;Boolean full=true;for(UInt32 i=0;i<1024U;i++){UInt32 nsid=ids[i];if(nsid==0){full=false;break;}if(nsid<=last)return false;last=nsid;DiscoverNamespace(ci,c,nsid);}if(!full)return true;start=last;}}
 static Boolean DiscoverNamespace(UInt32 ci,Controller* c,UInt32 nsid){Zero(c->Identify);if(!AdminIdentify(c,nsid,0,c->Identify.StartAddress))return false;Byte* d=Direct(c->Identify);UInt64 nsze=*(UInt64*)d;if(nsze==0)return false;Byte flbas=d[26];Byte format=(Byte)(flbas&15U);Byte lbads=d[128U+(UInt32)format*4U+2U];UInt32 blockSize=NvmeMath.NamespaceBlockSize(lbads);if(blockSize==0||blockSize>4096U)return false;if(_namespaceCount==_namespaceCapacity&&!GrowNamespaces())return false;KernelDeviceIdentifier ident=new(KernelDeviceBus.Logical,(UInt16)0x1D1D,(UInt16)0x4E56,0,0,0x010802U,0,(ci<<16)|(nsid&0xFFFFU));if(!KernelDrivers.DiscoverDevice(ident,new KernelDeviceHandle(c->DeviceHandle),out KernelDeviceHandle dh))return false;KernelStorageGeometry geometry=new(blockSize,blockSize,nsze,false,false);KernelContextualBlockDeviceCallbacks callbacks=new(&ReadBlocks,&WriteBlocks,&Flush);if(!KernelStorage.RegisterBlockDevice(dh,KernelStorageDeviceKind.Physical,geometry,callbacks,out KernelStorageDeviceHandle sh)){KernelDrivers.RemoveDevice(dh);return false;}Namespace* n=_namespaces+_namespaceCount;Clear((Byte*)n,(UInt64)sizeof(Namespace));n->Used=1;n->Controller=ci;n->Nsid=nsid;n->BlockSize=blockSize;n->Blocks=nsze;n->DeviceHandle=dh.Value;n->StorageHandle=sh.Value;_namespaceCount++;c->NamespaceCount++;return true;}
 static Boolean ReadBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes)=>Transfer(device,lba,count,buffer,bytes,false);
 static Boolean WriteBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes)=>Transfer(device,lba,count,buffer,bytes,true);
 static Boolean Flush(KernelDeviceHandle device){if(!FindNamespace(device,out Namespace* n))return false;Controller* c=_controllers+n->Controller;return SubmitIo(c,n->Nsid,0,0,0,0);}
 static Boolean Transfer(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes,Boolean write){if(buffer==null||count==0||!FindNamespace(device,out Namespace* n)||lba>=n->Blocks||count>n->Blocks-lba||(UInt64)bytes<(UInt64)count*n->BlockSize)return false;Controller* c=_controllers+n->Controller;if(!AllocPage(out KernelPhysicalAllocation bounce))return false;Byte* b=Direct(bounce);Boolean ok=true;for(UInt32 i=0;i<count&&ok;i++){if(write)Copy(buffer+(UInt64)i*n->BlockSize,b,n->BlockSize);ok=SubmitIo(c,n->Nsid,write?(Byte)1:(Byte)2,lba+i,bounce.StartAddress,1);if(ok&&!write)Copy(b,buffer+(UInt64)i*n->BlockSize,n->BlockSize);}KernelPhysicalMemory.TryRelease(bounce);return ok;}
 static Boolean AdminIdentify(Controller* c,UInt32 nsid,Byte cns,UInt64 prp)=>SubmitAdmin(c,6,nsid,prp,0,cns,0);
 static Boolean AdminCreateCq(Controller* c,UInt16 qid,UInt16 entries,UInt64 prp)=>SubmitAdmin(c,5,0,prp,0,((UInt32)(entries-1U)<<16)|qid,1U);
 static Boolean AdminCreateSq(Controller* c,UInt16 qid,UInt16 entries,UInt64 prp,UInt16 cqid)=>SubmitAdmin(c,1,0,prp,0,((UInt32)(entries-1U)<<16)|qid,((UInt32)cqid<<16)|1U);
 static Boolean SubmitAdmin(Controller* c,Byte opcode,UInt32 nsid,UInt64 prp1,UInt64 prp2,UInt32 cdw10,UInt32 cdw11){Byte* sq=Direct(c->Asq);Byte* e=sq+(UInt32)c->AdminTail*64U;for(UInt32 i=0;i<64;i++)e[i]=0;UInt16 cid=++c->AdminCid;e[0]=opcode;*(UInt16*)(e+2)=cid;*(UInt32*)(e+4)=nsid;*(UInt64*)(e+24)=prp1;*(UInt64*)(e+32)=prp2;*(UInt32*)(e+40)=cdw10;*(UInt32*)(e+44)=cdw11;c->AdminTail=(UInt16)((c->AdminTail+1U)%c->AdminEntries);W32(c->Mmio,NvmeMath.DoorbellOffset(0,false,c->DbStride),c->AdminTail);return WaitCompletion(c,0,cid,true);}
 static Boolean SubmitIo(Controller* c,UInt32 nsid,Byte opcode,UInt64 lba,UInt64 prp1,UInt16 blocks){Byte* sq=Direct(c->IoSq);Byte* e=sq+(UInt32)c->IoTail*64U;for(UInt32 i=0;i<64;i++)e[i]=0;UInt16 cid=++c->IoCid;e[0]=opcode;*(UInt16*)(e+2)=cid;*(UInt32*)(e+4)=nsid;*(UInt64*)(e+24)=prp1;if(opcode!=0){*(UInt64*)(e+40)=lba;*(UInt32*)(e+48)=(UInt32)(blocks-1U);}c->IoTail=(UInt16)((c->IoTail+1U)%c->IoEntries);W32(c->Mmio,NvmeMath.DoorbellOffset(1,false,c->DbStride),c->IoTail);return WaitCompletion(c,1,cid,false);}
 static Boolean WaitCompletion(Controller* c,UInt16 qid,UInt16 cid,Boolean admin){Byte* cq=Direct(admin?c->Acq:c->IoCq);UInt16 entries=admin?c->AdminEntries:c->IoEntries;UInt16 head=admin?c->AdminHead:c->IoHead;Byte phase=admin?c->AdminPhase:c->IoPhase;UInt32 spins=SpinLimit;while(spins-->0){Byte* e=cq+(UInt32)head*16U;UInt16 status=*(UInt16*)(e+14);if((status&1U)==phase){if(*(UInt16*)(e+12)!=cid)return false;Boolean ok=(status&0xFFFEU)==0;head++;if(head==entries){head=0;phase=(Byte)(phase==0?1:0);}if(admin){c->AdminHead=head;c->AdminPhase=phase;}else{c->IoHead=head;c->IoPhase=phase;}W32(c->Mmio,NvmeMath.DoorbellOffset(qid,true,c->DbStride),head);return ok;}}return false;}
 static Boolean WaitReady(Controller* c,Boolean ready){UInt32 spins=SpinLimit;while(spins-->0){Boolean r=(R32(c->Mmio,0x1C)&1U)!=0;if(r==ready)return true;}return false;}
 static Boolean FindNamespace(KernelDeviceHandle d,out Namespace* n){n=null;for(UInt32 i=0;i<_namespaceCount;i++){Namespace* x=_namespaces+i;if(x->Used!=0&&x->DeviceHandle==d.Value){n=x;return true;}}return false;}
 static Boolean AllocateTables(){_controllerCapacity=8U;_namespaceCapacity=16U;if(!AllocateControllerTable(_controllerCapacity,out _controllerAllocation,out _controllers))return false;if(!AllocateNamespaceTable(_namespaceCapacity,out _namespaceAllocation,out _namespaces)){KernelHeap.TryRelease(_controllerAllocation);_controllers=null;return false;}return true;}
 static Boolean GrowControllers(){UInt32 next=_controllerCapacity>0x3FFFFFFFU?UInt32.MaxValue:_controllerCapacity*2U;if(next<=_controllerCapacity)return false;if(!AllocateControllerTable(next,out KernelHeapAllocation a,out Controller* t))return false;CopyBytes((Byte*)_controllers,(Byte*)t,(UInt64)_controllerCount*(UInt64)sizeof(Controller));KernelHeapAllocation old=_controllerAllocation;_controllerAllocation=a;_controllers=t;_controllerCapacity=next;return KernelHeap.TryRelease(old);}
 static Boolean GrowNamespaces(){UInt32 next=_namespaceCapacity>0x3FFFFFFFU?UInt32.MaxValue:_namespaceCapacity*2U;if(next<=_namespaceCapacity)return false;if(!AllocateNamespaceTable(next,out KernelHeapAllocation a,out Namespace* t))return false;CopyBytes((Byte*)_namespaces,(Byte*)t,(UInt64)_namespaceCount*(UInt64)sizeof(Namespace));KernelHeapAllocation old=_namespaceAllocation;_namespaceAllocation=a;_namespaces=t;_namespaceCapacity=next;return KernelHeap.TryRelease(old);}
 static Boolean AllocateControllerTable(UInt32 capacity,out KernelHeapAllocation a,out Controller* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Controller),64UL,true,out a))return false;t=(Controller*)(nuint)a.Address;return true;}
 static Boolean AllocateNamespaceTable(UInt32 capacity,out KernelHeapAllocation a,out Namespace* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Namespace),64UL,true,out a))return false;t=(Namespace*)(nuint)a.Address;return true;}
 static Boolean AllocPage(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a); static Byte* Direct(KernelPhysicalAllocation a)=> (Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress); static void Zero(KernelPhysicalAllocation a){Byte* p=Direct(a);for(UInt32 i=0;i<4096;i++)p[i]=0;} static Boolean Fail(Controller* c){c->State=(Byte)NvmeControllerState.Failed;return false;}
 static UInt32 R32(UInt64 b,UInt32 o)=>*(UInt32*)(nuint)(b+o); static UInt64 R64(UInt64 b,UInt32 o)=>*(UInt64*)(nuint)(b+o); static void W32(UInt64 b,UInt32 o,UInt32 v)=>*(UInt32*)(nuint)(b+o)=v; static void W64(UInt64 b,UInt32 o,UInt64 v)=>*(UInt64*)(nuint)(b+o)=v; static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;} static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];} static void CopyBytes(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
