using System;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Heap;
namespace NovaOryn.Bus.Usb;
public static unsafe class KernelUsbBus
{
 private const UInt32 MaxHosts=16,InitialDevices=64,InitialInterfaces=128,ScratchBytes=4096;
 private struct HostRec{internal Byte Used;internal UInt64 Context,Prepare,Control,Bulk,Interrupt,ConfigureEndpoint,ConfigureHub;}
 private struct DevRec{internal Byte Used;internal UInt32 Host,Generic;internal Byte Address,ParentAddress,Port,Speed,Configuration,Class,SubClass,Protocol,MaxPacket0,Configs;internal UInt16 Vendor,Product,UsbVersion,Release;}
 private struct IfRec{internal Byte Used;internal UInt32 Device;internal Byte Number,Alternate,EndpointCount,Class,SubClass,Protocol,StringIndex;internal fixed Byte EpAddress[4];internal fixed Byte EpAttributes[4];internal fixed UInt16 EpMaxPacket[4];internal fixed Byte EpInterval[4];}
 private static HostRec* _hosts;private static DevRec* _devices;private static IfRec* _interfaces;private static Byte* _scratch;private static KernelHeapAllocation _ha,_da,_ia,_sa;private static UInt32 _hostCount,_deviceCount,_interfaceCount,_deviceCapacity,_interfaceCapacity,_enumerations,_failures;private static Boolean _initialized;
 public static Boolean Initialize(){if(_initialized)return true;if(!KernelHeap.IsInitialized()||!KernelDrivers.IsInitialized())return false;if(!Alloc(MaxHosts,(UInt32)sizeof(HostRec),out _ha,out Byte* hp)||!Alloc(InitialDevices,(UInt32)sizeof(DevRec),out _da,out Byte* dp)||!Alloc(InitialInterfaces,(UInt32)sizeof(IfRec),out _ia,out Byte* ip)||!KernelHeap.TryAllocate(ScratchBytes,64,true,out _sa))return false;_hosts=(HostRec*)hp;_devices=(DevRec*)dp;_interfaces=(IfRec*)ip;_scratch=(Byte*)(nuint)_sa.Address;_deviceCapacity=InitialDevices;_interfaceCapacity=InitialInterfaces;_initialized=true;return true;}
 public static UsbBusCapabilities GetCapabilities()=>new(_initialized,_hostCount,_deviceCount,_interfaceCount,_enumerations,_failures);public static UInt32 GetDeviceCount()=>_deviceCount;public static UInt32 GetInterfaceCount()=>_interfaceCount;
 public static Boolean RegisterHost(UsbHostCallbacks cb,out UsbHostHandle handle){handle=default;if(!_initialized||cb.PrepareDevice==null||cb.Control==null||cb.Bulk==null||cb.Interrupt==null||cb.ConfigureEndpoint==null||cb.ConfigureHub==null)return false;for(UInt32 i=0;i<MaxHosts;i++){HostRec* r=_hosts+i;if(r->Used!=0)continue;r->Used=1;r->Context=cb.Context;r->Prepare=(UInt64)(void*)cb.PrepareDevice;r->Control=(UInt64)(void*)cb.Control;r->Bulk=(UInt64)(void*)cb.Bulk;r->Interrupt=(UInt64)(void*)cb.Interrupt;r->ConfigureEndpoint=(UInt64)(void*)cb.ConfigureEndpoint;r->ConfigureHub=(UInt64)(void*)cb.ConfigureHub;_hostCount++;handle=new UsbHostHandle(i+1);return true;}return false;}
 public static Boolean EnumeratePort(UsbHostHandle host,Byte port,UsbSpeed speed,out UsbDeviceHandle device)=>EnumeratePort(host,0,port,speed,out device);
 public static Boolean EnumeratePort(UsbHostHandle host,Byte parentAddress,Byte port,UsbSpeed speed,out UsbDeviceHandle device)
 {device=default;if(!TryHost(host,out HostRec* h)||port==0)return Fail();Byte address=NextAddress();if(address==0)return Fail();var prepare=(delegate*<UInt64,Byte,Byte,UsbSpeed,Byte,Boolean>)(void*)h->Prepare;if(!prepare(h->Context,parentAddress,port,speed,address))return Fail();Clear(_scratch,ScratchBytes);UInt32 got=0;UsbSetupPacket get8=new(0x80,6,0x0100,0,8);if(!Ctl(h,0,0,&get8,_scratch,8,&got)||got<8)return Fail();Byte mps=_scratch[7];UsbSetupPacket setAddress=new(0,5,address,0,0);if(!Ctl(h,0,0,&setAddress,null,0,&got))return Fail();UsbSetupPacket getDevice=new(0x80,6,0x0100,0,18);if(!Ctl(h,address,0,&getDevice,_scratch,18,&got)||!UsbDescriptorParser.TryParseDevice(_scratch,got,out UsbDeviceDescriptor dd))return Fail();UsbSetupPacket getCfg9=new(0x80,6,0x0200,0,9);if(!Ctl(h,address,0,&getCfg9,_scratch,9,&got)||got<9)return Fail();UInt16 total=UsbDescriptorParser.Read16(_scratch+2);if(total<9||total>ScratchBytes)return Fail();UsbSetupPacket getCfg=new(0x80,6,0x0200,0,total);if(!Ctl(h,address,0,&getCfg,_scratch,total,&got)||got<total)return Fail();Byte configuration=_scratch[5];UsbSetupPacket setCfg=new(0,9,configuration,0,0);if(!Ctl(h,address,0,&setCfg,null,0,&got))return Fail();if(!AddDevice(host,address,parentAddress,port,speed,dd,mps,configuration,out device))return Fail();if(!ParseInterfaces(h,device,_scratch,total)){RemoveDevice(device);return Fail();}_enumerations++;return true;}
 public static Boolean TryGetDevice(UsbDeviceHandle h,out UsbDeviceInfo info){info=default;if(!TryDev(h,out DevRec* r))return false;UsbDeviceDescriptor d=new(r->UsbVersion,r->Class,r->SubClass,r->Protocol,r->MaxPacket0,r->Vendor,r->Product,r->Release,0,0,0,r->Configs);info=new UsbDeviceInfo(h,new KernelDeviceHandle(r->Generic),new UsbHostHandle(r->Host),r->Address,r->Port,(UsbSpeed)r->Speed,d,r->Configuration);return true;}
 public static Boolean TryGetInterface(UInt32 index,out UsbInterfaceInfo info){info=default;UInt32 found=0;for(UInt32 i=0;i<_interfaceCapacity;i++){IfRec* r=_interfaces+i;if(r->Used==0)continue;if(found++!=index)continue;UsbInterfaceDescriptor d=new(r->Number,r->Alternate,r->EndpointCount,r->Class,r->SubClass,r->Protocol,r->StringIndex);info=new UsbInterfaceInfo(new UsbDeviceHandle(r->Device),d,Ep(r,0),Ep(r,1),Ep(r,2),Ep(r,3));return true;}return false;}
 public static Boolean ConfigureHub(UsbDeviceHandle device,Byte portCount,Boolean multiTransactionTranslator){if(!TryDev(device,out DevRec* d)||!TryHost(new UsbHostHandle(d->Host),out HostRec* h))return false;var fn=(delegate*<UInt64,Byte,Byte,Boolean,Boolean>)(void*)h->ConfigureHub;return fn(h->Context,d->Address,portCount,multiTransactionTranslator);}
 public static Boolean ControlTransfer(UsbDeviceHandle device,UsbSetupPacket setup,Byte* buffer,UInt32 bytes,out UInt32 transferred){transferred=0;if(!TryDev(device,out DevRec* d)||!TryHost(new UsbHostHandle(d->Host),out HostRec* h))return false;UsbSetupPacket localSetup=setup;UInt32 localTransferred=0;Boolean ok=Ctl(h,d->Address,0,&localSetup,buffer,bytes,&localTransferred);transferred=localTransferred;return ok;}
 public static Boolean BulkTransfer(UsbDeviceHandle device,Byte endpoint,Byte* buffer,UInt32 bytes,out UInt32 transferred){transferred=0;if(!TryDev(device,out DevRec* d)||!TryHost(new UsbHostHandle(d->Host),out HostRec* h))return false;var fn=(delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean>)(void*)h->Bulk;UInt32 localTransferred=0;Boolean ok=fn(h->Context,d->Address,endpoint,buffer,bytes,&localTransferred);transferred=localTransferred;return ok;}
 public static Boolean InterruptTransfer(UsbDeviceHandle device,Byte endpoint,Byte* buffer,UInt32 bytes,out UInt32 transferred){transferred=0;if(!TryDev(device,out DevRec* d)||!TryHost(new UsbHostHandle(d->Host),out HostRec* h))return false;var fn=(delegate*<UInt64,Byte,Byte,Byte*,UInt32,UInt32*,Boolean>)(void*)h->Interrupt;UInt32 localTransferred=0;Boolean ok=fn(h->Context,d->Address,endpoint,buffer,bytes,&localTransferred);transferred=localTransferred;return ok;}
 private static Boolean AddDevice(UsbHostHandle host,Byte address,Byte parent,Byte port,UsbSpeed speed,UsbDeviceDescriptor d,Byte mps,Byte config,out UsbDeviceHandle h){h=default;Int32 slot=FreeDev();if(slot<0)return false;UInt32 cls=d.DeviceClass==0?0U:((UInt32)d.DeviceClass<<16)|((UInt32)d.DeviceSubClass<<8)|d.DeviceProtocol;KernelDeviceIdentifier id=new(KernelDeviceBus.Usb,d.VendorId,d.ProductId,0,0,cls,(Byte)d.DeviceRelease,((UInt32)host.Value<<24)|((UInt32)parent<<16)|((UInt32)port<<8)|address);if(!KernelDrivers.RegisterDevice(id,out KernelDeviceHandle generic))return false;DevRec* r=_devices+slot;r->Used=1;r->Host=host.Value;r->Generic=generic.Value;r->Address=address;r->ParentAddress=parent;r->Port=port;r->Speed=(Byte)speed;r->Configuration=config;r->Class=d.DeviceClass;r->SubClass=d.DeviceSubClass;r->Protocol=d.DeviceProtocol;r->MaxPacket0=mps;r->Configs=d.ConfigurationCount;r->Vendor=d.VendorId;r->Product=d.ProductId;r->UsbVersion=d.UsbVersion;r->Release=d.DeviceRelease;_deviceCount++;h=new UsbDeviceHandle((UInt32)slot+1);return true;}
 private static Boolean ParseInterfaces(HostRec* host,UsbDeviceHandle dev,Byte* p,UInt32 bytes){IfRec* current=null;UInt32 off=0;if(!TryDev(dev,out DevRec* owner))return false;while(off+2<=bytes){Byte len=p[off],type=p[off+1];if(len<2||off+len>bytes)return false;if(type==(Byte)UsbDescriptorType.Interface){if(!UsbDescriptorParser.TryParseInterface(p+off,len,out UsbInterfaceDescriptor d))return false;Int32 s=FreeIf();if(s<0)return false;current=_interfaces+s;current->Used=1;current->Device=dev.Value;current->Number=d.Number;current->Alternate=d.AlternateSetting;current->EndpointCount=d.EndpointCount>4?(Byte)4:d.EndpointCount;current->Class=d.Class;current->SubClass=d.SubClass;current->Protocol=d.Protocol;current->StringIndex=d.StringIndex;_interfaceCount++;UInt32 cls=((UInt32)d.Class<<16)|((UInt32)d.SubClass<<8)|d.Protocol;KernelDeviceIdentifier iid=new(KernelDeviceBus.Usb,owner->Vendor,owner->Product,0,0,cls,0,((UInt32)dev.Value<<8)|d.Number);KernelDrivers.RegisterDevice(iid,out _);}else if(type==(Byte)UsbDescriptorType.Endpoint&&current!=null&&UsbDescriptorParser.TryParseEndpoint(p+off,len,out UsbEndpointDescriptor e)){for(Byte n=0;n<4;n++){if(current->EpAddress[n]!=0)continue;current->EpAddress[n]=e.Address;current->EpAttributes[n]=e.Attributes;current->EpMaxPacket[n]=e.MaximumPacketSize;current->EpInterval[n]=e.Interval;var configure=(delegate*<UInt64,Byte,UsbEndpointDescriptor*,Boolean>)(void*)host->ConfigureEndpoint;if(!configure(host->Context,owner->Address,&e))return false;break;}}off+=len;}return true;}
 private static UsbEndpointDescriptor Ep(IfRec* r,Int32 i)=>new(r->EpAddress[i],r->EpAttributes[i],r->EpMaxPacket[i],r->EpInterval[i]);
 private static Boolean RemoveDevice(UsbDeviceHandle h){if(!TryDev(h,out DevRec* r))return false;KernelDrivers.RemoveDevice(new KernelDeviceHandle(r->Generic));Clear((Byte*)r,(UInt32)sizeof(DevRec));_deviceCount--;return true;}
 private static Boolean Ctl(HostRec* h,Byte addr,Byte ep,UsbSetupPacket* s,Byte* b,UInt32 n,UInt32* x){var fn=(delegate*<UInt64,Byte,Byte,UsbSetupPacket*,Byte*,UInt32,UInt32*,Boolean>)(void*)h->Control;return fn(h->Context,addr,ep,s,b,n,x);}private static Byte NextAddress(){for(Byte a=1;a<128;a++){Boolean used=false;for(UInt32 i=0;i<_deviceCapacity;i++)if((_devices+i)->Used!=0&&(_devices+i)->Address==a){used=true;break;}if(!used)return a;}return 0;}
 private static Boolean TryHost(UsbHostHandle h,out HostRec* r){r=null;if(h.Value==0||h.Value>MaxHosts)return false;r=_hosts+h.Value-1;return r->Used!=0;}private static Boolean TryDev(UsbDeviceHandle h,out DevRec* r){r=null;if(h.Value==0||h.Value>_deviceCapacity)return false;r=_devices+h.Value-1;return r->Used!=0;}private static Int32 FreeDev(){for(Int32 i=0;i<(Int32)_deviceCapacity;i++)if((_devices+i)->Used==0)return i;return -1;}private static Int32 FreeIf(){for(Int32 i=0;i<(Int32)_interfaceCapacity;i++)if((_interfaces+i)->Used==0)return i;return -1;}
 private static Boolean Alloc(UInt32 count,UInt32 size,out KernelHeapAllocation a,out Byte* p){a=default;p=null;if(!KernelHeap.TryAllocate((UInt64)count*size,64,true,out a))return false;p=(Byte*)(nuint)a.Address;return true;}private static void Clear(Byte* p,UInt32 n){for(UInt32 i=0;i<n;i++)p[i]=0;}private static Boolean Fail(){_failures++;return false;}
}
