<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType><TargetFramework>net10.0</TargetFramework><AllowUnsafeBlocks>true</AllowUnsafeBlocks><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable><DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences><NoStdLib>true</NoStdLib><NoConfig>true</NoConfig><RuntimeMetadataVersion>v4.0.30319</RuntimeMetadataVersion><GenerateAssemblyInfo>false</GenerateAssemblyInfo><GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute><DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences><AssemblyName>NovaOryn.Kernel.Synchronization</AssemblyName><RootNamespace>NovaOryn.Kernel.Synchronization</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NovaOryn.Freestanding.CoreLib\NovaOryn.Freestanding.CoreLib.csproj" />
    <ProjectReference Include="..\NovaOryn.Arch.X64\NovaOryn.Arch.X64.csproj" />
    <ProjectReference Include="..\NovaOryn.Kernel.Smp\NovaOryn.Kernel.Smp.csproj" />
    <ProjectReference Include="..\NovaOryn.Kernel.Scheduler\NovaOryn.Kernel.Scheduler.csproj" />
    <ProjectReference Include="..\NovaOryn.Kernel.Time\NovaOryn.Kernel.Time.csproj" />
  </ItemGroup>
</Project>
