<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup>
<ItemGroup>
<ProjectReference Include="../Commands/NovaOryn.Userland.Commands.csproj" />
<ProjectReference Include="../Settings/NovaOryn.Userland.Settings.csproj" />
<ProjectReference Include="../Fonts/NovaOryn.Userland.Fonts.csproj" />
<ProjectReference Include="../Images/NovaOryn.Userland.Images.csproj" />
<ProjectReference Include="../Drivers/NovaOryn.Userland.Drivers.csproj" />
</ItemGroup>
</Project>
