using System;
using NovaOryn.Kernel.AddressSpace;
using NovaOryn.Kernel.Drivers;
using NovaOryn.Kernel.Memory;
using NovaOryn.Kernel.Heap;
using NovaOryn.Kernel.Pci;
using NovaOryn.Kernel.Storage;
namespace NovaOryn.Kernel.Ahci;
/// <summary>AHCI 1.x PCI driver with SATA discovery, DMA command lists, IDENTIFY, read/write and flush.</summary>
public static unsafe class KernelAhci
{
 const UInt32 SpinLimit=40000000U; const UInt32 PxBase=0x100U,PxStride=0x80U;
 struct Controller{internal Byte Used;internal UInt16 Segment;internal Byte Bus,Device,Function;internal UInt32 DeviceHandle,Implemented,DiskCount;internal UInt64 Abar;}
 struct Disk{internal Byte Used,Port,Lba48;internal UInt32 Controller,DeviceHandle,StorageHandle,SectorSize;internal UInt64 Sectors;internal KernelPhysicalAllocation CommandList,Fis,CommandTable,Bounce;}
 static Controller* _controllers;static Disk* _disks;static KernelHeapAllocation _controllerAllocation,_diskAllocation;static UInt32 _controllerCapacity,_diskCapacity,_controllerCount,_diskCount;static Boolean _initialized;
 public static Boolean Initialize(){if(_initialized)return true;if(!KernelPci.IsInitialized()||!KernelStorage.IsInitialized()||!KernelPhysicalMemory.IsInitialized()||!KernelAddressSpace.IsInitialized())return false;if(!AllocateTables())return false;UInt32 count=KernelPci.GetDeviceCount();for(UInt32 i=0;i<count;i++){if(!KernelPci.TryGetDevice(i,out PciDeviceInfo pci)||!AhciMath.IsAhciClass(pci.ClassCode))continue;if(_controllerCount==_controllerCapacity&&!GrowControllers())return false;TryStartController(pci);} _initialized=true;return true;}
 public static Boolean IsInitialized()=>_initialized;public static AhciCapabilities GetCapabilities()=>new(_initialized,_controllerCount,_diskCount);
 public static Boolean TryGetController(UInt32 index,out AhciControllerInfo info){info=default;if(index>=_controllerCount)return false;Controller* c=_controllers+index;info=new AhciControllerInfo(new PciLocation(c->Segment,c->Bus,c->Device,c->Function),new KernelDeviceHandle(c->DeviceHandle),c->Implemented,c->DiskCount);return true;}
 public static Boolean TryGetDisk(UInt32 index,out AhciDiskInfo info){info=default;if(index>=_diskCount)return false;Disk* d=_disks+index;if(d->Used==0)return false;info=new AhciDiskInfo(d->Controller,d->Port,AhciPortType.Sata,d->Sectors,d->SectorSize,d->Lba48!=0,new KernelDeviceHandle(d->DeviceHandle),new KernelStorageDeviceHandle(d->StorageHandle));return true;}
 static Boolean TryStartController(PciDeviceInfo pci){if(!KernelPci.TryMapBar(pci.Location,5,out PciBarInfo bar,out UInt64 abar)||bar.Type==PciBarType.Io||bar.Length<0x1100UL)return false;if(!KernelPci.TryRead16(pci.Location,4,out UInt16 cmd)||!KernelPci.TryWrite16(pci.Location,4,(UInt16)(cmd|0x0006U)))return false;W32(abar,0x04,R32(abar,0x04)|(1U<<31));Controller* c=_controllers+_controllerCount;Clear((Byte*)c,(UInt64)sizeof(Controller));c->Used=1;c->Segment=pci.Location.Segment;c->Bus=pci.Location.Bus;c->Device=pci.Location.Device;c->Function=pci.Location.Function;c->DeviceHandle=pci.DeviceHandle.Value;c->Abar=abar;c->Implemented=R32(abar,0x0C);UInt32 ci=_controllerCount++;for(Byte p=0;p<32;p++){if((c->Implemented&(1U<<p))==0)continue;UInt64 pr=abar+PxBase+(UInt32)p*PxStride;if(!AhciMath.IsDevicePresent(R32(pr,0x28))||AhciMath.DecodeSignature(R32(pr,0x24))!=AhciPortType.Sata)continue;if(StartDisk(ci,c,p))c->DiskCount++;}return true;}
 static Boolean StartDisk(UInt32 ci,Controller* c,Byte port){if(_diskCount==_diskCapacity&&!GrowDisks())return false;Disk* d=_disks+_diskCount;Clear((Byte*)d,(UInt64)sizeof(Disk));d->Controller=ci;d->Port=port;if(!AllocPage(out d->CommandList)||!AllocPage(out d->Fis)||!AllocPage(out d->CommandTable)||!AllocPage(out d->Bounce))return false;Zero(d->CommandList);Zero(d->Fis);Zero(d->CommandTable);Zero(d->Bounce);UInt64 pr=c->Abar+PxBase+(UInt32)port*PxStride;if(!StopPort(pr))return false;W32(pr,0,(UInt32)d->CommandList.StartAddress);W32(pr,4,(UInt32)(d->CommandList.StartAddress>>32));W32(pr,8,(UInt32)d->Fis.StartAddress);W32(pr,12,(UInt32)(d->Fis.StartAddress>>32));if(!StartPort(pr))return false;if(!Identify(c,d))return false;KernelDeviceIdentifier id=new(KernelDeviceBus.Synthetic,(UInt16)0x1D1D,(UInt16)0x5341,0,0,0x010601U,0,(ci<<8)|port);if(!KernelDrivers.RegisterDevice(id,out KernelDeviceHandle dh))return false;KernelStorageGeometry geo=new(d->SectorSize,d->SectorSize,d->Sectors,false,false);KernelContextualBlockDeviceCallbacks cb=new(&ReadBlocks,&WriteBlocks,&Flush);if(!KernelStorage.RegisterBlockDevice(dh,KernelStorageDeviceKind.Physical,geo,cb,out KernelStorageDeviceHandle sh)){KernelDrivers.RemoveDevice(dh);return false;}d->DeviceHandle=dh.Value;d->StorageHandle=sh.Value;d->Used=1;_diskCount++;return true;}
 static Boolean Identify(Controller* c,Disk* d){Zero(d->Bounce);if(!Command(c,d,0xEC,0,1,false,true))return false;UInt16* w=(UInt16*)Direct(d->Bounce);Boolean lba48=(w[83]&(1U<<10))!=0;UInt64 sectors=lba48?AhciMath.DecodeLba48(w[100],w[101],w[102],w[103]):((UInt32)w[60]|((UInt32)w[61]<<16));UInt32 ss=AhciMath.DecodeLogicalSectorSize(w[106],w[117],w[118]);if(sectors==0||ss==0||ss>4096U)return false;d->Lba48=lba48?(Byte)1:(Byte)0;d->Sectors=sectors;d->SectorSize=ss;return true;}
 static Boolean ReadBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes)=>Transfer(device,lba,count,buffer,bytes,false);static Boolean WriteBlocks(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes)=>Transfer(device,lba,count,buffer,bytes,true);
 static Boolean Transfer(KernelDeviceHandle device,UInt64 lba,UInt32 count,Byte* buffer,UInt32 bytes,Boolean write){if(buffer==null||count==0||!FindDisk(device,out Disk* d)||lba>=d->Sectors||count>d->Sectors-lba||(UInt64)bytes<(UInt64)count*d->SectorSize)return false;Controller* c=_controllers+d->Controller;Byte* bounce=Direct(d->Bounce);for(UInt32 i=0;i<count;i++){if(write)Copy(buffer+(UInt64)i*d->SectorSize,bounce,d->SectorSize);Byte op=write?(d->Lba48!=0?(Byte)0x35:(Byte)0xCA):(d->Lba48!=0?(Byte)0x25:(Byte)0xC8);if(!Command(c,d,op,lba+i,1,write,false))return false;if(!write)Copy(bounce,buffer+(UInt64)i*d->SectorSize,d->SectorSize);}return true;}
 static Boolean Flush(KernelDeviceHandle device){if(!FindDisk(device,out Disk* d))return false;return Command(_controllers+d->Controller,d,d->Lba48!=0?(Byte)0xEA:(Byte)0xE7,0,0,false,false);}
 static Boolean Command(Controller* c,Disk* d,Byte ata,UInt64 lba,UInt16 sectors,Boolean write,Boolean identify){UInt64 pr=c->Abar+PxBase+(UInt32)d->Port*PxStride;UInt32 wait=SpinLimit;while(wait-->0&&((R32(pr,0x20)&(0x80U|0x08U))!=0)){}if((R32(pr,0x20)&(0x80U|0x08U))!=0)return false;Byte* cl=Direct(d->CommandList);Byte* ct=Direct(d->CommandTable);for(UInt32 i=0;i<1024;i++)cl[i]=0;for(UInt32 i=0;i<4096;i++)ct[i]=0;*(UInt16*)cl=(UInt16)(5U|(write?1U<<6:0U));*(UInt16*)(cl+2)=sectors==0?(UInt16)0:(UInt16)1;*(UInt32*)(cl+8)=(UInt32)d->CommandTable.StartAddress;*(UInt32*)(cl+12)=(UInt32)(d->CommandTable.StartAddress>>32);Byte* fis=ct;fis[0]=0x27;fis[1]=0x80;fis[2]=ata;if(!identify&&sectors!=0){fis[4]=(Byte)lba;fis[5]=(Byte)(lba>>8);fis[6]=(Byte)(lba>>16);if(d->Lba48!=0){fis[7]=0x40;fis[8]=(Byte)(lba>>24);fis[9]=(Byte)(lba>>32);fis[10]=(Byte)(lba>>40);fis[12]=(Byte)sectors;fis[13]=(Byte)(sectors>>8);}else{if(lba>0x0FFFFFFFUL)return false;fis[7]=(Byte)(0x40U|((UInt32)(lba>>24)&15U));fis[12]=(Byte)sectors;}}if(sectors!=0){Byte* p=ct+0x80;UInt32 byteCount=identify?512U:d->SectorSize;*(UInt32*)p=(UInt32)d->Bounce.StartAddress;*(UInt32*)(p+4)=(UInt32)(d->Bounce.StartAddress>>32);*(UInt32*)(p+12)=(byteCount-1U)|(1U<<31);}W32(pr,0x10,0xFFFFFFFFU);W32(pr,0x38,1U);wait=SpinLimit;while(wait-->0){UInt32 ci=R32(pr,0x38);if((ci&1U)==0){UInt32 isr=R32(pr,0x10);return (isr&(1U<<30))==0;}}return false;}
 static Boolean StopPort(UInt64 p){UInt32 cmd=R32(p,0x18);cmd&=~1U;W32(p,0x18,cmd);UInt32 s=SpinLimit;while(s-->0&&(R32(p,0x18)&(1U<<15))!=0){}if((R32(p,0x18)&(1U<<15))!=0)return false;W32(p,0x18,R32(p,0x18)&~(1U<<4));s=SpinLimit;while(s-->0&&(R32(p,0x18)&(1U<<14))!=0){}return (R32(p,0x18)&(1U<<14))==0;}
 static Boolean StartPort(UInt64 p){UInt32 s=SpinLimit;while(s-->0&&(R32(p,0x18)&(1U<<15))!=0){}if((R32(p,0x18)&(1U<<15))!=0)return false;W32(p,0x18,R32(p,0x18)|(1U<<4)|1U);return true;}
 static Boolean FindDisk(KernelDeviceHandle device,out Disk* d){d=null;for(UInt32 i=0;i<_diskCount;i++){Disk* x=_disks+i;if(x->Used!=0&&x->DeviceHandle==device.Value){d=x;return true;}}return false;}
 static Boolean AllocateTables(){_controllerCapacity=4U;_diskCapacity=8U;if(!AllocateControllerTable(_controllerCapacity,out _controllerAllocation,out _controllers))return false;if(!AllocateDiskTable(_diskCapacity,out _diskAllocation,out _disks)){KernelHeap.TryRelease(_controllerAllocation);_controllers=null;return false;}return true;}static Boolean GrowControllers(){UInt32 next=_controllerCapacity>0x3FFFFFFFU?UInt32.MaxValue:_controllerCapacity*2U;if(next<=_controllerCapacity)return false;if(!AllocateControllerTable(next,out KernelHeapAllocation a,out Controller* t))return false;CopyBytes((Byte*)_controllers,(Byte*)t,(UInt64)_controllerCount*(UInt64)sizeof(Controller));KernelHeapAllocation old=_controllerAllocation;_controllerAllocation=a;_controllers=t;_controllerCapacity=next;return KernelHeap.TryRelease(old);}static Boolean GrowDisks(){UInt32 next=_diskCapacity>0x3FFFFFFFU?UInt32.MaxValue:_diskCapacity*2U;if(next<=_diskCapacity)return false;if(!AllocateDiskTable(next,out KernelHeapAllocation a,out Disk* t))return false;CopyBytes((Byte*)_disks,(Byte*)t,(UInt64)_diskCount*(UInt64)sizeof(Disk));KernelHeapAllocation old=_diskAllocation;_diskAllocation=a;_disks=t;_diskCapacity=next;return KernelHeap.TryRelease(old);}static Boolean AllocateControllerTable(UInt32 capacity,out KernelHeapAllocation a,out Controller* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Controller),64UL,true,out a))return false;t=(Controller*)(nuint)a.Address;return true;}static Boolean AllocateDiskTable(UInt32 capacity,out KernelHeapAllocation a,out Disk* t){a=default;t=null;if(!KernelHeap.TryAllocate((UInt64)capacity*(UInt64)sizeof(Disk),64UL,true,out a))return false;t=(Disk*)(nuint)a.Address;return true;}static Boolean AllocPage(out KernelPhysicalAllocation a)=>KernelPhysicalMemory.TryAllocate(1,1,out a);static Byte* Direct(KernelPhysicalAllocation a)=>(Byte*)(nuint)(KernelAddressSpace.DirectMapBase+a.StartAddress);static void Zero(KernelPhysicalAllocation a){Byte* p=Direct(a);for(UInt32 i=0;i<4096;i++)p[i]=0;}static UInt32 R32(UInt64 b,UInt32 o)=>*(UInt32*)(nuint)(b+o);static void W32(UInt64 b,UInt32 o,UInt32 v)=>*(UInt32*)(nuint)(b+o)=v;static void Clear(Byte* p,UInt64 n){for(UInt64 i=0;i<n;i++)p[i]=0;}static void Copy(Byte* s,Byte* d,UInt32 n){for(UInt32 i=0;i<n;i++)d[i]=s[i];}static void CopyBytes(Byte* s,Byte* d,UInt64 n){for(UInt64 i=0;i<n;i++)d[i]=s[i];}
}
