<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NovaOrynSkipPublicApiValidation>true</NovaOrynSkipPublicApiValidation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NovaOryn.Memory.Contracts\NovaOryn.Memory.Contracts.csproj" />
    <ProjectReference Include="..\..\src\NovaOryn.Boot.Memory\NovaOryn.Boot.Memory.csproj" />
  </ItemGroup>
</Project>
